const commonGlobals = {
  AbortController: "readonly",
  Array: "readonly",
  Boolean: "readonly",
  Buffer: "readonly",
  clearInterval: "readonly",
  clearTimeout: "readonly",
  console: "readonly",
  crypto: "readonly",
  Date: "readonly",
  Error: "readonly",
  fetch: "readonly",
  FormData: "readonly",
  global: "readonly",
  globalThis: "readonly",
  Headers: "readonly",
  Intl: "readonly",
  JSON: "readonly",
  Map: "readonly",
  Math: "readonly",
  Number: "readonly",
  Object: "readonly",
  process: "readonly",
  Promise: "readonly",
  RegExp: "readonly",
  Response: "readonly",
  Request: "readonly",
  Set: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
  String: "readonly",
  structuredClone: "readonly",
  Symbol: "readonly",
  TextDecoder: "readonly",
  TextEncoder: "readonly",
  TypeError: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
  WeakMap: "readonly",
  WeakSet: "readonly",
};

const baseRules = {
  "no-constant-condition": ["error", { checkLoops: false }],
  "no-dupe-args": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-empty": ["error", { allowEmptyCatch: true }],
  "no-redeclare": "error",
  "no-self-assign": "error",
  "no-unreachable": "error",
  "no-undef": "error",
  "no-unused-vars": [
    "warn",
    {
      argsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
      varsIgnorePattern: "^_",
    },
  ],
};

export default [
  {
    ignores: [
      "backend/data/**",
      "backend/node_modules/**",
      "coverage/**",
      "dist/**",
      "node_modules/**",
    ],
  },
  {
    files: ["backend/src/**/*.js", "backend/scripts/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: commonGlobals,
    },
    rules: baseRules,
  },
  {
    files: ["backend/**/*.cjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: {
        ...commonGlobals,
        __dirname: "readonly",
        __filename: "readonly",
        exports: "writable",
        module: "writable",
        require: "readonly",
      },
    },
    rules: baseRules,
  },
];
