#!/usr/bin/env node

import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '../..');

const steps = [
  'check:op04',
  'check:qlt04b',
  'check:qltpaybridge01',
  'check:seferscore01',
  'check:roadmaplockaimarketplace01',
  'check:publiclanding01',
  'check:publiclandingplatformfirst01',
  'check:publiclandingfinalpromise01',
  'check:leadcapture01',
  'check:onboardingreview01',
  'check:onboardingreviewfinalaudit01',
  'check:invitebasedmembership01',
  'check:verifiedsupplier01',
  'check:suppliermatching01',
  'check:supplieroffercollect01',
  'check:copilotofferanalysis01',
  'check:uxmarketplacepanels01',
  'check:productflowbuttonaudit01',
  'check:agreementsourceshiftlineage01',
  'check:marketplacefreetooperate01',
  'check:m44telematicst1t5',
  'check:telematicsproviderhub01',
  'check:safedrive01',
  'check:offerrankingquality01',
  'check:pay01e',
  'check:paysafe01',
  'check:web01a',
  'check:web01b',
  'check:uxsuperadminoverviewcleanup01',
  'check:uxsuperadminpanelclarity01',
  'check:uxsuperadminlabelpolish01',
  'check:uxsuperadminlivemonitoring01',
  'check:uxsuperadminauditpanel01',
  'check:uxsuperadminqualitypanel01',
  'check:uxsuperadmincommercialflow01',
  'check:uxsuperadminfielddispatchdiscovery01',
  'check:uxsuperadminfieldacceptancecenter01',
  'check:cop01e',
  'check:cop02a',
  'check:cop02b',
  'check:cop03a',
  'check:cop03afix01',
  'check:cop03afix02',
  'check:cop03b',
  'check:cop03c',
  'check:cop03cfix01',
  'check:uxkvkk01',
  'check:docsstate01',
  'check:e2esmoke01',
  'check:fieldlaunch01',
  'check:cop03cfix02',
  'check:cop04afix03',
  'check:cop04afix04',
  'check:cop03cfix03',
  'check:cop04a',
  'check:cop04afix02',
  'check:cop04afix01',
  'check:cop04b',
  'check:cop04bfix01',
  'check:cop04bfix02',
  'check:cop04bfix03',
  'check:cop04bfix04',
  'check:cop04bfix05',
  'check:cop04bfix06',
  'check:cop04bfix07',
  'check:cop04bfix08',
  'check:copilotroletaskmatrix01',
  'check:copilotairoadmap01',
  'check:copilotdemandintake01',
  'check:copilotdemandagreement01',
  'check:copilotrfqprep01',
  'check:copilothumanapproval01',
  'check:copilotexceldemandimport01',
  'check:addressgeocodingconfidence01',
  'check:copilotstoproutedraft01',
  'check:osrmroutedraftfromexcel01',
  'check:copilotroutereviewhumanapproval01',
  'check:exceltoroutereadinessredteam01',
  'check:copiloteblockruntimeanswerintegration01',
  'check:copilotguidedtaskengine01',
  'check:copilotdynamicquestionengine01',
  'check:copilotsmartdiagnosticengine01',
  'check:copilotrootcauseengine01',
  'check:copilotriskscoringengine01',
  'check:copilotclarifyingquestionengine01',
  'check:copilotworkflowreasoningengine01',
  'check:copilotoperationhealthengine01',
  'check:copilotnextbestactionengine01',
  'check:copilotplanreviewengine01',
  'check:hotfilesplitaichatcomposers01',
  'check:hotfilesplitwebpanels01',
  'check:copilotreasoninganswercomposer01',
  'check:ai03bparaphraseintentaudit01',
  'check:ai03bsemanticvisibleaudit01',
  'check:ai03bsemanticvisiblelivematrix01',
  'check:seferabireasoningassistant01',
  'check:seferabiallrolesreasoningassistant01',
  'check:seferabiturkishterminology01',
  'check:seferabiturkishuserfacinglanguage01',
  'check:copilotcontextmemorytaskstate01',
  'check:uxcopilotsmartchips01',
  'check:uxcopilotpersona01',
  'check:uxcopilotterminal01',
  'check:uxseferabilauncher01',
  'check:seferabiterminalhumanize01',
  'check:copliveaccept01',
  'check:boardingops01a',
  'check:bugrouteimpactpreviewbutton01',
  'check:uxrouteimpactpreviewcompact01',
  'check:uxcontractconversionopsbridgeclarity01',
  'check:shiftdispatchapprovalfix01',
  'check:boardingchangerequestentry01',
  'check:uiactionwiringaudit01',
  'check:boardingops01b',
  'check:boardingops01c',
  'check:routechangefinal01',
  'check:dynamicsavings01',
  'check:scriptharnessconsolidation01',
  'check:authstepupdevtoggle01',
  'check:authstepupproviderlocaldefault01',
  'check:docsbrandcleanup01',
  'check:etasanity01',
  'check:etaosrm01',
  'check:etaosrm02',
  'check:uxcollapsiblepanels01',
  'check:uxpanelstructure02',
  'check:uxpanelinventory02a',
  'check:uxpanelstructure02b',
  'check:uxroomvehiclestelematicsfix',
  'check:roomvehicledriveruppercase01',
  'check:uxroompanelclarity01',
  'check:uxroomopspaneltabs01',
  'check:uxroomopsrelationshippolish01',
  'check:uxroomshiftstabs01',
  'check:uxroomshiftsdensitydedup01',
  'check:uxpremiumcriticalfixroom01',
  'check:uxschoolorganizationpanels01',
  'check:uxcompanyshiftstabs01',
  'check:uxcompanymobileactionclarity01',
  'check:uxcompanypersonelaccessmobileparity01',
  'check:uxpremiumcriticalfixagreementsdetail01',
  'check:uxcompanyagreementsmobileparity01',
  'check:uxcompanyopspaneltabs01',
  'check:uxcompanyqualitytabs01',
  'check:uxcompanypanelssmoke01',
  'check:uxpaneltabsfix01',
  'check:uxlivemaptabsfix01',
    'check:uxlivemaptabssimplify01',
    'check:uxpanelreality02c',
    'check:uxpanelrealitycleanup02d',
  'check:uxpanellayoutwidth02cfix01',
  'check:uxpanellayoutwidth02cfix02',
  'check:uxpanellayoutwidth02cfix03',
  'check:uxnav01',
  'check:uxbrandloginpremium01',
  'check:uxmobilewebshellclarity01',
  'check:uxmobileallrolespanelfix01',
  'check:uxroomcompanyshiftsmobilecardfix01',
  'check:uxshiftsresponsivelayoutfix01',
  'check:uxmobileoverflowminimapreadability01',
  'check:uxmobileoverflowminimappolish02',
  'check:uxdensity01',
  'check:uxpanelstandardarchitecture01',
  'check:finaluxsmoke01',
  'check:uxlivepanelsmokeaudit01',
  'check:uxmobileallrolespanelaudit01',
  'check:uxpremiumcriticaluxfixcleanup01',
  'check:uxsmokepassminusevidence01',
  'check:uxlivepanelpremiumsmoke01',
  'check:uxsmokepassminuszero01',
  'check:mobilewebfinal01',
  'check:uxparentpersonelliveerrorclarity01',
  'check:livetrackingfinal01',
  'check:driverflowfinal01',
  'check:qualitygatefinal01',
  'check:testqualityandflakeaudit01',
  'check:dashboardbulkendpoint01',
  'check:cachecoalescingandbackoff01',
  'check:requeststormresilience01',
  'check:productionratelimitpolicy01',
  'check:airesponsesemanticqualitygate01',
  'check:loadtest2000users01',
  'check:dbpoolandapiscaling01',
  'check:observabilitymonitoringalerting01',
  'check:backendlintwarningburndown01',
  'check:dataintegrityandrecovery01',
  'check:roledataisolationredteam01',
  'check:securitykvkkfinal01',
  'check:auditlogandapprovaltrace01',
];

function runStep(scriptName) {
  return new Promise((resolve) => {
    const child = spawn('npm', ['run', scriptName], {
      cwd: repoRoot,
      env: process.env,
      stdio: 'inherit',
      shell: true,
    });

    child.on('exit', (code) => resolve(code ?? 1));
  });
}

async function main() {
  console.log('=== PRODUCT EXTENSIONS CHECK CHAIN ===');
  console.log(`Repo root: ${repoRoot}`);
  console.log(`Steps: ${steps.join(', ')}`);

  for (const [index, scriptName] of steps.entries()) {
    console.log(`\n--- ${String(index + 1).padStart(2, '0')}/${steps.length} ${scriptName} ---`);
    const code = await runStep(scriptName);
    if (code !== 0) {
      console.log(`FAIL ${scriptName}`);
      process.exit(code ?? 1);
    }
  }

  console.log('\n=== PRODUCT EXTENSIONS CHECK CHAIN PASS ===');
}

main().catch((err) => {
  console.error(err?.stack || String(err));
  process.exit(1);
});
