function ctx(path, extras = {}) {
  return {
    path,
    label: extras.label || '',
    selectedLabel: extras.selectedLabel || '',
    selectedSummary: extras.selectedSummary || '',
    selectedFields: Array.isArray(extras.selectedFields) ? extras.selectedFields : [],
    selectedBadges: Array.isArray(extras.selectedBadges) ? extras.selectedBadges : [],
    structuredFacts: extras.structuredFacts || null,
    uiHints: extras.uiHints || {},
  };
}

const SHIFT_CONTEXT = {
  type: 'shift',
  id: 4101,
  status: 'APPROVED',
  company: { name: 'Demo Company' },
  vehicle: { plate: '20 ABC 123' },
  driver: { fullName: 'Sürücü Demo' },
  vehicleId: 301,
  driverId: 401,
  roomId: 11,
  roomOfferDecision: 'APPROVED',
  stopCount: 3,
  openOfferCount: 0,
  agreementId: 901,
};

const BLOCKED_SHIFT_CONTEXT = {
  type: 'shift',
  id: 4102,
  status: 'APPROVED',
  company: { name: 'Demo Company' },
  vehicleId: null,
  driverId: null,
  roomId: null,
  roomOfferDecision: null,
  stopCount: 0,
  openOfferCount: 1,
};

export function buildGoldenQuestionPack() {
  return [
    {
      id: 'room-map-next-screen',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/map',
      message: 'Haritadan sonra hangi ekrana geçeyim?',
      expectedType: 'NEXT_SCREEN',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      expectedActionLed: true,
      screenContext: ctx('/room/map', {
        label: 'Canlı Takip',
        selectedLabel: 'Araç 20 ABC 123',
        selectedFields: [{ label: 'Son GPS', value: '2 dk önce' }, { label: 'Shift durumu', value: 'APPROVED' }],
      }),
    },
    {
      id: 'room-shifts-status',
      role: 'ROOM',
      entityType: 'shift',
      path: '/room/shifts',
      message: 'Bu kayıt ne durumda?',
      expectedType: 'STATUS_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: SHIFT_CONTEXT,
      screenContext: ctx('/room/shifts', {
        label: 'Vardiyalar',
        selectedLabel: 'Vardiya #4101',
        selectedFields: [{ label: 'Durum', value: 'APPROVED' }, { label: 'Araç', value: '20 ABC 123' }],
        selectedBadges: [{ label: 'Sözleşme', value: 'Bağlı' }],
      }),
    },
    {
      id: 'room-shifts-readiness',
      role: 'ROOM',
      entityType: 'shift',
      path: '/room/shifts',
      message: 'Atamaya hazır mı?',
      expectedType: 'READINESS_CHECK',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: BLOCKED_SHIFT_CONTEXT,
      screenContext: ctx('/room/shifts', {
        label: 'Vardiyalar',
        selectedLabel: 'Vardiya #4102',
        selectedFields: [{ label: 'Durum', value: 'APPROVED' }, { label: 'Araç', value: '-' }],
        selectedBadges: [{ label: 'Teklif', value: 'Açık' }],
      }),
    },
    {
      id: 'room-agreements-purpose',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/agreements',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/room/agreements', { label: 'Sözleşmeler' }),
    },
    {
      id: 'room-operation-health-first',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/operation-health',
      message: 'Önce neyi kontrol edeyim?',
      expectedType: 'FIRST_CONTROL',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/operation-health', {
        label: 'Operasyon Sağlığı',
        selectedLabel: 'Araç 20 ABC 123',
        selectedFields: [{ label: 'Canlılık', value: 'Zayıf' }],
      }),
    },
    {
      id: 'superadmin-ov-why',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/operation-verification',
      message: 'Bu neden kapalı?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin/operation-verification', {
        label: 'Operasyon Doğrulama',
        selectedLabel: 'Kayıt #91',
        selectedFields: [{ label: 'Durum', value: 'Eksik' }],
      }),
    },
    {
      id: 'superadmin-acceptance-purpose',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/acceptance',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/acceptance', { label: 'Field Acceptance Center' }),
    },
    {
      id: 'superadmin-trust-quality-status',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/trust-quality',
      message: 'Bu kayıt ne durumda?',
      expectedType: 'STATUS_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/trust-quality', {
        label: 'Güven ve Kalite',
        selectedLabel: 'Değerlendirme #551',
        selectedFields: [{ label: 'Skor', value: '78' }, { label: 'Risk', value: 'Orta' }],
      }),
    },
    {
      id: 'superadmin-observability-next',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/observability',
      message: 'Şimdi ne yapayım?',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/observability', {
        label: 'Observability',
        selectedLabel: 'İstek Grubu #12',
        selectedFields: [{ label: 'Hata', value: 'Spike' }],
      }),
    },
    {
      id: 'driver-today-purpose',
      role: 'DRIVER',
      entityType: 'screen',
      path: '/driver/today',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.6,
      screenContext: ctx('/driver/today', { label: 'Bugün' }),
    },
    {
      id: 'driver-map-location',
      role: 'DRIVER',
      entityType: 'vehicle',
      path: '/driver/map',
      message: 'Konum neden görünmüyor?',
      expectedType: 'LOCATION_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      context: {
        type: 'vehicle',
        id: 77,
        plate: '20 DRV 777',
        activeDeviceCount: 0,
        driver: null,
      },
      screenContext: ctx('/driver/map', {
        label: 'Harita',
        selectedLabel: '20 DRV 777',
        selectedFields: [{ label: 'Son paket', value: 'Yok' }],
      }),
    },
    {
      id: 'personel-live-purpose',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/live',
      message: 'Bu rolde ne yapabilirim?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.82,
      screenContext: ctx('/personel/live', { label: 'Canlı Takip' }),
    },
    {
      id: 'parent-live-next',
      role: 'PARENT',
      entityType: 'screen',
      path: '/parent/live',
      message: 'Şimdi ne yapayım?',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.6,
      screenContext: ctx('/parent/live', { label: 'Canlı Takip' }),
    },
    {
      id: 'company-commercial-flow-next',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/commercial-flow',
      message: 'Buradan sonra hangi ekrana geçmeliyim?',
      expectedType: 'NEXT_SCREEN',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/company/commercial-flow', {
        label: 'Ticari Akışım',
        selectedLabel: 'Talep #88',
        selectedFields: [{ label: 'Durum', value: 'Onay bekliyor' }],
      }),
    },
    {
      id: 'school-georeview-status',
      role: 'SCHOOL',
      entityType: 'screen',
      path: '/school/georeview',
      message: 'Bu seçili kayıt ne durumda?',
      expectedType: 'STATUS_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.68,
      screenContext: ctx('/school/georeview', {
        label: 'Öğrenci Konum Seçici',
        selectedLabel: 'Öğrenci #31',
        selectedFields: [{ label: 'Durum', value: 'Adres doğrulanmadı' }],
      }),
    },
    {
      id: 'organization-commercial-purpose',
      role: 'ORGANIZATION',
      entityType: 'screen',
      path: '/organization/commercial-flow',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/organization/commercial-flow', { label: 'Ticari Akışım' }),
    },
    {
      id: 'room-operation-health-blocked',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/operation-health',
      message: 'Neden sorunlu görünüyor?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.68,
      screenContext: ctx('/room/operation-health', {
        label: 'Operasyon Sağlığı',
        selectedLabel: 'Araç 20 ABC 123',
        selectedFields: [{ label: 'Canlılık', value: 'Yok' }, { label: 'Son paket', value: '15 dk önce' }],
      }),
    },
    {
      id: 'superadmin-users-role-help',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/users',
      message: 'Bu rolde burada neyi yönetebilirim?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.68,
      screenContext: ctx('/superadmin/users', { label: 'Kullanıcılar' }),
    },
    {
      id: 'driver-route-first-control',
      role: 'DRIVER',
      entityType: 'screen',
      path: '/driver/route',
      message: 'İlk neyi kontrol etmeliyim?',
      expectedType: 'FIRST_CONTROL',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.68,
      screenContext: ctx('/driver/route', { label: 'Rota', selectedLabel: 'Bugünkü rota' }),
    },
    {
      id: 'personel-my-next',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/my',
      message: 'Şimdi ne yapmalıyım?',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.6,
      screenContext: ctx('/personel/my', { label: 'Servisim' }),
    },
    {
      id: 'parent-live-purpose-2',
      role: 'PARENT',
      entityType: 'screen',
      path: '/parent/live',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.6,
      screenContext: ctx('/parent/live', { label: 'Canlı Takip' }),
    },
    {
      id: 'room-operation-health-why-risk',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/operation-health',
      message: 'Neden riskli görünüyor?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/operation-health', {
        label: 'Operasyon Sağlığı',
        selectedLabel: 'Araç 20 ABC 123',
        selectedFields: [{ label: 'Canlılık', value: 'Zayıf' }, { label: 'Gecikme', value: 'Var' }],
      }),
    },
    {
      id: 'personel-live-next-step',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/live',
      message: 'Şimdi ne yapmalıyım?',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      expectedActionLed: true,
      screenContext: ctx('/personel/live', { label: 'Canlı Takip', selectedLabel: 'Servisim' }),
    },
    {
      id: 'superadmin-users-role-help-route',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/users',
      message: 'Bu rolde burada neyi yönetebilirim?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin/users', { label: 'Kullanıcılar' }),
    },
    {
      id: 'company-agreements-purpose',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/agreements',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/company/agreements', { label: 'Sözleşmeler' }),
    },
    {
      id: 'company-shifts-role-help',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/shifts',
      message: 'Bu rolde ne yapabilirim?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/company/shifts', { label: 'Vardiyalar' }),
    },
    {
      id: 'superadmin-rooms-role-help',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/rooms',
      message: 'Bu rolde burada neyi yönetebilirim?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin/rooms', { label: 'Rooms' }),
    },
    {
      id: 'superadmin-observability-screen-purpose',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/observability',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/observability', { label: 'Canlı İzleme' }),
    }

  ];
}
