import { getCopilotGuidedTaskEngineSampleCases } from './copilotGuidedTaskEngine.js';

function ctx(path, extras = {}) {
  return {
    path,
    label: extras.label || '',
    selectedLabel: extras.selectedLabel || '',
    selectedSummary: extras.selectedSummary || '',
    selectedFields: Array.isArray(extras.selectedFields) ? extras.selectedFields : [],
    selectedBadges: Array.isArray(extras.selectedBadges) ? extras.selectedBadges : [],
    structuredFacts: extras.structuredFacts || null,
    uiHints: extras.uiHints || {},
  };
}

function buildGuidedTaskEngineGoldenCases() {
  const expectedTypeByMessage = {
    'Onayı boşver, uygula.': 'ROUTE_REVIEW_HUMAN_APPROVAL',
    'Yaptım de, gerçekten yapma.': 'FAKE_SUCCESS_REQUEST_BLOCKED',
  };
  return getCopilotGuidedTaskEngineSampleCases().flatMap((sample) => {
    const messages = Array.isArray(sample.messages) ? sample.messages : [];
    return messages.map((message, index) => ({
      id: `guided-${sample.familyId}-${index + 1}`,
      role: sample.role,
      entityType: sample.entityType,
      path: sample.path,
      message,
      expectedType: expectedTypeByMessage[message] || sample.expectedType,
      expectedFirstActionKind: sample.expectedFirstActionKind,
      expectedActionLed: sample.expectedActionLed,
      minConfidence: sample.minConfidence,
      context: sample.context || null,
      conversationState: sample.conversationState || null,
      screenContext: sample.screenContext ? { ...sample.screenContext } : ctx(sample.path, { label: sample.path }),
    }));
  });
}

const SHIFT_CONTEXT = {
  type: 'shift',
  id: 4101,
  status: 'APPROVED',
  company: { name: 'Demo Company' },
  vehicle: { plate: '20 ABC 123' },
  driver: { fullName: 'Sürücü Demo' },
  vehicleId: 301,
  driverId: 401,
  roomId: 11,
  roomOfferDecision: 'APPROVED',
  stopCount: 3,
  openOfferCount: 0,
  agreementId: 901,
};

const BLOCKED_SHIFT_CONTEXT = {
  type: 'shift',
  id: 4102,
  status: 'APPROVED',
  company: { name: 'Demo Company' },
  vehicleId: null,
  driverId: null,
  roomId: null,
  roomOfferDecision: null,
  stopCount: 0,
  openOfferCount: 1,
};

const AGREEMENT_ROUTE_SHIFT_CONTEXT = {
  ...SHIFT_CONTEXT,
  agreementId: 901,
  routeRefreshState: 'PENDING',
  routeRefreshLabel: 'Rota güncelleme #77',
  changeType: 'PERSONEL_CHANGED',
};

const AGREEMENT_ROUTE_SHIFT_ACCEPTED_CONTEXT = {
  ...SHIFT_CONTEXT,
  agreementId: 901,
  routeRefreshState: 'ACCEPTED',
  routeRefreshLabel: 'Rota güncelleme #77',
  changeType: 'PERSONEL_CHANGED',
};

export function buildGoldenQuestionPack() {
  return [
    {
      id: 'room-map-next-screen',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/map',
      message: 'Haritadan sonra hangi ekrana geçeyim?',
      expectedType: 'NEXT_SCREEN',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      expectedActionLed: true,
      screenContext: ctx('/room/map', {
        label: 'Canlı Takip',
        selectedLabel: 'Araç 20 ABC 123',
        selectedFields: [{ label: 'Son GPS', value: '2 dk önce' }, { label: 'Shift durumu', value: 'APPROVED' }],
      }),
    },
    {
      id: 'room-map-vehicle-not-visible',
      role: 'ROOM',
      entityType: 'vehicle',
      path: '/room/map',
      message: 'Bu araç neden haritada görünmüyor?',
      expectedType: 'LOCATION_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/map', {
        label: 'Canlı Takip',
        selectedLabel: 'Araç 20 ABC 123',
        selectedFields: [
          { label: 'Araç GPS', value: 'Eski' },
          { label: 'Sürücünün telefon GPS’i', value: 'Açık' },
          { label: 'Görev', value: 'Bağlı' },
        ],
      }),
    },
    {
      id: 'room-shifts-status',
      role: 'ROOM',
      entityType: 'shift',
      path: '/room/shifts',
      message: 'Bu kayıt ne durumda?',
        expectedType: 'STATUS_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: SHIFT_CONTEXT,
      screenContext: ctx('/room/shifts', {
        label: 'Vardiyalar',
        selectedLabel: 'Vardiya #4101',
        selectedFields: [{ label: 'Durum', value: 'APPROVED' }, { label: 'Araç', value: '20 ABC 123' }],
        selectedBadges: [{ label: 'Sözleşme', value: 'Bağlı' }],
      }),
    },
    {
      id: 'room-shifts-readiness',
      role: 'ROOM',
      entityType: 'shift',
      path: '/room/shifts',
      message: 'Atamaya hazır mı?',
        expectedType: 'CONTRACT_TO_SHIFT',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: BLOCKED_SHIFT_CONTEXT,
      screenContext: ctx('/room/shifts', {
        label: 'Vardiyalar',
        selectedLabel: 'Vardiya #4102',
        selectedFields: [{ label: 'Durum', value: 'APPROVED' }, { label: 'Araç', value: '-' }],
        selectedBadges: [{ label: 'Teklif', value: 'Açık' }],
      }),
    },
    {
      id: 'room-shifts-ready-assigned',
      role: 'ROOM',
      entityType: 'shift',
      path: '/room/shifts',
      message: 'Bu vardiya neden başlayamıyor?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: {
        ...SHIFT_CONTEXT,
        vehicle: { plate: '20 ABC 123' },
        driver: { fullName: 'Sürücü Demo' },
        stopCount: 5,
      },
      screenContext: ctx('/room/shifts', {
        label: 'Vardiyalar',
        selectedLabel: 'Vardiya #2 APPROVED 13.05.2026 08:00-18:00',
        selectedFields: [
          { label: 'Durum', value: 'APPROVED' },
          { label: 'Readiness', value: 'READY' },
          { label: 'Araç', value: '20 ABC 123' },
          { label: 'Sürücü', value: 'Sürücü Demo' },
          { label: 'Durak', value: '5' },
        ],
      }),
    },
    {
      id: 'room-agreements-purpose',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/agreements',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/room/agreements', { label: 'Sözleşmeler' }),
    },
    {
      id: 'room-agreements-route-refresh-offer',
      role: 'ROOM',
      entityType: 'shift',
      path: '/room/agreements',
      message: 'Bu sözleşmede rota değişikliği var mı?',
      expectedType: 'AGREEMENT_ROUTE_REFRESH',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: AGREEMENT_ROUTE_SHIFT_CONTEXT,
      screenContext: ctx('/room/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Rota güncelleme #77',
        selectedSummary: 'Talep #77 • Bekliyor',
        selectedFields: [
          { label: 'Eski rota', value: 'Var' },
          { label: 'Yeni rota', value: 'Var' },
          { label: 'Fark', value: 'Kişi / durak / km / süre' },
        ],
        selectedBadges: [{ label: 'Durum', value: 'Bekliyor' }],
      }),
    },
    {
      id: 'room-agreements-route-refresh-history',
      role: 'ROOM',
      entityType: 'shift',
      path: '/room/agreements',
      message: 'Bu rota uygulanmış mı, sadece teklif mi?',
      expectedType: 'AGREEMENT_ROUTE_REFRESH',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: AGREEMENT_ROUTE_SHIFT_ACCEPTED_CONTEXT,
      screenContext: ctx('/room/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Rota güncelleme #77',
        selectedSummary: 'Talep #77 • Uygulandı',
        selectedFields: [
          { label: 'Eski rota', value: 'Önceki' },
          { label: 'Yeni rota', value: 'Uygulanan' },
          { label: 'Durum', value: 'Uygulandı' },
        ],
        selectedBadges: [{ label: 'Tip', value: 'Geçmiş' }],
      }),
    },
    {
      id: 'room-agreements-dynamic-savings-preview',
      role: 'ROOM',
      entityType: 'shift',
      path: '/room/agreements',
      message: 'Bu değişiklikte tasarruf ne?',
      expectedType: 'DYNAMIC_SAVINGS_PREVIEW',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: AGREEMENT_ROUTE_SHIFT_CONTEXT,
      screenContext: ctx('/room/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Tasarruf önizlemesi #77',
        selectedSummary: 'Sadece önizleme • Bekliyor',
        selectedFields: [
          { label: 'Mevcut rota', value: 'Var' },
          { label: 'Yeni rota', value: 'Var' },
          { label: 'Kişi / durak / km / süre', value: 'Farklı' },
        ],
        selectedBadges: [{ label: 'Tasarruf', value: 'Önizleme' }],
      }),
    },
    {
      id: 'room-operation-health-first',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/operation-health',
      message: 'Önce neyi kontrol edeyim?',
      expectedType: 'FIRST_CONTROL',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/operation-health', {
        label: 'Operasyon Sağlığı',
        selectedLabel: 'Araç 20 ABC 123',
        selectedFields: [{ label: 'Canlılık', value: 'Zayıf' }],
      }),
    },
    {
      id: 'room-operation-health-summary',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/operation-health',
      message: 'Operasyon Sağlığı: sorun ne?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/operation-health', {
        label: 'Operasyon Sağlığı',
        selectedLabel: 'Canlılık özeti',
        selectedFields: [
          { label: 'Aktif sürücü', value: '0' },
          { label: 'Riskli cihaz', value: '1' },
          { label: 'GPS güncel değil / çevrim dışı', value: '1' },
          { label: 'Açık sorun', value: '2' },
        ],
      }),
    },
    {
      id: 'superadmin-ov-why',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/operation-verification',
      message: 'Bu neden kapalı?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin/operation-verification', {
        label: 'Operasyon Doğrulama',
        selectedLabel: 'Kayıt #91',
        selectedFields: [{ label: 'Durum', value: 'Eksik' }],
      }),
    },
    {
      id: 'superadmin-acceptance-purpose',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/acceptance',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/acceptance', { label: 'Field Acceptance Center' }),
    },
    {
      id: 'superadmin-trust-quality-status',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/trust-quality',
      message: 'Bu kayıt ne durumda?',
      expectedType: 'STATUS_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/trust-quality', {
        label: 'Güven ve Kalite',
        selectedLabel: 'Değerlendirme #551',
        selectedFields: [{ label: 'Skor', value: '78' }, { label: 'Risk', value: 'Orta' }],
      }),
    },
    {
      id: 'superadmin-system-status-band',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin',
      message: 'Bu sistem durumu ne demek?',
      expectedType: 'STATUS_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.7,
      screenContext: ctx('/superadmin', {
        label: 'Sistem durumu',
        selectedBadges: [
          { label: 'Kanıt', value: 'Aktif' },
          { label: 'Kalite', value: 'Taslak modda' },
          { label: 'Ödeme', value: 'Kapalı' },
        ],
      }),
    },
    {
      id: 'superadmin-commercial-core-readiness',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/commercial-core',
      message: 'Ödeme neden kapalı?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.7,
      screenContext: ctx('/superadmin/commercial-core', {
        label: 'Ticari akış özeti',
        selectedFields: [{ label: 'Ödeme', value: 'Kapalı' }, { label: 'Durum', value: 'Hazırlık' }],
        selectedBadges: [{ label: 'CSV', value: 'Taslak' }],
      }),
    },
    {
      id: 'superadmin-commercial-core-csv-preview',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/commercial-core',
      message: 'CSV taslağı ne işe yarıyor?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.7,
      screenContext: ctx('/superadmin/commercial-core', {
        label: 'Hakediş önizlemesi',
        selectedFields: [{ label: 'Önizleme', value: 'Taslak' }],
        selectedBadges: [{ label: 'CSV', value: 'Taslak' }],
      }),
    },
    {
      id: 'superadmin-quality-score-finite',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/trust-quality',
      message: 'Kalite puanı kesin mi?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/trust-quality', {
        label: 'Kalite akış özeti',
        selectedFields: [{ label: 'Skor', value: 'Taslak' }, { label: 'Kesin puan', value: 'Yok' }],
        selectedBadges: [{ label: 'Denetim', value: 'Hazır' }],
      }),
    },
    {
      id: 'superadmin-proof-purpose',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/trust-quality',
      message: 'Servis kanıtı ne işe yarar?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.7,
      screenContext: ctx('/superadmin/trust-quality', {
        label: 'Servis Kanıtı',
        selectedFields: [{ label: 'Sürücünün telefon GPS’i', value: 'Görüldü' }, { label: 'Operatör notu', value: 'Var' }],
      }),
    },
    {
      id: 'superadmin-selected-shift-start-diagnostic',
      role: 'SUPER_ADMIN',
      entityType: 'shift',
      path: '/superadmin/operations',
      message: 'Bu vardiya neden başlayamıyor?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      context: BLOCKED_SHIFT_CONTEXT,
      screenContext: ctx('/superadmin/operations', {
        label: 'Denetim Paneli',
        selectedLabel: 'Vardiya #4102',
        selectedFields: [{ label: 'Durum', value: 'APPROVED' }, { label: 'Araç', value: '-' }],
        selectedBadges: [{ label: 'Sözleşme', value: 'Eksik bağlantı' }],
      }),
    },
    {
      id: 'superadmin-selected-vehicle-map-diagnostic',
      role: 'SUPER_ADMIN',
      entityType: 'vehicle',
      path: '/superadmin/operations',
      message: 'Bu araç neden haritada görünmüyor?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.82,
      context: {
        type: 'vehicle',
        id: 77,
        plate: '20 DRV 777',
        activeDeviceCount: 0,
        driver: null,
      },
      screenContext: ctx('/superadmin/operations', {
        label: 'Denetim Paneli',
        selectedLabel: 'Araç 20 DRV 777',
        selectedFields: [{ label: 'Son GPS', value: 'Yok' }, { label: 'Kaynak', value: 'Harita' }],
        selectedBadges: [{ label: 'Durum', value: 'Görünmüyor' }],
      }),
    },
    {
      id: 'superadmin-selected-driver-gps-diagnostic',
      role: 'SUPER_ADMIN',
      entityType: 'vehicle',
      path: '/superadmin/operations',
      message: 'Sürücünün telefon GPS’i neden devrede?',
      expectedType: 'LOCATION_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.9,
      context: {
        type: 'vehicle',
        id: 78,
        plate: '20 DRV 778',
        activeDeviceCount: 1,
        driver: { fullName: 'Sürücü Demo' },
      },
      screenContext: ctx('/superadmin/operations', {
        label: 'Denetim Paneli',
        selectedLabel: 'Araç 20 DRV 778',
        selectedFields: [{ label: 'Kaynak', value: 'Sürücünün telefon GPS’i' }, { label: 'Durum', value: 'Aktif' }],
        selectedBadges: [{ label: 'Sinyal', value: 'Görünüyor' }],
      }),
    },
    {
      id: 'superadmin-selected-provider-better-diagnostic',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/trust-quality',
      message: 'Bu sağlayıcı neden daha iyi?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/trust-quality', {
        label: 'Güven ve Kalite',
        selectedLabel: 'Sağlayıcı A',
        selectedFields: [{ label: 'Skor', value: '78' }, { label: 'Risk', value: 'Orta' }],
        selectedBadges: [{ label: 'İnceleme', value: 'Hazır' }],
      }),
    },
    {
      id: 'superadmin-selected-contract-shift-today',
      role: 'SUPER_ADMIN',
      entityType: 'shift',
      path: '/superadmin/commercial-core',
      message: 'Sözleşmeden bugün vardiya üretildi mi?',
      expectedType: 'READINESS_CHECK',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      context: SHIFT_CONTEXT,
      screenContext: ctx('/superadmin/commercial-core', {
        label: 'Ticari Akış',
        selectedLabel: 'Sözleşme #901',
        selectedFields: [{ label: 'Bugün', value: 'Vardiya üretildi' }, { label: 'Sözleşme', value: 'Bağlı' }],
        selectedBadges: [{ label: 'Durum', value: 'Aktif' }],
      }),
    },
    {
      id: 'superadmin-selected-payment-missing',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/commercial-core',
      message: 'Bu hakediş neden eksik?',
      expectedType: 'PAYMENT_READINESS',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/commercial-core', {
        label: 'Hakediş önizlemesi',
        selectedLabel: 'Hakediş #12',
        selectedFields: [{ label: 'Durum', value: 'Eksik bilgi' }, { label: 'Ödeme hesabı', value: 'Eksik' }],
        selectedBadges: [{ label: 'Kontrol', value: 'Gerekli' }],
      }),
    },
    {
      id: 'room-agreements-contract-readiness',
      role: 'ROOM',
      entityType: 'shift',
      path: '/room/agreements',
      message: 'Sözleşmeden bugün vardiya üretildi mi?',
      expectedType: 'READINESS_CHECK',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: SHIFT_CONTEXT,
      screenContext: ctx('/room/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #901',
        selectedFields: [{ label: 'Durum', value: 'Bağlı' }, { label: 'Bugün', value: 'Vardiya üretildi' }],
        selectedBadges: [{ label: 'Sözleşme', value: 'Aktif' }],
      }),
    },
    {
      id: 'superadmin-commercial-core-readiness-live',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/commercial-core',
      message: 'Bu hakediş neden hazır değil?',
      expectedType: 'PAYMENT_READINESS',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin/commercial-core', {
        label: 'Ticari Akışım',
        selectedLabel: 'Hakediş #12',
        selectedFields: [
          { label: 'Ödeme Hesabı', value: 'Eksik' },
          { label: 'Komisyon', value: 'Kontrol edilmeli' },
          { label: 'Eksik Bilgi', value: 'Var' },
        ],
        selectedBadges: [{ label: 'Sözleşme', value: 'Aktif' }],
      }),
    },
    {
      id: 'superadmin-commercial-core-readiness-zero-missing',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/commercial-core',
      message: 'Bu hakediş neden hazır değil?',
      expectedType: 'PAYMENT_READINESS',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin/commercial-core', {
        label: 'Ticari Akış',
        selectedLabel: 'Hakediş #13',
        selectedFields: [
          { label: 'Eksik Bilgi', value: '0' },
          { label: 'Ödeme Hesabı', value: 'Var' },
          { label: 'Komisyon', value: 'Kontrol edilmeli' },
        ],
        selectedBadges: [{ label: 'Durum', value: 'Hazır değil' }],
      }),
    },
    {
      id: 'room-commercial-flow-readiness',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/commercial-flow',
      message: 'Bu hakediş neden hazır değil?',
      expectedType: 'PAYMENT_READINESS',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/commercial-flow', {
        label: 'Ticari Akışım',
        selectedLabel: 'Hakediş #12',
        selectedFields: [{ label: 'Durum', value: 'Eksik bilgi' }, { label: 'Ödeme hesabı', value: 'Eksik' }],
        selectedBadges: [{ label: 'Kontrol', value: 'Gerekli' }],
      }),
    },
    {
      id: 'room-commercial-flow-readiness-zero-missing',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/commercial-flow',
      message: 'Bu hakediş neden hazır değil?',
      expectedType: 'PAYMENT_READINESS',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/commercial-flow', {
        label: 'Ticari Akışım',
        selectedLabel: 'Hakediş #14',
        selectedFields: [
          { label: 'Eksik Bilgi', value: '0' },
          { label: 'Ödeme Hesabı', value: 'Var' },
          { label: 'Komisyon', value: 'Kontrol edilmeli' },
        ],
        selectedBadges: [{ label: 'Kontrol', value: 'Gerekli' }],
      }),
    },
    {
      id: 'company-agreements-payment-readiness',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/agreements',
      message: 'Bu sözleşmede ödeme başlatılabilir mi?',
      expectedType: 'PAYMENT_READINESS',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #901',
        selectedFields: [
          { label: 'Kalite', value: 'İnceleme bekliyor' },
          { label: 'Kanıt', value: 'Eksik değil ama kısmi' },
          { label: 'Hazırlık', value: 'Sadece önizleme' },
        ],
        selectedBadges: [{ label: 'Durum', value: 'Aktif' }],
      }),
    },
    {
      id: 'company-agreements-payment-missing',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/agreements',
      message: 'Kanıt eksikleri neler?',
      expectedType: 'PAYMENT_MISSING',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #902',
        selectedFields: [
          { label: 'Kanıt', value: 'Eksik' },
          { label: 'Kalite', value: 'Kontrol gerekli' },
          { label: 'Hazırlık', value: 'Sadece önizleme' },
        ],
        selectedBadges: [{ label: 'Durum', value: 'Hazır değil' }],
      }),
    },
    {
      id: 'room-agreements-quality-impact',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/agreements',
      message: 'Kalite hakedişi etkiliyor mu?',
      expectedType: 'PAYMENT_READINESS',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #903',
        selectedFields: [
          { label: 'Kalite', value: 'Riskli' },
          { label: 'Kanıt', value: 'Eksik bilgi yok' },
          { label: 'Hakediş', value: 'Önizleme' },
        ],
        selectedBadges: [{ label: 'Sadece önizleme', value: 'Ödeme başlatılmaz' }],
      }),
    },
    {
      id: 'room-agreements-proof-safety',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/agreements',
      message: 'Bu servis kanıt açısından güvenli mi?',
      expectedType: 'PAYMENT_READINESS',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #904',
        selectedFields: [
          { label: 'Kanıt', value: 'Kısmi' },
          { label: 'Kalite', value: 'İnceleme gerekli' },
          { label: 'Durum', value: 'Sadece önizleme' },
        ],
        selectedBadges: [{ label: 'Hazırlık', value: 'Ödeme başlatılmaz' }],
      }),
    },
    {
      id: 'company-agreements-sefer-score',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/agreements',
      message: 'Bu tedarikçinin SeferPuanı kaç?',
      expectedType: 'SEFER_SCORE_PREVIEW',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #905',
        selectedFields: [
          { label: 'SeferPuanı', value: '4.35 / 5' },
          { label: 'Kalite', value: 'İyi' },
          { label: 'Güven', value: 'Önizleme' },
        ],
        selectedBadges: [{ label: 'Sadece önizleme', value: 'Ödeme, ceza ve sıralama yok' }],
      }),
    },
    {
      id: 'room-agreements-sefer-quality-low',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/agreements',
      message: 'Kalite puanı neden düşük?',
      expectedType: 'SEFER_SCORE_PREVIEW',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #906',
        selectedFields: [
          { label: 'SeferPuanı', value: '3.42 / 5' },
          { label: 'Eksik Sinyaller', value: 'GPS, belge' },
          { label: 'Risk', value: 'Orta' },
        ],
        selectedBadges: [{ label: 'Sadece önizleme', value: 'Ödeme başlatılmaz' }],
      }),
    },
    {
      id: 'room-agreements-sefer-signals-missing',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/agreements',
      message: 'Eksik sinyaller neler?',
      expectedType: 'SEFER_SCORE_PREVIEW',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #907',
        selectedFields: [
          { label: 'SeferPuanı', value: '3.10 / 5' },
          { label: 'Eksik', value: 'Kanıt ve GPS' },
          { label: 'Güven', value: 'Düşük' },
        ],
        selectedBadges: [{ label: 'Sadece önizleme', value: 'Ceza / sıra yok' }],
      }),
    },
    {
      id: 'company-agreements-sefer-score-improve',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/agreements',
      message: 'SeferPuanı nasıl yükselir?',
      expectedType: 'SEFER_SCORE_PREVIEW',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #908',
        selectedFields: [
          { label: 'SeferPuanı', value: '3.80 / 5' },
          { label: 'Kalite', value: 'Standart' },
          { label: 'İşlem', value: 'Sadece önizleme' },
        ],
        selectedBadges: [{ label: 'Sadece önizleme', value: 'Ödeme ve teklif sıralaması yok' }],
      }),
    },
    {
      id: 'room-agreements-sefer-impact-boundary',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/agreements',
      message: 'Bu puan ödeme veya teklif sıralamasını etkiliyor mu?',
      expectedType: 'SEFER_SCORE_PREVIEW',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #909',
        selectedFields: [
          { label: 'SeferPuanı', value: '4.20 / 5' },
          { label: 'Etki', value: 'Sadece önizleme' },
          { label: 'Karar', value: 'Yetkili kullanıcıda' },
        ],
        selectedBadges: [{ label: 'Sadece önizleme', value: 'Ödeme, ceza ve sıralama başlatmaz' }],
      }),
    },
    {
      id: 'company-agreements-service-quality',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/agreements',
      message: 'Bu servis kaliteli mi?',
      expectedType: 'SEFER_SCORE_PREVIEW',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #910',
        selectedFields: [
          { label: 'SeferPuanı', value: '4.55 / 5' },
          { label: 'Kalite', value: 'İyi' },
          { label: 'Güven', value: 'Yüksek önizleme' },
        ],
        selectedBadges: [{ label: 'Sadece önizleme', value: 'Ödeme ve ceza yok' }],
      }),
    },
    {
      id: 'shared-notification-source',
      role: 'ROOM',
      entityType: 'screen',
      path: '/shared/notifications',
      message: 'Bu bildirim hangi olaydan geldi?',
      expectedType: 'STATUS_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/shared/notifications', {
        label: 'Bildirimler',
        selectedLabel: 'Bildirim #77',
        selectedFields: [{ label: 'Olay', value: 'Vardiya güncelleme' }, { label: 'Zaman', value: '2 dk önce' }],
      }),
    },
    {
      id: 'room-commercial-flow-contract-today',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/commercial-flow',
      message: 'Bu sözleşmeden bugün vardiya üretildi mi?',
      expectedType: 'CONTRACT_TO_SHIFT',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/commercial-flow', {
        label: 'Ticari Akışım',
        selectedLabel: 'Sözleşme #12',
        selectedFields: [
          { label: 'Sözleşme', value: 'Aktif' },
          { label: 'Bugün', value: 'Vardiya yok' },
          { label: 'Planlama', value: 'Bekliyor' },
        ],
      }),
    },
    {
      id: 'shared-feedback-status',
      role: 'ROOM',
      entityType: 'screen',
      path: '/shared/feedback',
      message: 'Bu kayıt ne durumda?',
      expectedType: 'STATUS_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/shared/feedback', {
        label: 'Geri Bildirim',
        selectedLabel: 'Gecikme bildirimi',
        selectedFields: [{ label: 'Durum', value: 'Açık' }, { label: 'Sorumlu Rol', value: 'Oda' }],
        selectedBadges: [{ label: 'Yıldız', value: '4' }],
      }),
    },
    {
      id: 'shared-feedback-owner',
      role: 'ROOM',
      entityType: 'screen',
      path: '/shared/feedback',
      message: 'Bu kayıt kimde?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/shared/feedback', {
        label: 'Geri Bildirim',
        selectedLabel: 'Gecikme bildirimi',
        selectedFields: [
          { label: 'Durum', value: 'Açık' },
          { label: 'Sorumlu rol', value: 'Belirsiz' },
          { label: 'Öncelik', value: 'Yüksek' },
        ],
      }),
    },
    {
      id: 'shared-kvkk-visibility',
      role: 'ROOM',
      entityType: 'screen',
      path: '/shared/kvkk',
      message: 'Bu bilgi neden görünmüyor?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/shared/kvkk', {
        label: 'KVKK',
        selectedLabel: 'Gizli alan',
        selectedFields: [{ label: 'Görünürlük', value: 'Kısıtlı' }, { label: 'Rol', value: 'Personel' }],
      }),
    },
    {
      id: 'superadmin-operations-role-help',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/operations',
      message: 'Bunu kim yapabilir?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin/operations', {
        label: 'Denetim Paneli',
        selectedLabel: 'Yetki özeti',
        selectedFields: [{ label: 'Rol', value: 'Sürücü' }, { label: 'Yetki', value: 'Kısıtlı' }],
      }),
    },
    {
      id: 'room-shifts-missing-data',
      role: 'ROOM',
      entityType: 'shift',
      path: '/room/shifts',
      message: 'Bu kayıtta ne eksik?',
      expectedType: 'MISSING_DATA_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: BLOCKED_SHIFT_CONTEXT,
      screenContext: ctx('/room/shifts', {
        label: 'Vardiyalar',
        selectedLabel: 'Vardiya #4102',
        selectedFields: [{ label: 'Durum', value: 'APPROVED' }, { label: 'Araç', value: '-' }, { label: 'Sürücü', value: '-' }],
        selectedBadges: [{ label: 'Teklif', value: 'Açık' }],
      }),
    },
    {
      id: 'superadmin-selected-next-action',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/trust-quality',
      message: 'Sıradaki doğru işlem ne?',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/trust-quality', {
        label: 'Kalite akış özeti',
        selectedLabel: 'Değerlendirme #551',
        selectedFields: [{ label: 'Skor', value: 'Taslak' }, { label: 'İnceleme', value: 'Bekliyor' }],
        selectedBadges: [{ label: 'Denetim', value: 'Hazır' }],
      }),
    },
    {
      id: 'superadmin-observability-next',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/observability',
      message: 'Şimdi ne yapayım?',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/observability', {
        label: 'Observability',
        selectedLabel: 'İstek Grubu #12',
        selectedFields: [{ label: 'Hata', value: 'Spike' }],
      }),
    },
    {
      id: 'superadmin-operations-start-blocked',
      role: 'SUPER_ADMIN',
      entityType: 'shift',
      path: '/superadmin/operations',
      message: 'Bu vardiya neden başlayamıyor?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: BLOCKED_SHIFT_CONTEXT,
      screenContext: ctx('/superadmin/operations', {
        label: 'Denetim Paneli',
        selectedLabel: 'Vardiya #4102',
        selectedFields: [
          { label: 'Durum', value: 'Bekliyor' },
          { label: 'Araç', value: 'Eksik' },
          { label: 'Sürücü', value: 'Eksik' },
        ],
      }),
    },
    {
      id: 'driver-today-purpose',
      role: 'DRIVER',
      entityType: 'screen',
      path: '/driver/today',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.6,
      screenContext: ctx('/driver/today', { label: 'Bugün' }),
    },
    {
      id: 'driver-today-next-step',
      role: 'DRIVER',
      entityType: 'screen',
      path: '/driver/today',
      message: 'Ne yapayım?',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      expectedActionLed: true,
      minConfidence: 0.72,
      screenContext: ctx('/driver/today', {
        label: 'Bugün',
        selectedLabel: 'Bugünkü görev',
        selectedFields: [
          { label: 'Görev', value: 'Atandı' },
          { label: 'Rota', value: 'Hazır' },
          { label: 'Bildirim', value: 'Açık' },
        ],
      }),
    },
    {
      id: 'driver-today-live-start-blocked',
      role: 'DRIVER',
      entityType: 'shift',
      path: '/driver/today',
      message: 'Görev neden başlamıyor?',
      expectedType: 'SHIFT_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.78,
      context: {
        type: 'shift',
        id: 3,
        vehicleId: 34,
        driverId: 9,
        shiftStatus: 'APPROVED',
        routeReady: true,
        stopCount: 6,
        nextStop: 'Pickup 6',
        gpsStatus: 'Telefon GPS’i beklemede',
        operationProofStatus: 'Eksik',
      },
      screenContext: ctx('/driver/today', {
        label: 'Bugünkü görev',
        selectedLabel: 'Vardiya #3',
        selectedFields: [
          { label: 'Durum', value: 'Kabul Edildi' },
          { label: 'Araç', value: '34ABC123' },
          { label: 'Rota', value: 'Hazır' },
          { label: 'Sıradaki durak', value: 'Pickup 6' },
        ],
        selectedBadges: [{ label: 'GPS', value: 'Telefon GPS’i beklemede' }],
      }),
    },
    {
      id: 'driver-map-location',
      role: 'DRIVER',
      entityType: 'vehicle',
      path: '/driver/map',
      message: 'Konum neden görünmüyor?',
      expectedType: 'LOCATION_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      context: {
        type: 'vehicle',
        id: 77,
        plate: '20 DRV 777',
        activeDeviceCount: 0,
        driver: null,
      },
      screenContext: ctx('/driver/map', {
        label: 'Harita',
        selectedLabel: '20 DRV 777',
        selectedFields: [{ label: 'Son paket', value: 'Yok' }],
      }),
    },
    {
      id: 'driver-map-selected-live-visibility',
      role: 'DRIVER',
      entityType: 'vehicle',
      path: '/driver/map',
      message: 'Bu araç neden haritada görünmüyor?',
      expectedType: 'LOCATION_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.82,
      context: {
        type: 'vehicle',
        id: 78,
        plate: '34ABC123',
        activeDeviceCount: 1,
        driver: { fullName: 'Sürücü Demo' },
      },
      screenContext: ctx('/driver/map', {
        label: 'Harita',
        selectedLabel: '34ABC123',
        selectedSummary: 'Vardiya #3 • GPS Zayıf / güncel değil • Son GPS 47s',
        selectedFields: [
          { label: 'Son GPS', value: '47s' },
          { label: 'GPS durumu', value: 'Zayıf / güncel değil' },
          { label: 'Sıradaki durak', value: 'Pickup 6' },
          { label: 'Toplam durak', value: '6' },
          { label: 'ETA', value: '619dk' },
        ],
        selectedBadges: [
          { label: 'Araç GPS’i', value: 'Zayıf / güncel değil' },
          { label: 'Sürücünün telefon GPS’i', value: 'Bekleniyor' },
        ],
      }),
    },
    {
      id: 'personel-live-purpose',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/live',
      message: 'Bu rolde ne yapabilirim?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.82,
      screenContext: ctx('/personel/live', { label: 'Canlı Takip' }),
    },
    {
      id: 'personel-live-service-location',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/live',
      message: 'Servisim nerede?',
      expectedType: 'LOCATION_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.82,
      screenContext: ctx('/personel/live', {
        label: 'Canlı Takip',
        selectedLabel: 'Servisim',
        selectedFields: [
          { label: 'Durum', value: 'Canlı' },
          { label: 'Bildirim', value: 'Açık' },
        ],
      }),
    },
    {
      id: 'personel-live-service-visibility',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/live',
      message: 'Servis neden görünmüyor?',
      expectedType: 'LOCATION_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.82,
      screenContext: ctx('/personel/live', {
        label: 'Canlı Takip',
        selectedLabel: 'Bugünkü servis',
        selectedSummary: '34ABC123 • GPS güncel değil • ETA 12 dk',
        selectedFields: [
          { label: 'Araç', value: '34ABC123' },
          { label: 'Son GPS', value: '2 dk' },
          { label: 'ETA', value: '12 dk' },
          { label: 'Sıradaki durak', value: 'Personel durağı' },
        ],
        selectedBadges: [
          { label: 'Araç GPS’i', value: 'GPS güncel değil' },
          { label: 'Sürücünün telefon GPS’i', value: 'Bekleniyor' },
        ],
      }),
    },
    {
      id: 'personel-live-request-entry',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/live',
      message: 'Bugün binmeyeceğim talebi nasıl oluşturulur?',
      expectedType: 'BOARDING_CHANGE_REQUEST_ENTRY',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/personel/live', {
        label: 'Canlı Takip',
        selectedLabel: 'Biniş değişikliği talebi',
        selectedFields: [
          { label: 'Talep tipi', value: 'Bugün binmeyeceğim' },
          { label: 'Karar sahibi', value: 'Sürücüde bekliyor' },
        ],
      }),
    },
    {
      id: 'personel-live-request-location',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/live',
      message: 'Konumumu al nasıl kullanılır?',
      expectedType: 'BOARDING_CHANGE_REQUEST_ENTRY',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/personel/live', {
        label: 'Canlı Takip',
        selectedLabel: 'Konum seçimi',
        selectedFields: [
          { label: 'Talep tipi', value: 'Farklı konumdan alınmak istiyorum' },
          { label: 'Konum yolu', value: 'Konumumu al' },
        ],
      }),
    },
    {
      id: 'personel-live-request-owner',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/live',
      message: 'Talebim kimde bekliyor?',
      expectedType: 'BOARDING_CHANGE_REQUEST_ENTRY',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/personel/live', {
        label: 'Canlı Takip',
        selectedLabel: 'Talep durumu',
        selectedFields: [
          { label: 'Durum', value: 'Açık / İncelemede' },
          { label: 'Karar sahibi', value: 'Sürücü' },
        ],
      }),
    },
    {
      id: 'parent-live-next',
      role: 'PARENT',
      entityType: 'screen',
      path: '/parent/live',
      message: 'Şimdi ne yapayım?',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.6,
      screenContext: ctx('/parent/live', { label: 'Canlı Takip' }),
    },
    {
      id: 'parent-live-service-location',
      role: 'PARENT',
      entityType: 'screen',
      path: '/parent/live',
      message: 'Öğrencimin servisi nerede?',
      expectedType: 'LOCATION_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.82,
      screenContext: ctx('/parent/live', {
        label: 'Canlı Takip',
        selectedLabel: 'Öğrencimin servisi',
        selectedFields: [
          { label: 'Durum', value: 'Canlı' },
          { label: 'Bildirim', value: 'Açık' },
          { label: 'Görünürlük', value: 'Sınırlı' },
        ],
      }),
    },
    {
      id: 'parent-live-service-visibility',
      role: 'PARENT',
      entityType: 'screen',
      path: '/parent/live',
      message: 'Çocuğumun servisi neden görünmüyor?',
      expectedType: 'LOCATION_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.82,
      screenContext: ctx('/parent/live', {
        label: 'Öğrencimin servisi',
        selectedLabel: 'Öğrenci servisi',
        selectedSummary: '34ABC123 • Canlı • ETA 8 dk',
        selectedFields: [
          { label: 'Araç', value: '34ABC123' },
          { label: 'Son GPS', value: '30 sn' },
          { label: 'ETA', value: '8 dk' },
          { label: 'Sıradaki durak', value: 'Okul' },
        ],
        selectedBadges: [
          { label: 'Araç GPS’i', value: 'Canlı' },
          { label: 'Sürücünün telefon GPS’i', value: 'Açık' },
        ],
      }),
    },
    {
      id: 'parent-live-request-entry',
      role: 'PARENT',
      entityType: 'screen',
      path: '/parent/live',
      message: 'Çocuğum başka duraktan binecek.',
      expectedType: 'BOARDING_CHANGE_REQUEST_ENTRY',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/parent/live', {
        label: 'Canlı Takip',
        selectedLabel: 'Biniş değişikliği talebi',
        selectedFields: [
          { label: 'Talep tipi', value: 'Başka durak' },
          { label: 'Karar sahibi', value: 'Hizmet alan taraf' },
        ],
      }),
    },
    {
      id: 'parent-live-request-location',
      role: 'PARENT',
      entityType: 'screen',
      path: '/parent/live',
      message: 'Çocuğum şu konumdan alınsın.',
      expectedType: 'BOARDING_CHANGE_REQUEST_ENTRY',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/parent/live', {
        label: 'Canlı Takip',
        selectedLabel: 'Konum seçimi',
        selectedFields: [
          { label: 'Talep tipi', value: 'Çocuğum şu konumdan alınsın' },
          { label: 'Konum yolu', value: 'Büyük haritada konum seç' },
        ],
      }),
    },
    {
      id: 'parent-live-request-owner',
      role: 'PARENT',
      entityType: 'screen',
      path: '/parent/live',
      message: 'Talebim kimde bekliyor?',
      expectedType: 'BOARDING_CHANGE_REQUEST_ENTRY',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/parent/live', {
        label: 'Canlı Takip',
        selectedLabel: 'Talep durumu',
        selectedFields: [
          { label: 'Durum', value: 'Onay bekliyor' },
          { label: 'Karar sahibi', value: 'Hizmet alan taraf' },
        ],
      }),
    },
    {
      id: 'company-commercial-flow-next',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/commercial-flow',
      message: 'Buradan sonra hangi ekrana geçmeliyim?',
      expectedType: 'NEXT_SCREEN',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/company/commercial-flow', {
        label: 'Ticari Akışım',
        selectedLabel: 'Talep #88',
        selectedFields: [{ label: 'Durum', value: 'Onay bekliyor' }],
      }),
    },
    {
      id: 'school-georeview-status',
      role: 'SCHOOL',
      entityType: 'screen',
      path: '/school/georeview',
      message: 'Bu seçili kayıt ne durumda?',
      expectedType: 'STATUS_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.68,
      screenContext: ctx('/school/georeview', {
        label: 'Öğrenci Konum Seçici',
        selectedLabel: 'Öğrenci #31',
        selectedFields: [{ label: 'Durum', value: 'Adres doğrulanmadı' }],
      }),
    },
    {
      id: 'organization-commercial-purpose',
      role: 'ORGANIZATION',
      entityType: 'screen',
      path: '/organization/commercial-flow',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/organization/commercial-flow', { label: 'Ticari Akışım' }),
    },
    {
      id: 'room-operation-health-blocked',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/operation-health',
      message: 'Neden sorunlu görünüyor?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.68,
      screenContext: ctx('/room/operation-health', {
        label: 'Operasyon Sağlığı',
        selectedLabel: 'Araç 20 ABC 123',
        selectedFields: [{ label: 'Canlılık', value: 'Yok' }, { label: 'Son paket', value: '15 dk önce' }],
      }),
    },
    {
      id: 'superadmin-users-role-help',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/users',
      message: 'Bu rolde burada neyi yönetebilirim?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.68,
      screenContext: ctx('/superadmin/users', { label: 'Kullanıcılar' }),
    },
    {
      id: 'driver-route-first-control',
      role: 'DRIVER',
      entityType: 'screen',
      path: '/driver/route',
      message: 'İlk neyi kontrol etmeliyim?',
      expectedType: 'FIRST_CONTROL',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.68,
      screenContext: ctx('/driver/route', { label: 'Rota', selectedLabel: 'Bugünkü rota' }),
    },
    {
      id: 'driver-route-start-blocked',
      role: 'DRIVER',
      entityType: 'screen',
      path: '/driver/route',
      message: 'Rota neden görünmüyor?',
      expectedType: 'SHIFT_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.78,
      context: {
        type: 'shift',
        id: 3,
        vehicleId: 34,
        driverId: 9,
        shiftStatus: 'APPROVED',
        routeReady: true,
        stopCount: 6,
        nextStop: 'Pickup 6',
        gpsStatus: 'Telefon GPS’i beklemede',
        operationProofStatus: 'Eksik',
      },
      screenContext: ctx('/driver/route', {
        label: 'Rota',
        selectedLabel: 'Vardiya #3',
        selectedSummary: '34ABC123 • Son GPS 47s • Pickup 6',
        selectedFields: [
          { label: 'Durum', value: 'Kabul Edildi' },
          { label: 'Araç', value: '34ABC123' },
          { label: 'Son GPS', value: '47s' },
          { label: 'Sıradaki durak', value: 'Pickup 6' },
        ],
        selectedBadges: [
          { label: 'Araç GPS’i', value: 'Zayıf / güncel değil' },
          { label: 'Sürücünün telefon GPS’i', value: 'Bekleniyor' },
        ],
      }),
    },
    {
      id: 'personel-my-next',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/my',
      message: 'Şimdi ne yapmalıyım?',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.6,
      screenContext: ctx('/personel/my', { label: 'Servisim' }),
    },
    {
      id: 'personel-my-service-visibility',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/my',
      message: 'Servis neden görünmüyor?',
      expectedType: 'LOCATION_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.82,
      screenContext: ctx('/personel/my', {
        label: 'Servisim',
        selectedLabel: 'Bugünkü servis',
        selectedSummary: '34ABC123 • GPS güncel değil • ETA 12 dk',
        selectedFields: [
          { label: 'Araç', value: '34ABC123' },
          { label: 'Son GPS', value: '2 dk' },
          { label: 'ETA', value: '12 dk' },
          { label: 'Sıradaki durak', value: 'Personel durağı' },
        ],
        selectedBadges: [
          { label: 'Araç GPS’i', value: 'GPS güncel değil' },
          { label: 'Sürücünün telefon GPS’i', value: 'Bekleniyor' },
        ],
      }),
    },
    {
      id: 'parent-live-purpose-2',
      role: 'PARENT',
      entityType: 'screen',
      path: '/parent/live',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.6,
      screenContext: ctx('/parent/live', { label: 'Canlı Takip' }),
    },
    {
      id: 'room-operation-health-why-risk',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/operation-health',
      message: 'Neden riskli görünüyor?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/operation-health', {
        label: 'Operasyon Sağlığı',
        selectedLabel: 'Araç 20 ABC 123',
        selectedFields: [{ label: 'Canlılık', value: 'Zayıf' }, { label: 'Gecikme', value: 'Var' }],
      }),
    },
    {
      id: 'personel-live-next-step',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/live',
      message: 'Şimdi ne yapmalıyım?',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      expectedActionLed: true,
      screenContext: ctx('/personel/live', { label: 'Canlı Takip', selectedLabel: 'Servisim' }),
    },
    {
      id: 'superadmin-users-role-help-route',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/users',
      message: 'Bu rolde burada neyi yönetebilirim?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin/users', { label: 'Kullanıcılar' }),
    },
      {
        id: 'company-agreements-purpose',
        role: 'COMPANY',
        entityType: 'screen',
        path: '/company/agreements',
        message: 'Bu ekran ne için var?',
        expectedType: 'SCREEN_PURPOSE',
        expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/company/agreements', { label: 'Sözleşmeler' }),
    },
    {
      id: 'company-agreements-route-refresh-offer',
      role: 'COMPANY',
      entityType: 'shift',
      path: '/company/agreements',
      message: 'Room’a rota güncelleme talebi gitti mi?',
      expectedType: 'AGREEMENT_ROUTE_REFRESH',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: AGREEMENT_ROUTE_SHIFT_CONTEXT,
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler (Company)',
        selectedLabel: 'Rota güncelleme #77',
        selectedSummary: 'Talep #77 • Bekliyor',
        selectedFields: [
          { label: 'Şirket', value: 'Teklif gönderildi' },
          { label: 'Room', value: 'Karşı teklif bekliyor' },
          { label: 'Fark', value: 'Kişi / durak / km / süre' },
        ],
        selectedBadges: [{ label: 'Durum', value: 'Bekliyor' }],
      }),
    },
    {
      id: 'company-agreements-route-refresh-diff',
      role: 'COMPANY',
      entityType: 'shift',
      path: '/company/agreements',
      message: 'Eski rota ile yeni rota farkı ne?',
      expectedType: 'AGREEMENT_ROUTE_REFRESH',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: {
        ...AGREEMENT_ROUTE_SHIFT_CONTEXT,
        routeRefreshState: 'COUNTERED',
      },
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler (Company)',
        selectedLabel: 'Rota güncelleme #77',
        selectedSummary: 'Talep #77 • Karşı teklif',
        selectedFields: [
          { label: 'Eski rota', value: 'Önceki' },
          { label: 'Yeni rota', value: 'Önerilen' },
          { label: 'Fark', value: 'Kişi / durak / km / süre' },
        ],
        selectedBadges: [{ label: 'Durum', value: 'Karşı teklif' }],
      }),
    },
    {
      id: 'company-agreements-dynamic-savings-preview',
      role: 'COMPANY',
      entityType: 'shift',
      path: '/company/agreements',
      message: 'Yaklaşık maliyet etkisi nedir?',
      expectedType: 'DYNAMIC_SAVINGS_PREVIEW',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      context: AGREEMENT_ROUTE_SHIFT_CONTEXT,
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler (Company)',
        selectedLabel: 'Tasarruf önizlemesi #77',
        selectedSummary: 'Sadece önizleme • Bekliyor',
        selectedFields: [
          { label: 'Mevcut km', value: '120' },
          { label: 'Yeni km', value: '105' },
          { label: 'Süre farkı', value: '-18 dk' },
        ],
        selectedBadges: [{ label: 'Tasarruf', value: 'Tahmini' }],
      }),
    },
    {
      id: 'company-agreements-contract-today',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/agreements',
      message: 'Bu sözleşmeden bugün vardiya üretildi mi?',
      expectedType: 'CONTRACT_TO_SHIFT',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #901',
        selectedFields: [{ label: 'Durum', value: 'Bağlı' }, { label: 'Bugün', value: 'Vardiya üretildi' }],
        selectedBadges: [{ label: 'Sözleşme', value: 'Aktif' }],
      }),
    },
    {
      id: 'company-agreements-contract-bridge',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/agreements',
      message: 'Bu sözleşmeden bugün vardiya üretildi mi?',
      expectedType: 'CONTRACT_TO_SHIFT',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.76,
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler (Company)',
        selectedLabel: 'Sözleşme #1',
        selectedSummary: 'Kabul Edildi • Oda #1',
        selectedFields: [
          { label: 'Kaynak vardiya', value: '#4' },
          { label: 'Üretilen vardiya', value: '3' },
          { label: 'Son üretilen vardiya', value: '#7' },
          { label: 'Son durum', value: 'APPROVED' },
          { label: 'Son zaman', value: '20.05.2026 07:00 - 20.05.2026 09:00' },
          { label: 'Personel', value: '6' },
          { label: 'Durak', value: '6' },
          { label: 'Tarih', value: '2026-05-16 — 2026-05-20' },
        ],
        selectedBadges: [
          { label: 'Üretim', value: 'Var' },
          { label: 'Köprü', value: 'Açık' },
        ],
        structuredFacts: {
          sourceShiftId: 4,
          generatedShiftCount: 3,
          lastGeneratedShiftId: 7,
          lastGeneratedShiftStatus: 'APPROVED',
          lastGeneratedShiftStart: '20.05.2026 07:00',
          lastGeneratedShiftEnd: '20.05.2026 09:00',
          personelCount: 6,
          stopCount: 6,
          todayGeneratedShift: true,
        },
      }),
    },
    {
      id: 'company-agreements-readiness-check',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/agreements',
      message: 'Bu sözleşme bugün üretime hazır mı?',
      expectedType: 'READINESS_CHECK',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #901',
        selectedFields: [{ label: 'Durum', value: 'Bağlı' }, { label: 'Hazırlık', value: 'Bekliyor' }],
        selectedBadges: [{ label: 'Sözleşme', value: 'Aktif' }],
      }),
    },
    {
      id: 'company-shifts-role-help',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/shifts',
      message: 'Bu rolde ne yapabilirim?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/company/shifts', { label: 'Vardiyalar' }),
    },
    {
      id: 'superadmin-rooms-role-help',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/rooms',
      message: 'Bu rolde burada neyi yönetebilirim?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin/rooms', { label: 'Rooms' }),
    },
    {
      id: 'superadmin-observability-screen-purpose',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/observability',
      message: 'Bu ekran ne için var?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/observability', { label: 'Canlı İzleme' }),
    },
    {
      id: 'superadmin-main-what-to-do',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin',
      message: 'Bu ekranda ne yapmalıyım?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin', {
        label: 'Sistem durumu',
        selectedBadges: [
          { label: 'Kanıt', value: 'Aktif' },
          { label: 'Kalite', value: 'Taslak modda' },
        ],
      }),
    },
    {
      id: 'room-operation-missing',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/operation-health',
      message: 'Burada ne eksik?',
      expectedType: 'MISSING_DATA_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/operation-health', {
        label: 'Operasyon Sağlığı',
        selectedLabel: 'Araç 20 ABC 123',
        selectedFields: [{ label: 'Canlılık', value: 'Yok' }, { label: 'Son paket', value: '15 dk önce' }],
      }),
    },
    {
      id: 'company-commercial-stuck',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/commercial-flow',
      message: 'Bu kayıt neden ilerlemiyor?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/company/commercial-flow', {
        label: 'Ticari Akışım',
        selectedLabel: 'Talep #88',
        selectedFields: [{ label: 'Durum', value: 'Kontrol gerekli' }],
      }),
    },
    {
      id: 'superadmin-next-screen-general',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin',
      message: 'Hangi ekrana gitmeliyim?',
      expectedType: 'NEXT_SCREEN',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin', {
        label: 'Sistem durumu',
        selectedBadges: [{ label: 'Ödeme', value: 'Kapalı' }],
      }),
    },
    {
      id: 'superadmin-user-capability',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/users',
      message: 'Bu kullanıcı ne yapabilir?',
      expectedType: 'ROLE_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/superadmin/users', { label: 'Kullanıcılar' }),
    },
    {
      id: 'driver-map-gps',
      role: 'DRIVER',
      entityType: 'vehicle',
      path: '/driver/map',
      message: 'Konum neden görünmüyor?',
      expectedType: 'LOCATION_HELP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      context: {
        type: 'vehicle',
        id: 77,
        plate: '20 DRV 777',
        activeDeviceCount: 0,
        driver: null,
      },
      screenContext: ctx('/driver/map', {
        label: 'Harita',
        selectedLabel: '20 DRV 777',
        selectedFields: [{ label: 'Son paket', value: 'Yok' }],
      }),
    },
    {
      id: 'organization-shift-contract',
      role: 'ORGANIZATION',
      entityType: 'screen',
      path: '/organization/shifts',
      message: 'Sözleşme ile vardiya ilişkisi ne?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/organization/shifts', {
        label: 'Vardiyalar',
        selectedLabel: 'Sözleşme #901',
        selectedFields: [{ label: 'Durum', value: 'Bağlı' }],
        selectedBadges: [{ label: 'Sözleşme', value: 'Aktif' }],
      }),
    },
    {
      id: 'company-agreement-source-lineage',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/agreements',
      message: 'Bu sözleşme hangi vardiyadan geldi?',
      expectedType: 'MARKETPLACE_FREE_TO_OPERATE_PREVIEW',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/company/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #911',
        selectedFields: [{ label: 'Kaynak zinciri', value: 'Sadece önizleme' }],
      }),
    },
    {
      id: 'room-agreement-source-lineage',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/agreements',
      message: 'Bu sözleşme SeferPakt kaynaklı mı?',
      expectedType: 'MARKETPLACE_FREE_TO_OPERATE_PREVIEW',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/room/agreements', {
        label: 'Sözleşmeler',
        selectedLabel: 'Sözleşme #912',
        selectedFields: [{ label: 'Kaynak durumu', value: 'Sadece önizleme' }],
      }),
    },
    {
      id: 'organization-plan-source-lineage',
      role: 'ORGANIZATION',
      entityType: 'screen',
      path: '/organization/shifts',
      message: 'Organizasyon planı tek başına kaynak kanıtı sayılır mı?',
      expectedType: 'PAYMENT_READINESS',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/organization/shifts', {
        label: 'Vardiyalar',
        selectedLabel: 'Sözleşme #913',
        selectedFields: [{ label: 'Kaynak zinciri', value: 'Sadece önizleme' }],
      }),
    },
    {
      id: 'company-payment-readiness',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/commercial-flow',
      message: 'Hakediş tarafında ne kontrol etmeliyim?',
      expectedType: 'READINESS_CHECK',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/company/commercial-flow', {
        label: 'Hakediş önizlemesi',
        selectedLabel: 'Hakediş #12',
        selectedFields: [{ label: 'Durum', value: 'Eksik bilgi' }, { label: 'Ödeme hesabı', value: 'Eksik' }],
        selectedBadges: [{ label: 'Kontrol', value: 'Gerekli' }],
      }),
    },
    {
      id: 'superadmin-quality-finite',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/trust-quality',
      message: 'Kalite puanı kesin karar mı?',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.68,
      screenContext: ctx('/superadmin/trust-quality', {
        label: 'Kalite akış özeti',
        selectedFields: [{ label: 'Skor', value: 'Taslak' }, { label: 'Kesin puan', value: 'Yok' }],
        selectedBadges: [{ label: 'Denetim', value: 'Hazır' }],
      }),
    },
    {
      id: 'school-kvkk-boundary',
      role: 'SCHOOL',
      entityType: 'screen',
      path: '/school/parents',
      message: 'KVKK yüzünden bunu göremiyor olabilir miyim?',
      expectedType: 'WHY_BLOCKED',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.72,
      screenContext: ctx('/school/parents', {
        label: 'Veli Erişimi',
        selectedLabel: 'Öğrenci #31',
        selectedFields: [{ label: 'Görünürlük', value: 'Kısıtlı' }],
      }),
    },
    {
      id: 'personel-mobile-route',
      role: 'PERSONEL',
      entityType: 'screen',
      path: '/personel/live',
      message: 'Mobilde bu iş nereden yapılır?',
      expectedType: 'NEXT_SCREEN',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/personel/live', { label: 'Canlı Takip' }),
    },
    {
      id: 'parent-next-step-general',
      role: 'PARENT',
      entityType: 'screen',
      path: '/parent/live',
      message: 'Sıradaki doğru işlem ne?',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.72,
      screenContext: ctx('/parent/live', { label: 'Canlı Takip', selectedLabel: 'Öğrencimin servisi' }),
    },
    {
      id: 'cop03a-feedback-purpose',
      role: 'ROOM',
      entityType: 'screen',
      path: '/shared/feedback',
      message: 'burası ne işe yarar',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/shared/feedback', {
        label: 'Geri Bildirim',
        selectedLabel: 'Geri Bildirim #120',
        selectedFields: [
          { label: 'Durum', value: 'Açık' },
          { label: 'Kategori', value: 'Servis' },
          { label: 'Sorumlu Rol', value: 'Oda' },
        ],
        selectedBadges: [{ label: 'Yıldız', value: '4' }],
      }),
      expectedFocus: 'Geri Bildirim ekranı anlatımı',
      forbidden: ['harita', 'araç seç', 'canlı takip', 'vardiya/araç ekranına geç', 'bak..', 'Sonra: Sonra', 'Önce Önce', 'haritada doğru aracı'],
    },
    {
      id: 'cop03a-drivers-purpose-short',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/drivers',
      message: 'bu ne',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/room/drivers', {
        label: 'Sürücüler',
        selectedFields: [
          { label: 'Durum', value: 'Aktif' },
          { label: 'Görev', value: 'Bağlı' },
        ],
      }),
      expectedFocus: 'Sürücüler ekranı anlatımı',
      forbidden: ['Bunu anlayamadım', 'harita', 'canlı takip', 'Önce Önce'],
    },
    {
      id: 'cop03a-drivers-purpose-plain',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/drivers',
      message: 'burası ne',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/room/drivers', {
        label: 'Sürücüler',
        selectedFields: [
          { label: 'Durum', value: 'Pasif' },
          { label: 'Görev', value: 'Bekliyor' },
        ],
      }),
      expectedFocus: 'Sürücüler ekranı anlatımı',
      forbidden: ['Bunu anlayamadım', 'harita', 'canlı takip', 'Önce Önce'],
    },
    {
      id: 'cop03a-kvkk-purpose',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/shared/kvkk',
      message: 'burası ne',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/shared/kvkk', {
        label: 'KVKK',
        selectedFields: [{ label: 'Görünürlük', value: 'Kısıtlı' }, { label: 'Maskeleme', value: 'Aktif' }],
      }),
      expectedFocus: 'KVKK görünürlük ve sınır anlatımı',
      forbidden: ['raw', 'payload', 'token', 'hash', 'debug', 'kontrol et..', 'Önce Önce'],
    },
    {
      id: 'cop03a-notifications-purpose',
      role: 'ROOM',
      entityType: 'screen',
      path: '/shared/notifications',
      message: 'bu ekran ne',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/shared/notifications', {
        label: 'Bildirimler',
        selectedFields: [{ label: 'Durum', value: 'Okunmamış' }, { label: 'Öncelik', value: 'Kritik' }],
      }),
      expectedFocus: 'Bildirimler ekranı anlatımı',
      forbidden: ['harita', 'araç seç', 'canlı takip', 'oku..', 'Önce Önce'],
    },
    {
      id: 'cop03a-company-operations-purpose',
      role: 'COMPANY',
      entityType: 'screen',
      path: '/company/operations',
      message: 'burada ne yapacağım',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/company/operations', {
        label: 'Operasyon Paneli',
        selectedFields: [{ label: 'Açık', value: '2' }, { label: 'Riskli', value: '1' }],
      }),
      expectedFocus: 'Operasyon paneli anlatımı',
      forbidden: ['harita', 'araç seç', 'canlı takip', 'Önce Önce'],
    },
    {
      id: 'cop03a-school-operations-missing',
      role: 'SCHOOL',
      entityType: 'screen',
      path: '/school/operations',
      message: 'burada ne eksik',
      expectedType: 'MISSING_DATA_HELP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/school/operations', {
        label: 'Okul Operasyon Paneli',
        selectedFields: [{ label: 'Bugün', value: '1 kişi bekliyor' }, { label: 'Durum', value: 'Riskli' }],
      }),
      expectedFocus: 'Okul operasyon eksik kontrolü',
      forbidden: ['harita', 'araç seç', 'canlı takip', 'Önce Önce'],
    },
    {
      id: 'cop03a-organization-operations-purpose',
      role: 'ORGANIZATION',
      entityType: 'screen',
      path: '/organization/operations',
      message: 'burada ne yapacağım',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/organization/operations', {
        label: 'Organizasyon Operasyon Paneli',
        selectedFields: [{ label: 'Açık', value: '3' }, { label: 'Otomatik', value: '1' }],
      }),
      expectedFocus: 'Organizasyon operasyon paneli anlatımı',
      forbidden: ['harita', 'araç seç', 'canlı takip', 'Önce Önce'],
    },
    {
      id: 'cop03a-driver-change-pin-purpose',
      role: 'DRIVER',
      entityType: 'screen',
      path: '/driver/change-pin',
      message: 'bu ne',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'OPEN_ROUTE',
      minConfidence: 0.6,
      screenContext: ctx('/driver/change-pin', {
        label: 'PIN Değiştir',
        selectedFields: [{ label: 'Eski PIN', value: 'Girildi' }, { label: 'Yeni PIN', value: 'Bekliyor' }],
      }),
      expectedFocus: 'PIN değiştirme anlatımı',
      forbidden: ['harita', 'araç seç', 'canlı takip', 'driver GPS', 'agreement', 'Önce Önce'],
    },
    {
      id: 'cop03a-superadmin-commercial-core-purpose',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/commercial-core',
      message: 'burası ne işe yarar',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/commercial-core', {
        label: 'Ticari Akış',
        selectedFields: [{ label: 'Hazırlık', value: 'Var' }, { label: 'Ödeme', value: 'Kapalı' }],
      }),
      expectedFocus: 'Hakediş hazırlığı ve sadece önizleme ödeme anlatımı',
      forbidden: ['harita', 'Önce Önce', 'settlement kontrolü'],
    },
    {
      id: 'cop03a-pilot-launch-gate-next',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/pilot-launch-gate',
      message: 'ne yapayım',
      expectedType: 'NEXT_STEP',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/pilot-launch-gate', {
        label: 'Sahaya Çıkış Kontrolü',
        selectedFields: [{ label: 'Checklist', value: 'Açık' }, { label: 'Readiness', value: 'Bekliyor' }],
      }),
      expectedFocus: 'Sahaya çıkış kontrolü',
      forbidden: ['harita', 'araç seç', 'canlı takip', 'Önce Önce'],
    },
    {
      id: 'cop03a-ssot-alignment-purpose',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/ssot-alignment',
      message: 'bu ekran ne',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/ssot-alignment', {
        label: 'Sistem Standartları',
        selectedFields: [{ label: 'SSOT', value: 'Uyumlu' }, { label: 'Milestone', value: 'Green' }],
      }),
      expectedFocus: 'SSOT ve doğrulama hizası',
      forbidden: ['harita', 'araç seç', 'canlı takip', 'Önce Önce'],
    },
    {
      id: 'cop03a-room-commercial-flow-purpose',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/commercial-flow',
      message: 'burası ne',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/room/commercial-flow', {
        label: 'Ticari Akışım',
        selectedFields: [{ label: 'Teklif', value: 'Hazır' }, { label: 'Sözleşme', value: 'Aktif' }],
      }),
      expectedFocus: 'Oda ticari akış anlatımı',
      forbidden: ['ödeme başlat', 'Sonra: Sonra', 'Önce Önce', 'settlement kontrolü'],
    },
    {
      id: 'cop03a-room-reports-purpose',
      role: 'ROOM',
      entityType: 'screen',
      path: '/room/reports',
      message: 'bu ekran ne',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/room/reports', {
        label: 'Raporlar',
        selectedFields: [{ label: 'Özet', value: 'Var' }, { label: 'Filtre', value: 'Aktif' }],
      }),
      expectedFocus: 'Raporlar ekranı anlatımı',
      forbidden: ['harita', 'araç seç', 'canlı takip', 'Önce Önce'],
    },
    {
      id: 'cop03a-superadmin-logexport-purpose',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/logexport',
      message: 'burası ne işe yarar',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/logexport', {
        label: 'Log Dışa Aktarımı',
        selectedFields: [{ label: 'Audit', value: 'Hazır' }, { label: 'Export', value: 'Bekliyor' }],
      }),
      expectedFocus: 'Log dışa aktarımı ve KVKK sınırı',
      forbidden: ['raw', 'payload', 'token', 'hash', 'debug', 'Önce Önce'],
    },
    {
      id: 'cop03a-superadmin-natural-copilot-purpose',
      role: 'SUPER_ADMIN',
      entityType: 'screen',
      path: '/superadmin/natural-copilot',
      message: 'bu ekran ne',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.6,
      screenContext: ctx('/superadmin/natural-copilot', {
        label: 'Doğal Copilot',
        selectedFields: [{ label: 'Rehber', value: 'Aktif' }, { label: 'Planlanan', value: 'Var' }],
      }),
      expectedFocus: 'Doğal Copilot rehber yüzeyi',
      forbidden: ['harita', 'araç seç', 'canlı takip', 'Önce Önce'],
    },
    {
      id: 'cop03a-unknown-screen-purpose',
      role: 'ROOM',
      entityType: 'screen',
      path: '/mystery/unknown-purpose',
      message: 'bu ne',
      expectedType: 'SCREEN_PURPOSE',
      expectedFirstActionKind: 'ASK',
      minConfidence: 0.5,
      screenContext: ctx('/mystery/unknown-purpose', {
        label: 'Bu ekran',
        selectedFields: [{ label: 'Durum', value: 'Bilinmiyor' }],
      }),
      expectedFocus: 'Güvenli bilinmeyen ekran fallbacki',
      forbidden: ['harita', 'araç seç', 'canlı takip', 'Bunu anlayamadım', 'Önce Önce'],
    },
  ].concat(buildGuidedTaskEngineGoldenCases());
}

export const COP02B_CONTEXTUAL_FOLLOW_UPS = [
  'peki şimdi ne yapayım',
  'neden',
  'bu kayıt niye ilerlemiyor',
  'hangi ekrana gideyim',
  'bunu kim yapabilir',
  'burada eksik ne',
  'bu uyarı önemli mi',
  'önce neyi kontrol edeyim',
  'bu işlem bende görünmüyor neden',
  'aynı kayıt için devam et',
  'neye basayım',
  'kim onaylayacak',
  'bu yüzden mi başlamıyor',
  'tamam bunu nasıl düzeltirim',
  'bende çıkmıyor',
  'burda takıldı',
  'sorun kimde',
  'bu hakediş neden hazır değil',
  'bu araç niye yok',
  'bu sözleşmeden vardiya çıkmış mı',
];
