import { pickTerms } from "./glossary.js";
import { button, inferGuideKeyFromScreen, screen } from "./screenCatalog.shared.js";

const ROOM = [
  screen(1101, "/room/map", "Canlı Takip", {
    menuPurpose: "Araçların ve işlerin canlı durumunu hızlıca görmek için kullanılır.",
    forWhom: "Oda operasyonunu yöneten kullanıcı içindir.",
    firstStep: "Önce haritada doğru aracı veya işi seç.",
    nextStep: "Sorun varsa ilgili vardiya veya araç ekranına geç.",
    doNotDo: "Sadece haritaya bakıp karar verme; gerekirse vardiya detayını da kontrol et.",
    stepByStep: ["Haritadaki aracı seç.", "Durum ve son konumu oku.", "Gerekirse vardiya veya araç ekranına geç."],
    commonMistakes: ["Eski konumu canlı sanmak.", "Yanlış aracı seçmek."],
    doneChecklist: ["Doğru araç seçildi.", "Canlı durum okundu."],
    buttonGuides: [
      button("Aracı aç", "Seçili aracı detaylı incelemeye götürür.", "Belirli bir araç hakkında daha fazla bilgi gerekince kullan.", "Araç detayına veya ilgili akışa geçilir."),
      button("Yenile", "Canlı bilgiyi tekrar yükler.", "Bilginin eski kaldığını düşünüyorsan kullan.", "Ekrandaki durumlar yeniden okunur."),
      button("Durakları göster", "Durak pinlerini haritada açıp kapatır.", "Durak yoğunluğunu görmek veya gizlemek istediğinde kullan.", "Durak markerları görünür veya gizlenir."),
      button("Sonraki Durağa Navigasyon", "Seçili aracın sıradaki durağı için dış navigasyonu açar.", "Sıradaki durak net ve araç seçiliyse kullan.", "Telefon veya dış navigasyon sıradaki durağa göre açılır."),
      button("Tam Rotayı Dış Navigasyonda Aç", "Tüm durak sırasını dış navigasyonda açar.", "Mini harita yerine tam yol tarifi gerektiğinde kullan.", "Harici navigasyon tam rota ile açılır."),
      button("Tümünü Göster", "Araç ve durakların tamamını haritaya sığdırır.", "Harita bir bölgeye fazla yaklaşmışsa kullan.", "Kamera tüm aktif rota alanına oturur."),
    ],
    screenMenus: [
      { label: "Vardiyalar", path: "/room/shifts", purpose: "Canlı durumun hangi işten geldiğini görmek için açılır." },
      { label: "Araçlar", path: "/room/vehicles", purpose: "Araç ve cihaz bilgisini kontrol etmek için açılır." },
    ],
    simpleTerms: pickTerms(["telefonGps", "cihazGps", "konumKaynagi"]),
    dataRules: ["Son GPS çok eskiyse bu ekran tek başına canlı karar için yeterli değildir.", "Üst karttaki durum, sıradaki durak ve ETA birlikte okunmalıdır; tek rozetle karar verilmez.", "Haritadaki mavi aktif parça sıradaki hedefi, yeşil parça geçilen kısmı gösterir.", "Araç seçili değilse üst özet değişmez; önce doğru araç satırını seç."],
    firstControls: ["Önce doğru aracı veya seçili işi seç.", "Son GPS zamanı yeni mi kontrol et.", "Shift durumu, sıradaki durak ve ETA birlikte tutarlı mı bak."],
    stuckChecks: ["Araç seçili değilse üst kart değişmez.", "Son GPS eskiyse canlı karar verme.", "Haritada araç var ama üst kart boşsa doğru vardiya bağını kontrol et."],
    workflowStages: [
      { key: 'ROOM_MAP_PICK', title: 'Önce doğru kaydı seç', action: 'Listeden veya haritadan doğru aracı seç.', doneWhen: 'Üst kartta plaka ve vardiya bilgisi görünür.', ifBlocked: 'Seçim değişmiyorsa filtreleri ve veri yenilemeyi kontrol et.' },
      { key: 'ROOM_MAP_READ', title: 'Canlı bilgiyi oku', action: 'GPS, son GPS, sıradaki durak ve ETA alanlarını birlikte oku.', doneWhen: 'Canlı durum hakkında tek cümlelik özet çıkarabiliyorsun.', ifBlocked: 'Son GPS çok eskiyse bu ekran tek başına karar için yetmez.' },
      { key: 'ROOM_MAP_DECIDE', title: 'Sonraki ekranı seç', action: 'Sorun iş tarafındaysa Vardiyalar, araç/sürücü tarafındaysa Araçlar ekranına geç.', doneWhen: 'Takip edeceğin doğru ekran netleşir.', ifBlocked: 'Sorun tipi belirsizse önce selected shift bilgisini netleştir.' },
    ],
    nextScreens: [
      { label: 'Vardiyalar', path: '/room/shifts', reason: 'Sorunun hangi işe bağlı olduğunu görmek için.' },
      { label: 'Araçlar', path: '/room/vehicles', reason: 'Araç, sürücü veya cihaz GPS tarafını kontrol etmek için.' },
    ],
    chatQuestions: ['Önce neyi kontrol edeyim?', 'Kontrol listesi ver', 'Sık hata ne?', 'Hangi ekrana geçeyim?', 'Bu satırı nasıl okurum?'],
    fieldGuides: [
      { label: 'Plaka', meaning: 'Seçili aracın kimliğidir.', howToRead: 'Önce doğru aracı seçtiğini buradan doğrula.' },
      { label: 'Shift durumu', meaning: 'Seçili işin operasyon durumudur.', howToRead: 'APPROVED veya ACTIVE bilgisini diğer alanlarla birlikte oku.', risk: 'Tek başına atama tamam anlamına gelmez.' },
      { label: 'GPS', meaning: 'Araçtan canlı konum akıp akmadığını özetler.', howToRead: 'ONLINE/OFFLINE bilgisini son GPS ile birlikte değerlendir.' },
      { label: 'Son GPS', meaning: 'En son konumun ne kadar önce geldiğini gösterir.', risk: 'Çok eskiyse sahadaki canlı durumu tek başına temsil etmez.' },
      { label: 'Sıradaki durak', meaning: 'Araç için bir sonraki hedef noktadır.' },
      { label: 'ETA', meaning: 'Sıradaki durağa tahmini kalan süredir.' },
      { label: 'Toplam Durak Sayısı', meaning: 'Bu rotadaki toplam durak adedidir.' },
      { label: 'Tamamlanan', meaning: 'Geçilen durak adedidir.' },
      { label: 'Kalan', meaning: 'Henüz gidilmeyen durak adedidir.' },
    ],
    badgeGuides: [
      { label: 'APPROVED', meaning: 'İş onaylıdır ama operasyon detayını ayrıca okumak gerekir.', actionHint: 'Araç ve sürücü alanlarını ayrıca kontrol et.' },
      { label: 'ACTIVE', meaning: 'İş sahada aktif ilerliyor.' },
      { label: 'OFFLINE', meaning: 'Son anda canlı GPS akışı görünmüyor olabilir.', actionHint: 'Son GPS ve telefon tarafını kontrol et.' },
      { label: 'ONLINE', meaning: 'Canlı GPS akışı görülüyor.' },
    ],
    rowReadHint: 'Önce plaka ve shift durumunu oku. Sonra GPS, son GPS ve ETA alanlarını birlikte değerlendir. En son toplam, tamamlanan ve kalan ile rotanın neresinde olduğunu anla.',
  }),
  screen(1102, "/room/offers", "Teklifler", {
    menuPurpose: "Gelen teklifleri görmek, karşılaştırmak ve karar vermek için kullanılır.",
    forWhom: "Teklif ve pazarlık akışını yöneten oda kullanıcısı içindir.",
    firstStep: "Önce hangi teklifin hangi işe ait olduğunu kontrol et.",
    nextStep: "Karar vermeden önce araç, sürücü ve saat bilgisini karşılaştır.",
    doNotDo: "Teklifin bağlı olduğu işi anlamadan onay verme.",
    stepByStep: ["Teklifi seç.", "İşe bağlı bilgileri kontrol et.", "Uygunsa onay veya red kararı ver."],
    commonMistakes: ["Yanlış işe ait teklifi onaylamak.", "Araç ve sürücüyü kontrol etmeden karar vermek."],
    doneChecklist: ["Doğru teklif seçildi.", "Karar öncesi eksikler kontrol edildi."],
    buttonGuides: [
      button("Teklifi aç", "Teklif satırını detaylı inceler.", "Satırdaki bilgi yetmiyorsa kullan.", "Teklifin bağlı olduğu iş ve detaylar görünür."),
      button("Onay ver", "Seçili teklifi kabul eder.", "Araç, sürücü ve saat uygunsa kullan.", "Teklifin durumu güncellenir.", "Eksik bilgi varsa kapalı kalabilir.", "Yanlış teklifi onaylamak diğer kararları etkileyebilir."),
      button("Reddet", "Seçili teklifi kapatır.", "Teklif uygun değilse kullan.", "Teklif red durumuna geçer."),
    ],
    screenMenus: [
      { label: "Vardiyalar", path: "/room/shifts", purpose: "Teklifin bağlı olduğu işi ayrıntılı görmek için açılır." },
      { label: "Sözleşmeler", path: "/room/agreements", purpose: "İş sözleşmeye bağlıysa önce burayı kontrol et." },
    ],
    simpleTerms: pickTerms(["teklif", "sozlesme", "atama"]),
    dataRules: ["Market, kabul ve operasyon aynı aşama değildir; aynı kaydın farklı evreleridir.", "Bu ekran yeni plan kurmaz; yeni iş için Planlama Merkezi açılır.", "Kabul edildi görünmesi operasyonun sahada başladığı anlamına gelmez; vardiya ve atama ayrıca okunur.", "Operasyon başladıysa kalite ve sonuç takibi Hizmet Değerlendirme tarafına kayar."],
  }),
  screen(1103, "/room/shifts", "Vardiyalar", {
    menuPurpose: "İşleri, atamaları ve operasyon akışını yönetmek için kullanılır.",
    forWhom: "Odanın günlük işi yöneten kullanıcısı içindir.",
    firstStep: "Önce doğru vardiya kaydını seç.",
    nextStep: "Araç, sürücü ve durak durumunu kontrol et.",
    doNotDo: "Yanlış vardiyayı açıp işlem yapma.",
    stepByStep: ["Vardiyayı seç.", "Durumunu oku.", "Eksik alan varsa ilgili ekrana git."],
    commonMistakes: ["Yanlış vardiya üzerinde işlem yapmak.", "Durak bilgisi eksikken hazır sanmak."],
    doneChecklist: ["Doğru vardiya seçildi.", "Eksik alanlar görüldü."],
    buttonGuides: [
      button("Yeni oluştur", "Yeni iş kaydı açar.", "Yeni bir iş başlatılacaksa kullan.", "Boş bir kayıt akışı açılır."),
      button("Önizle", "Seçili işin özetini gösterir.", "Karar vermeden önce hızlı özet görmek istersen kullan.", "Kısa bilgi açılır."),
      button("Süre uzat", "Seçili işin süresini uzatma akışını açar.", "İş planı uzayacaksa kullan.", "Uzatma akışı açılır."),
    ],
    screenMenus: [
      { label: "Teklifler", path: "/room/offers", purpose: "Teklife bağlı kararları görmek için açılır." },
      { label: "Araçlar", path: "/room/vehicles", purpose: "Araç ve cihaz bilgisi için açılır." },
      { label: "Sürücüler", path: "/room/drivers", purpose: "Sürücü bağlama veya sürücü kontrolü için açılır." },
    ],
    simpleTerms: pickTerms(["atama", "teklif", "sozlesme"]),
    firstControls: ["Doğru vardiya satırını seç.", "Durum, araç, sürücü ve durak eksiği var mı bak.", "Teklif veya sözleşme ilişkisini karıştırma."],
    stuckChecks: ["Onaylı ama atanmamış görünüyorsa araç/sürücü bağını kontrol et.", "Teklif bekliyorsa bu ekranı yeni plan kurma yeri gibi kullanma.", "Preview gördün diye atama tamam sanma."],
    workflowStages: [
      { key: 'ROOM_SHIFT_PICK', title: 'Doğru vardiyayı aç', action: 'Liste, bekleyen veya market tarafında doğru vardiyayı seç.', doneWhen: 'Seçili vardiya özeti net.', ifBlocked: 'Yanlış sekmede olabilirsin; takip/market ayrımını kontrol et.' },
      { key: 'ROOM_SHIFT_READ', title: 'Eksikleri ayır', action: 'Araç, sürücü, durak ve teklif bilgisini ayrı ayrı oku.', doneWhen: 'Eksik alanı tek cümlede söyleyebilirsin.', ifBlocked: 'Hepsi aynı anda eksik görünüyorsa veri yenile.' },
      { key: 'ROOM_SHIFT_ACT', title: 'Doğru alt ekrana git', action: 'Teklif kararı gerekiyorsa Teklifler, atama eksiği varsa Araçlar/Sürücüler tarafına geç.', doneWhen: 'Bir sonraki işlem ekranı netleşir.', ifBlocked: 'Sözleşmeli işte normal teklif akışını arama.' },
    ],
    nextScreens: [
      { label: 'Teklifler', path: '/room/offers', reason: 'Teklife bağlı karar vermek için.' },
      { label: 'Araçlar', path: '/room/vehicles', reason: 'Araç veya cihaz tarafını kontrol etmek için.' },
      { label: 'Sürücüler', path: '/room/drivers', reason: 'Sürücü bağı veya sürücü uygunluğunu kontrol etmek için.' },
    ],
    chatQuestions: ['Bu kayıt ne durumda?', 'Önce neyi kontrol edeyim?', 'Hangi ekrana geçeyim?', 'Sık hata ne?'],
  }),
  screen(1104, "/room/vehicles", "Araçlar", {
    menuPurpose: "Araç kayıtlarını, sürücü bağını ve cihaz GPS'i bilgisini yönetmek için kullanılır.",
    forWhom: "Araç ve konum kaynağı tarafını yöneten oda kullanıcısı içindir.",
    firstStep: "Önce doğru aracı seç.",
    nextStep: "Gerekirse sürücü bağı veya cihaz GPS'i bilgisine bak.",
    doNotDo: "Yanlış aracı seçip cihaz işlemi yapma.",
    stepByStep: ["Aracı seç.", "Durum ve bağları kontrol et.", "Gerekirse cihaz veya sürücü tarafına geç."],
    commonMistakes: ["Yanlış araca cihaz eklemek.", "Telefon GPS'i ile cihaz GPS'ini karıştırmak."],
    doneChecklist: ["Doğru araç seçildi.", "Konum kaynağı tarafı kontrol edildi."],
    buttonGuides: [
      button("Yeni araç", "Yeni araç kaydı açar.", "Araç sisteme ilk kez eklenecekse kullan.", "Yeni araç formu açılır."),
      button("Bağla", "Araç ile sürücüyü eşleştirme akışını açar.", "Telefon GPS'i tarafı için sürücü bağı gerekliyse kullan.", "Sürücü bağlama alanı açılır."),
      button("Telematics", "Cihaz GPS'i sekmesini açar.", "Araçtaki mevcut cihazı görmek veya eklemek için kullan.", "Cihaz GPS'i alanı görünür."),
    ],
    screenMenus: [
      { label: "Sürücüler", path: "/room/drivers", purpose: "Telefon GPS'i için bağlı sürücüyü kontrol et." },
      { label: "Vardiyalar", path: "/room/shifts", purpose: "Araç etkisini iş tarafında görmek için açılır." },
    ],
    simpleTerms: pickTerms(["telefonGps", "cihazGps", "konumKaynagi"]),
  }),
  screen(1105, "/room/drivers", "Sürücüler", {
    menuPurpose: "Sürücü kayıtlarını ve araç bağını yönetmek için kullanılır.",
    forWhom: "Sürücü planını yöneten oda kullanıcısı içindir.",
    firstStep: "Önce doğru sürücüyü seç.",
    nextStep: "Gerekirse araç bağını veya aktif işi kontrol et.",
    doNotDo: "Müsait olmayan sürücüyü bağlama.",
    stepByStep: ["Sürücüyü seç.", "Bağlı araç veya iş durumuna bak.", "Gerekirse araç ekranına geç."],
    commonMistakes: ["Yanlış sürücüyü bağlamak.", "Mevcut bağı görmeden yeni bağ yapmak."],
    doneChecklist: ["Doğru sürücü seçildi.", "Bağ durumu kontrol edildi."],
    buttonGuides: [
      button("Yeni sürücü", "Yeni sürücü kaydı açar.", "Yeni bir sürücü sisteme eklenecekse kullan.", "Yeni kayıt formu açılır."),
      button("Araca bağla", "Seçili sürücüyü bir araca bağlar.", "Telefon GPS'i akışı için sürücü ataması gerekiyorsa kullan.", "Bağlama akışı açılır."),
    ],
    screenMenus: [
      { label: "Araçlar", path: "/room/vehicles", purpose: "Sürücünün bağlı olacağı aracı seçmek için açılır." },
      { label: "Vardiyalar", path: "/room/shifts", purpose: "Sürücü etkisini iş ekranında görmek için açılır." },
    ],
    simpleTerms: pickTerms(["telefonGps", "atama"]),
  }),
  screen(1106, "/room/agreements", "Sözleşmeler", {
    menuPurpose: "Sözleşmeye bağlı işleri görmek ve yönetmek için kullanılır.",
    forWhom: "Sözleşmeli iş akışını takip eden oda kullanıcısı içindir.",
    firstStep: "Önce doğru sözleşmeyi seç.",
    nextStep: "İşe etkisini görmek için ilgili vardiyaya geç.",
    doNotDo: "Sözleşmeyi görmeden işe karar verme.",
    stepByStep: ["Sözleşmeyi seç.", "Durumunu ve kapsamını oku.", "Gerekirse vardiya veya teklif ekranına geç."],
    commonMistakes: ["Sözleşmeli işi normal teklif gibi düşünmek."],
    doneChecklist: ["Doğru sözleşme açıldı.", "İşe etkisi görüldü."],
    buttonGuides: [
      button("Onayla", "Seçili sözleşmeyi onaylar.", "Şartlar doğruysa kullan.", "Sözleşme durumu güncellenir."),
      button("İptal et", "Seçili sözleşmeyi pasif hale getirir.", "Sözleşme artık kullanılmayacaksa kullan.", "Durum iptal tarafına geçer.", "Koşullar uygun değilse kapalı kalabilir.", "Canlı işi etkileyebilir; önce bağlı işi kontrol et."),
      button("Uzat", "Sözleşme süresini uzatma akışını açar.", "Aynı iş devam edecekse kullan.", "Uzatma alanı açılır."),
    ],
    screenMenus: [
      { label: "Vardiyalar", path: "/room/shifts", purpose: "Sözleşmenin bağlı olduğu işi görmek için açılır." },
      { label: "Teklifler", path: "/room/offers", purpose: "Sözleşme dışı teklif akışını ayırmak için açılır." },
    ],
    simpleTerms: pickTerms(["sozlesme", "teklif"]),
  }),
  screen(1107, "/room/copilot", "Copilot", {
    menuPurpose: "Sorun yaşadığında rehber almak ve ilgili ekrana hızlı gitmek için kullanılır.",
    forWhom: "Ek yardım isteyen oda kullanıcısı içindir.",
    firstStep: "Önce yapmak istediğin işi seç.",
    nextStep: "Gerekirse bu ekran ne için var veya buton rehberini aç.",
    doNotDo: "İlgili kaydı seçmeden rastgele yorum bekleme.",
    stepByStep: ["İş veya ekran türünü seç.", "Rehberi çalıştır.", "Gerekirse hızlı geçişle ilgili ekrana git."],
    commonMistakes: ["Yanlış kayıt türünü seçmek."],
    doneChecklist: ["Doğru rehber seçildi.", "İlgili ekrana yönlendirme görüldü."],
    buttonGuides: [
      button("Rehberi aç", "Seçilen iş için sade rehber üretir.", "Ne yapacağını bilmiyorsan kullan.", "Adım adım yardım gelir."),
      button("Analiz et", "Gelişmiş copilot analizini çalıştırır.", "Daha derin teknik özet gerektiğinde kullan.", "Gelişmiş sonuç görünür."),
    ],
    screenMenus: [
      { label: "Sözleşmeler", path: "/room/agreements", purpose: "Sözleşme sorularında önce burayı aç." },
      { label: "Araçlar", path: "/room/vehicles", purpose: "Araç ve konum kaynağı sorularında buraya geç." },
    ],
    simpleTerms: pickTerms(["sozlesme", "telefonGps", "cihazGps"]),
  }),
  screen(1108, "/room/hub", "Hub", {
    menuPurpose: "Personelin toplandığı veya bırakıldığı ana noktayı görmek ve yönetmek için kullanılır.",
    forWhom: "Oda operasyonunu yöneten kullanıcı içindir.",
    firstStep: "Önce bu hub'ın hangi iş veya rota için kullanıldığını kontrol et.",
    nextStep: "Gerekirse vardiya veya teklif ekranına geç.",
    doNotDo: "Hub noktasını görmeden yön bilgisini kesin sanma.",
    stepByStep: ["Hub bilgisini oku.", "Konum doğru mu kontrol et.", "Gerekirse bağlı iş ekranına geç."],
    commonMistakes: ["Hub ile durakları karıştırmak.", "Inbound ve outbound yönünü karıştırmak."],
    doneChecklist: ["Hub anlamı netleşti.", "Bağlı iş veya yön kontrol edildi."],
    buttonGuides: [
      button("Hub'ı aç", "Seçili hub bilgisini detaylı görmek için kullanılır.", "Konumu veya bağlı işi görmek istediğinde kullan.", "Hub bilgisi detaylı görünür."),
      button("Haritada göster", "Hub noktasını haritada gösterir.", "Konumun doğru yerde olup olmadığını kontrol edeceğinde kullan.", "Hub haritada açılır."),
    ],
    screenMenus: [
      { label: "Vardiyalar", path: "/room/shifts", purpose: "Hub'ın bağlı olduğu işi görmek için açılır." },
      { label: "Teklifler", path: "/room/offers", purpose: "Hub'a bağlı teklif kararını görmek için açılır." },
    ],
    simpleTerms: pickTerms(["hub", "inbound", "outbound"]),
  }),
  screen(1109, "/room/checkin", "Check-in", {
    menuPurpose: "Biniş, iniş veya doğrulama kayıtlarını görmek için kullanılır.",
    forWhom: "Check-in tarafını takip eden oda kullanıcısı içindir.",
    firstStep: "Önce hangi kayıt veya iş için check-in baktığını seç.",
    nextStep: "Gerekirse vardiya ekranına dön.",
    doNotDo: "Check-in kaydı var diye işin tümü tamam sanma.",
    stepByStep: ["Kayıdı seç.", "Check-in olayını oku.", "Gerekirse bağlı işe dön."],
    commonMistakes: ["Check-in ile yoklamayı karıştırmak."],
    doneChecklist: ["Doğru check-in kaydı görüldü."],
    buttonGuides: [button("Kaydı aç", "Seçili check-in olayını açar.", "Detayı görmek istediğinde kullan.", "Kayıt detayı açılır.")],
    screenMenus: [{ label: "Vardiyalar", path: "/room/shifts", purpose: "Check-in kaydının bağlı olduğu işi görmek için açılır." }],
    simpleTerms: pickTerms(["checkin"]),
  }),
  screen(1114, "/room/operation-health", "Operasyon Sağlığı", {
    menuPurpose: "Room içindeki sürücü, cihaz ve canlılık risklerini toplu görmek için kullanılır.",
    forWhom: "Operasyon sağlığını izleyen oda kullanıcısı içindir.",
    firstStep: "Önce özet kartlarda riskli alanı belirle.",
    nextStep: "Sonra sorunlu sürücü veya açık sorun satırına in.",
    doNotDo: "Sadece tek rozet görüp tüm operasyonu sağlıklı sanma.",
    stepByStep: ["Özet kartları oku.", "Sorunlu sürücü veya açık sorun satırını seç.", "Gerekirse Harita, Sürücüler veya Copilot ekranına geç."],
    commonMistakes: ["Sadece canlılık rozetine bakıp izin veya oturum sorununu atlamak.", "Açık sorunları kapatmadan saha kararını net sanmak."],
    doneChecklist: ["Risk alanı netleşti.", "İlgili ekran veya rehber açıldı."],
    buttonGuides: [
      button("Rehberde aç", "Sorunlu sürücü veya açık sorun için ne yapılacağını Copilot'ta açar.", "Neden risk gördüğünü veya hangi ekrana geçeceğini netleştirmek istediğinde kullan.", "Copilot ilgili bağlamla açılır."),
    ],
    screenMenus: [
      { label: "Canlı Takip", path: "/room/map", purpose: "Canlılık veya son konum sorununu haritada görmek için açılır." },
      { label: "Sürücüler", path: "/room/drivers", purpose: "Oturum, izin veya bağ durumu için açılır." },
      { label: "Copilot", path: "/room/copilot", purpose: "Sorunun nedenini ve sonraki adımı sade dille almak için açılır." },
    ],
    simpleTerms: pickTerms(["telefonGps", "cihazGps", "oturumYenileme"]),
    dataRules: ["Açık sorun sayısı sıfır değilse ekran yalnız bilgilendirme değil aksiyon ekranıdır.", "Stale/offline sayısı ile riskli cihaz sayısı birlikte okunmalıdır."],
    firstControls: ["Önce en riskli kartı belirle.", "Sonra ilk sorunlu sürücü veya açık soruna in."],
    stuckChecks: ["Sorun görünmüyorsa önce Yenile değil kaynak ekrandaki canlı veri akışını kontrol et.", "Canlılık sorunu varsa Harita ekranı ile birlikte oku."],
    nextScreens: [
      { label: "Canlı Takip", path: "/room/map", why: "GPS ve son konum akışını doğrulamak için" },
      { label: "Sürücüler", path: "/room/drivers", why: "İzin, oturum ve araç bağı için" },
    ],
  }),
  screen(1111, "/shared/notifications", "Bildirimler", {
    menuPurpose: "Kullanıcılara giden uyarı ve haberleri görmek için kullanılır.",
    forWhom: "Bildirim takibi yapan kullanıcı içindir.",
    firstStep: "Önce hangi bildirimin hangi olaydan geldiğini oku.",
    nextStep: "Gerekirse ilgili iş veya kayıt ekranına geç.",
    doNotDo: "Bildirimi işlem kaydı ile aynı sanma.",
    stepByStep: ["Bildirimi seç.", "Ne anlattığını oku.", "Gerekirse ilgili yere git."],
    commonMistakes: ["Bildirimi log kaydı ile karıştırmak."],
    doneChecklist: ["Bildirim anlamı netleşti."],
    buttonGuides: [button("İlgili yere git", "Bildirimin bağlı olduğu ekrana götürür.", "Sorunun kaynağına gitmek istediğinde kullan.", "İlgili ekran açılır.")],
    screenMenus: [{ label: "Loglar", path: "/shared/logs", purpose: "Sistem kaydını karşılaştırmak için açılır." }],
    simpleTerms: pickTerms(["bildirim", "islemKaydi"]),
  }),
  screen(1112, "/shared/logs", "Loglar", {
    menuPurpose: "Sistemde ne olduğunun kayıt altına alınmış halini görmek için kullanılır.",
    forWhom: "İşlem kaydını kontrol eden kullanıcı içindir.",
    firstStep: "Önce hangi olay kaydını aradığını seç.",
    nextStep: "Gerekirse bildirime veya ilgili işe dön.",
    doNotDo: "Log kaydını kullanıcı bildirimi sanma.",
    stepByStep: ["Kayıdı filtrele.", "Olayı oku.", "Gerekirse bağlı ekrana git."],
    commonMistakes: ["Log ile bildirim farkını karıştırmak."],
    doneChecklist: ["İşlem kaydı anlamı netleşti."],
    buttonGuides: [button("Filtre uygula", "Kayıtları daraltır.", "Belirli olayı aradığında kullan.", "Liste daralır.")],
    screenMenus: [{ label: "Bildirimler", path: "/shared/notifications", purpose: "Kullanıcıya giden uyarıyı görmek için açılır." }],
    simpleTerms: pickTerms(["islemKaydi", "bildirim"]),
  }),
];

const COMPANY = [
  screen(2101, "/company", "Planlama Merkezi", {
    menuPurpose: "Yeni işi kurmak için önce bu ekrana gelirsin. Burada konumu kontrol eder, plan akışını başlatır, kişileri ve durakları hazırlayıp çözümden sonra teklifi gönderirsin.",
    forWhom: "Şirket, okul veya organizasyon tarafında yeni iş kuran kullanıcı içindir.",
    firstStep: "Önce konum sorunu var mı bak. NEEDS_REVIEW varsa önce Konum İncele ekranını aç.",
    nextStep: "Plan kurulduktan sonra teklif ve operasyon takibi için Vardiyalar ekranına geç.",
    doNotDo: "Konumları düzeltmeden veya adımları atlayıp doğrudan teklif göndermeye çalışma.",
    stepByStep: ["Konumları kontrol et; sorun varsa Konum İncele'de düzelt.", "Rehberi Başlat düğmesiyle plan akışını aç.", "Plan paketi, tarih ve günleri seç.", "Kişi ve durak tarafını kontrol et; gerekiyorsa düzenle.", "Matris/Çöz çalıştır ve teklifi gönder.", "Son takibi Vardiyalar ekranında yap."],
    commonMistakes: ["Konum sorunu varken plan kurmaya çalışmak.", "Planlama Merkezi ile Vardiyalar ekranının görevini karıştırmak.", "Teklif gönderdikten sonra takibi bu ekranda aramak."],
    doneChecklist: ["Konum tarafı kontrol edildi.", "Plan akışı başlatıldı.", "Teklif veya plan çıktısı üretildi.", "Takip için doğru ekrana geçildi."],
    buttonGuides: [
      button("Rehberi Başlat", "Planlama akışını adım adım açar.", "Yeni iş kuracaksan kullan.", "Şirket konumu → plan paketi → kişi/durak → çözüm akışı açılır."),
      button("Konum İncele", "Konum problemi olan kayıtları düzeltmeye götürür.", "NEEDS_REVIEW görüyorsan kullan.", "Konum inceleme ekranı açılır."),
      button("Vardiyalar", "Kurulan işin teklif ve operasyon takibine götürür.", "Plan çıktıktan sonra kullan.", "Vardiyalar ekranı açılır."),
    ],
    screenMenus: [
      { label: "Vardiyalar", path: "/company/shifts", purpose: "Kurulan işin teklif ve operasyon takibini yapmak için açılır." },
      { label: "Sözleşmeler", path: "/company/agreements", purpose: "Sözleşmeli işleri ayrı görmek için açılır." },
      { label: "Konum İncele", path: "/company/georeview", purpose: "Konum sorunu olan kayıtları düzeltmek için açılır." },
      { label: "Copilot", path: "/company/copilot", purpose: "Takıldığında adım adım yardım almak için açılır." },
    ],
    simpleTerms: pickTerms(["sozlesme", "teklif", "atama"]),
    dataRules: ["NEEDS_REVIEW veya eksik koordinat varken çözüm ve teklif güvenilmez.", "Planlama Merkezi yeni iş kurar; oluşmuş işin takibi Vardiyalar ekranında yapılır.", "Guided adımları atlanırsa çözüm çıktısı görünüp iş mantığı yine eksik kalabilir.", "Geçici adres plan üretiminde kullanılabilir; kalıcı operasyon verisi olarak esas ihtiyaç lat/lon bilgisidir."],
    firstControls: ["NEEDS_REVIEW veya eksik koordinat var mı bak.", "Yeni iş mi, mevcut takip mi ayır.", "Rehberi Başlatmadan önce kişi/durak verisi hazır mı kontrol et."],
    stuckChecks: ["Konum sorunu varken çöz çalıştırma.", "Teklif gönderdikten sonraki takibi burada arama.", "Guided Step 3 tamamlanmadan ilerleme bekleme."],
    workflowStages: [
      { key: 'COMPANY_PLAN_REVIEW', title: 'Konum ve veri hazırlığını kontrol et', action: 'Önce georeview ihtiyacı olan kişi veya durak var mı kontrol et.', doneWhen: 'NEEDS_REVIEW kalmaz veya neden kaldığı bilinir.', ifBlocked: 'Konum seçici veya büyük harita ile eksik noktayı düzelt.' },
      { key: 'COMPANY_PLAN_START', title: 'Plan akışını başlat', action: 'Rehberi Başlat ile paket, tarih ve kapsam bilgisini seç.', doneWhen: 'Step akışı açık ve ilerliyor.', ifBlocked: 'Yanlış şirket/okul/organizasyon kapsamında olabilirsin.' },
      { key: 'COMPANY_PLAN_SOLVE', title: 'Kişi ve durak çözümünü tamamla', action: 'Durakları, matrix çözümünü ve teklif öncesi sayıları kontrol et.', doneWhen: 'Çözüm çıktısı mantıklı ve gönderime hazır.', ifBlocked: 'OSRM veya matrix sorunu varsa önce konum kalitesini düzelt.' },
      { key: 'COMPANY_PLAN_HANDOFF', title: 'Takibe doğru ekranla devam et', action: 'Plan çıktıysa Vardiyalar ekranına geç.', doneWhen: 'Takip ekranı netleşir.', ifBlocked: 'Hâlâ plan kuruyorsan bu ekrandan ayrılma.' },
    ],
    nextScreens: [
      { label: 'Konum İncele', path: '/company/georeview', reason: 'Eksik veya hatalı koordinatı düzeltmek için.' },
      { label: 'Vardiyalar', path: '/company/shifts', reason: 'Plan çıktıktan sonra takip ve teklif durumunu görmek için.' },
      { label: 'Sözleşmeler', path: '/company/agreements', reason: 'Sözleşmeli işlerde ayrı akışı görmek için.' },
    ],
    chatQuestions: ['Önce neyi kontrol edeyim?', 'Kontrol listesi ver', 'Guided modede sırayla ne yaparım?', 'Sonra hangi ekrana geçeyim?'],
  }),
  screen(2102, "/company/shifts", "Vardiyalar", {
    menuPurpose: "Bu ekranın ana işi takip etmektir. Burada kurulan vardiyaları, teklifleri, bekleyen işleri ve operasyon durumunu izlersin.",
    forWhom: "Şirket tarafında oluşmuş işi takip eden ve teklif durumunu okuyan kullanıcı içindir.",
    firstStep: "Önce doğru vardiyayı veya takip sekmesini seç.",
    nextStep: "Yeni iş kuracaksan Planlama Merkezi'ne dön; mevcut işin takibini burada sürdür.",
    doNotDo: "Vardiyalar ekranını yeni plan kurmanın ana yeri sanma veya yanlış vardiyada işlem yapma.",
    stepByStep: ["Takip edeceğin vardiyayı seç.", "Market, Bekleyen veya Liste bölümünde durumu oku.", "Gerekirse teklif, detay veya önizlemeyi aç.", "Yeni iş gerektiyse Planlama Merkezi'ne dön."],
    commonMistakes: ["Yeni iş kurmayı bu ekrandan başlatmaya çalışmak.", "Yanlış vardiya üzerinde karar vermek.", "Takip ekranını plan kurma ekranı sanmak."],
    doneChecklist: ["Doğru vardiya seçildi.", "Durum ve teklif tarafı okundu.", "Gerekli takip adımı açıldı."],
    buttonGuides: [
      button("Takip", "Vardiya listelerini takip görünümünde açar.", "Mevcut işlerin durumunu izlemek istediğinde kullan.", "Market, Bekleyen ve Liste alanları görünür."),
      button("Önizle", "Seçili vardiyanın rota ve özet bilgisini gösterir.", "Karar öncesi kısa kontrol gerektiğinde kullan.", "Vardiya özeti açılır."),
      button("Süre uzat", "Mevcut işin süresini uzatma akışını açar.", "Aynı iş devam edecekse kullan.", "Uzatma alanı açılır."),
    ],
    screenMenus: [
      { label: "Planlama Merkezi", path: "/company", purpose: "Yeni iş kurmak veya adım adım plan başlatmak için açılır." },
      { label: "Sözleşmeler", path: "/company/agreements", purpose: "Sözleşmeye bağlı işleri ayrı görmek için açılır." },
      { label: "Konum İncele", path: "/company/georeview", purpose: "Konum sorunu olan kayıtları düzeltmek için açılır." },
    ],
    simpleTerms: pickTerms(["sozlesme", "atama"]),
    dataRules: ["Bu ekran yeni plan kurma yeri değildir; yeni iş için Planlama Merkezi'ne dönülür.", "APPROVED görünmesi tek başına araç ve sürücü atamasının tamamlandığı anlamına gelmez.", "Agreement badge varsa klasik offer akışı kapalı veya farklı olabilir.", "Preview açılması operasyonun sahada başladığı anlamına gelmez; atama ve durum ayrıca okunmalıdır."],
    firstControls: ["Önce doğru vardiyayı seç.", "Takip, market ve bekleyen ayrımını doğru oku.", "Bu ekranın yeni plan kurma yeri olmadığını unutma."],
    stuckChecks: ["Onaylandı ama araç/sürücü yoksa atama katmanını kontrol et.", "Preview var diye iş bitti sanma.", "Sözleşmeli işte offer akışını normal kayıt gibi yorumlama."],
    workflowStages: [
      { key: 'COMPANY_SHIFT_PICK', title: 'Doğru liste ve vardiyayı seç', action: 'Market, Bekleyen veya Liste tarafında doğru kaydı aç.', doneWhen: 'Seçili vardiya net.', ifBlocked: 'Yanlış sekmedeysen aynı kaydı bulamazsın.' },
      { key: 'COMPANY_SHIFT_READ', title: 'Durumu katman katman oku', action: 'Teklif, atama, operasyon ve agreement rozetlerini ayrı ayrı değerlendir.', doneWhen: 'Kayıdın hangi aşamada olduğunu söyleyebilirsin.', ifBlocked: 'Rozetleri aynı anlama geliyor sanma.' },
      { key: 'COMPANY_SHIFT_DECIDE', title: 'İhtiyaca göre alt akışa geç', action: 'Teklif kararı, uzatma, operasyon olayı veya preview akışından doğru olanı aç.', doneWhen: 'Bir sonraki işlem net.', ifBlocked: "Yeni iş kurman gerekiyorsa Planlama Merkezi'ne dön." },
    ],
    nextScreens: [
      { label: 'Planlama Merkezi', path: '/company', reason: 'Yeni iş kurmak için.' },
      { label: 'Sözleşmeler', path: '/company/agreements', reason: 'Sözleşmeli akışı ayrı takip etmek için.' },
      { label: 'Konum İncele', path: '/company/georeview', reason: 'Eksik koordinat veya lokasyon sorunu varsa.' },
    ],
    chatQuestions: ['Bu kayıt ne durumda?', 'Önce neyi kontrol edeyim?', 'Kontrol listesi ver', 'Hangi ekrana geçeyim?', 'Bu satırı nasıl okurum?', 'Bu rozet ne demek?'],
    fieldGuides: [
      { label: 'Durum', meaning: 'Vardiyanın şu an hangi aşamada olduğunu gösterir.', howToRead: 'Market, bekleyen ve liste bağlamıyla birlikte oku.', risk: 'APPROVED tek başına tam atama anlamına gelmez.' },
      { label: 'Room', meaning: 'İşin bağlı olduğu oda veya sağlayıcıdır.' },
      { label: 'Araç', meaning: 'Atanmış araç bilgisidir.', risk: 'Boşsa atama tamam olmayabilir.' },
      { label: 'Sürücü', meaning: 'Atanmış sürücü bilgisidir.', risk: 'Boşsa saha hazırlığı eksik olabilir.' },
      { label: 'Durak', meaning: 'Vardiyadaki durak adedidir.' },
      { label: 'Başlangıç', meaning: 'İşin planlanan başlangıç zamanıdır.' },
      { label: 'Bitiş', meaning: 'İşin planlanan bitiş zamanıdır.' },
      { label: 'Sözleşme', meaning: 'Kayıt sözleşmeli akıştan mı geliyor bilgisidir.' },
    ],
    badgeGuides: [
      { label: 'MARKET', meaning: 'Pazarlık veya teklif tarafı sürüyor.', actionHint: 'Marketi aç veya teklif detayını oku.' },
      { label: 'PENDING', meaning: 'Karar veya onay bekleyen kayıt.', actionHint: 'Bekleyen tarafı ve eksik atamaları kontrol et.' },
      { label: 'APPROVED', meaning: 'İş onaylıdır.', actionHint: 'Araç ve sürücü atamasını ayrıca doğrula.', risk: 'Tek başına operasyon tamamen hazır demek değildir.' },
      { label: 'ACTIVE', meaning: 'İş sahada aktif ilerliyor.' },
      { label: 'DONE', meaning: 'İş tamamlanmıştır.' },
      { label: 'AGREEMENT', meaning: 'Sözleşme tabanlı akış olduğu için klasik offer mantığı değişebilir.' },
    ],
    rowReadHint: 'Önce durum ve hangi sekmede olduğuna bak. Sonra room, araç ve sürücü dolu mu kontrol et. En son başlangıç, bitiş ve durak bilgisiyle işin operasyon hazır olup olmadığını değerlendir.',
  }),
  screen(2103, "/company/agreements", "Sözleşmeler", {
    menuPurpose: "Şirket tarafındaki sözleşmeli işleri görmek ve yönetmek için kullanılır.",
    forWhom: "Sözleşmeli plan akışını yöneten kullanıcı içindir.",
    firstStep: "Önce doğru sözleşmeyi seç.",
    nextStep: "Bağlı işi görmek için vardiya ekranına geç.",
    doNotDo: "Sözleşmeyi görmeden işin tamamını anlamış sayma.",
    stepByStep: ["Sözleşmeyi seç.", "Durumunu oku.", "Bağlı işe geç."],
    commonMistakes: ["Sözleşmeli akışı normal teklif akışıyla karıştırmak."],
    doneChecklist: ["Doğru sözleşme seçildi.", "Bağlı iş görüldü."],
    buttonGuides: [
      button("Oluştur", "Yeni sözleşme kaydı açar.", "Yeni sözleşmeli iş kurulacaksa kullan.", "Yeni sözleşme formu açılır."),
      button("Uzat", "Sözleşme süresini uzatır.", "Aynı sözleşme devam edecekse kullan.", "Uzatma akışı açılır."),
      button("İptal et", "Sözleşmeyi kapatır.", "Geçersiz veya bitmişse kullan.", "Sözleşme durumu kapanır."),
    ],
    screenMenus: [
      { label: "Vardiyalar", path: "/company/shifts", purpose: "Sözleşmenin bağlı olduğu işleri görmek için açılır." },
      { label: "Copilot", path: "/company/copilot", purpose: "Sözleşme hakkında rehber almak için açılır." },
    ],
    simpleTerms: pickTerms(["sozlesme", "teklif"]),
  }),
  screen(2104, "/company/access-links", "Personel Link", {
    menuPurpose: "Personel için paylaşılan erişim linklerini üretmek ve yönetmek için kullanılır.",
    forWhom: "Şirket tarafında bağlantı paylaşan kullanıcı içindir.",
    firstStep: "Önce hangi personel veya grup için link gerektiğini seç.",
    nextStep: "Süre ve paylaşım şeklini netleştir.",
    doNotDo: "Süresini kontrol etmeden link paylaşma.",
    stepByStep: ["Link türünü seç.", "Süreyi belirle.", "Oluşan linki güvenli paylaş."],
    commonMistakes: ["Süresi geçmiş linki kullanmak."],
    doneChecklist: ["Doğru link üretildi.", "Süre kontrol edildi."],
    buttonGuides: [
      button("Link oluştur", "Yeni erişim linki üretir.", "Yeni paylaşım yapılacaksa kullan.", "Yeni link oluşur."),
      button("Kopyala", "Oluşan linki panoya alır.", "Paylaşmadan önce kullan.", "Link kopyalanır."),
      button("İptal et", "Linki pasif hale getirir.", "Artık kullanılmayacaksa kullan.", "Link pasif olur."),
    ],
    screenMenus: [
            { label: "Copilot", path: "/company/copilot", purpose: "Link türünü anlamıyorsan rehber için aç." },
    ],
    simpleTerms: pickTerms(["veliErisimi", "erisimLinki"]),
  }),
  screen(2105, "/company/copilot", "Copilot", {
    menuPurpose: "Şirket ekranlarında ne yapacağını anlamadığında yardım almak için kullanılır.",
    forWhom: "Şirket kullanıcısı içindir.",
    firstStep: "Önce iş veya ekran rehberini seç.",
    nextStep: "Gerekirse hızlı geçişle ilgili ekrana git.",
    doNotDo: "İlgili ekranı seçmeden genel yorum bekleme.",
    stepByStep: ["Rehber türünü seç.", "Kayıt veya ekranı seç.", "Sonucu oku ve geçişi kullan."],
    commonMistakes: ["Yanlış ekran için rehber açmak."],
    doneChecklist: ["Doğru rehber seçildi.", "Gerekli ekran açıldı."],
    buttonGuides: [
      button("Rehberi aç", "Seçilen rehberi çalıştırır.", "Yol gösterecek sade yardım istediğinde kullan.", "Rehber sonucu görünür."),
      button("Analiz et", "Gelişmiş analizi çalıştırır.", "Detaylı yorum gerektiğinde kullan.", "Gelişmiş sonuç görünür."),
    ],
    screenMenus: [
      { label: "Planlama Merkezi", path: "/company", purpose: "Yeni iş kurmak için açılır." },
      { label: "Vardiyalar", path: "/company/shifts", purpose: "İş detaylarını ve takibi görmek için açılır." },
      { label: "Sözleşmeler", path: "/company/agreements", purpose: "Sözleşmeli işleri görmek için açılır." },
    ],
    firstControls: ['Önce hangi ekran veya kayıt hakkında konuşacağını seç.', 'Seçili vardiya veya araç bağlamı varsa doğru geldi mi kontrol et.', 'Genel soru yerine operasyon sorusu sor.'],
    stuckChecks: ['Yanlış ekran seçiliyse cevap çok genel kalır.', 'Seçili kayıt yoksa copilot yalnız ekran seviyesinde konuşur.', 'Kısa takip sorularında aynı sohbeti sürdürmek gerekir.'],
    workflowStages: [
      { key: 'COPILOT_SCOPE', title: 'Bağlamı netleştir', action: 'Önce ekranı ve varsa seçili kaydı doğrula.', doneWhen: 'Üstte doğru ekran ve seçili kayıt görünür.', ifBlocked: 'Yanlış scope varsa ilgili ekrana dönüp kaydı yeniden seç.' },
      { key: 'COPILOT_ASK', title: 'Doğru soru tipini sor', action: 'Önce neyi kontrol edeyim, kontrol listesi ver, sık hata ne, hangi ekrana geçeyim gibi operasyon soruları sor.', doneWhen: 'Cevap doğrudan uygulanabilir olur.', ifBlocked: 'Soru çok genel kalırsa ekran veya kayıt adını ekle.' },
      { key: 'COPILOT_APPLY', title: 'Cevabı ekrana çevir', action: 'Önerilen quick action veya ekran geçişini gerçekten aç.', doneWhen: 'Sohbet operasyon adımına dönüşür.', ifBlocked: 'Sadece okuyup kalırsan copilot değer üretmez.' },
    ],
    nextScreens: [
      { label: 'Planlama Merkezi', path: '/company', reason: 'Yeni iş kurma soruları için.' },
      { label: 'Vardiyalar', path: '/company/shifts', reason: 'Mevcut iş ve teklif takibi için.' },
      { label: 'Konum İncele', path: '/company/georeview', reason: 'Koordinat veya lokasyon sorunları için.' },
    ],
    chatQuestions: ['Bu ekranda önce neyi kontrol edeyim?', 'Kontrol listesi ver', 'Sık hata ne?', 'Hangi ekrana geçeyim?'],
  }),
  screen(2106, "/company/hub", "Hub", {
    menuPurpose: "Personelin toplandığı veya bırakıldığı ana noktayı yönetmek için kullanılır.",
    forWhom: "Şirket operasyonunu yöneten kullanıcı içindir.",
    firstStep: "Önce hub bilgisinin doğru yerde olup olmadığını kontrol et.",
    nextStep: "Gerekirse ilgili iş veya rota ekranına geç.",
    doNotDo: "Hub olmadan rota ve yön hesabını tamam sanma.",
    stepByStep: ["Hub bilgisini aç.", "Konumu kontrol et.", "Gerekirse bağlı işe dön."],
    commonMistakes: ["Hub ile durağı karıştırmak.", "Inbound ve outbound yönünü karıştırmak."],
    doneChecklist: ["Hub anlamı netleşti.", "Konum kontrol edildi."],
    buttonGuides: [
      button("Kaydet", "Hub noktasını kaydeder.", "Hub bilgisi güncellenecekse kullan.", "Hub verisi kaydedilir."),
      button("Haritada seç", "Hub konumunu haritada seçmeyi açar.", "Noktayı elle seçmek istediğinde kullan.", "Harita seçimi açılır."),
    ],
    screenMenus: [
      { label: "Vardiyalar", path: "/company/shifts", purpose: "Hub'ın bağlı olduğu işi görmek için açılır." },
      { label: "Konum İncele", path: "/company/georeview", purpose: "Konum tarafını kontrol etmek için açılır." },
    ],
    simpleTerms: pickTerms(["hub", "inbound", "outbound"]),
  }),
  screen(2107, "/company/checkin", "Check-in", {
    menuPurpose: "Biniş, iniş veya doğrulama kayıtlarını görmek için kullanılır.",
    forWhom: "Check-in tarafını takip eden şirket kullanıcısı içindir.",
    firstStep: "Önce hangi kayıt için check-in baktığını seç.",
    nextStep: "Gerekirse ilgili iş ekranına dön.",
    doNotDo: "Check-in kaydını tek başına tüm operasyon sanma.",
    stepByStep: ["Kayıdı seç.", "Check-in olayını oku.", "Gerekirse iş ekranına dön."],
    commonMistakes: ["Check-in ile yoklama veya daveti karıştırmak."],
    doneChecklist: ["Doğru check-in kaydı görüldü."],
    buttonGuides: [button("Kaydı aç", "Seçili check-in olayını açar.", "Detay görmek istediğinde kullan.", "Kayıt detayı açılır.")],
    screenMenus: [{ label: "Vardiyalar", path: "/company/shifts", purpose: "Check-in kaydının bağlı olduğu işi görmek için açılır." }],
    simpleTerms: pickTerms(["checkin"]),
  }),
  screen(2109, "/company/georeview", "Konum İncele", {
    menuPurpose: "Konum verisinin neden eksik, hatalı veya tutarsız göründüğünü kontrol etmek için kullanılır.",
    forWhom: "Konum tarafında sorun inceleyen şirket kullanıcısı içindir.",
    firstStep: "Önce hangi kayıt veya kişinin konumunu incelediğini seç.",
    nextStep: "Sorunun konum verisi mi, yol hesabı mı, yoksa eşleşme mi olduğunu ayır.",
    doNotDo: "Konum görünmüyor diye hemen tek sebep var sanma.",
    stepByStep: ["Kayıdı seç.", "Konum durumunu oku.", "Gerekirse ilgili iş veya araç ekranına dön."],
    commonMistakes: ["Konum İncele ile canlı haritayı aynı sanmak.", "OSRM ve matrix terimlerini anlamadan karar vermek."],
    doneChecklist: ["Sorun tipi netleşti."],
    buttonGuides: [
      button("Seç", "Soldaki satırı aktif kayıt yapar.", "Başka bir kişi üzerinde işlem yapmak istediğinde kullan.", "Sağ panel seçili kişiyle senkron olur."),
      button("Adresten Bul", "Yazılan adrese göre koordinat üretmeye çalışır.", "Elle pin koymadan önce metin adresinden sonuç almak istediğinde kullan.", "Lat/lon alanları yeni sonuca göre güncellenir."),
      button("Büyük Haritada İşaretle", "Noktayı büyük harita modalında rahat seçmeni sağlar.", "Küçük önizlemede hassas seçim zor olduğunda kullan.", "Büyük harita açılır ve OK ile geri dönülür."),
      button("Konumu Temizle", "Seçili kaydın sağ paneldeki geçici konumunu temizler.", "İşaretlemeyi baştan yapmak istediğinde kullan.", "Geçici lat/lon temizlenir; kalıcı kayıt ancak Kaydet ile değişir."),
      button("Kaydet", "Seçili kaydın lat/lon bilgisini veritabanına yazar.", "Konum doğrulandıysa kullan.", "Kayıt güncellenir ve satırdaki koordinat alanı yenilenir."),
      button("Kaydet + Sonraki", "Kaydetme sonrası sıradaki kişiye geçer.", "Seri konum düzeltme yaparken kullan.", "Mevcut kayıt kaydedilir ve liste bir sonraki satıra ilerler."),
      button("OK Yap", "Büyük harita seçim modalını kapatır.", "İşaretleme bittiğinde kullan.", "Seçilen nokta küçük önizlemeye geri taşınır."),
      button("Tüm Adresleri Temizle", "Aktif kapsam içindeki adres alanlarını toplu temizler.", "KVKK hazırlığında artık adres tutmak istemiyorsan kullan.", "Adres alanları boşaltılır."),
      button("Tüm Telefonları Temizle", "Aktif kapsam içindeki telefon alanlarını toplu temizler.", "KVKK hazırlığında telefon tutmak istemiyorsan kullan.", "Telefon alanları boşaltılır."),
    ],
    screenMenus: [
      { label: "Vardiyalar", path: "/company/shifts", purpose: "Sorunun bağlı olduğu işi görmek için açılır." },
      { label: "Hub", path: "/company/hub", purpose: "Toplama veya bırakma noktasını kontrol etmek için açılır." },
    ],
    simpleTerms: pickTerms(["konumIncele", "osrm", "matrix", "sureHesabi"]),
    dataRules: ["Seç butonuna bastığında sağ paneldeki seçili kişi adı aynı satıra dönmelidir.", "Kaydet veritabanına yazar; OK Yap yalnız işaretleme modalını onaylar.", "Kaydet + Sonraki kaydetme sonrası sıradaki kişiyi seçer; seçimi tek başına değiştiren buton Seç'tir.", "Guided Step 3'ten gelince varsayılan kapsam yalnız aktif planlama oturumundaki seçili kişiler olmalıdır.", "Küçük harita önizlemedir; hassas nokta seçimi büyük haritada yapılır.", "KVKK tarafında kalıcı ihtiyaç lat/lon olabilir; adres ve telefon gerektiğinde toplu temizlenebilir."],
    firstControls: ["Önce doğru kişiyi veya durağı seç.", "Harita önizleme ile seçili kayıt aynı mı kontrol et.", "Sorunun koordinat mı, adres mi, yol hesabı mı olduğunu ayır."],
    stuckChecks: ["Seç butonuna bastığında seçili kayıt değişmiyorsa oturum filtresini kontrol et.", "Küçük harita bozuksa tile/CSS problemi olup olmadığına bak.", "Guided Step 3'ten geldiysen yalnız oturum kişileriyle çalışman gerekir."],
    workflowStages: [
      { key: 'GEO_PICK', title: 'Doğru kaydı seç', action: 'Listeden kişiyi seç ve sağdaki panelde seçili kişi adını doğrula.', doneWhen: 'Seçili satır ve sağ panel aynı kişiyi gösterir.', ifBlocked: 'Seçim geri dönüyorsa preferred selection akışını kontrol et.' },
      { key: 'GEO_MARK', title: 'Büyük haritada noktayı işaretle', action: 'Büyük harita aç, doğru noktayı seç ve OK ile kapat.', doneWhen: 'Küçük önizlemede yeni pin görünür.', ifBlocked: 'İşaretleme görünmüyorsa leaflet render ve koordinat state güncellemesini kontrol et.' },
      { key: 'GEO_SAVE', title: 'Kaydet ve sıradaki kişiye geç', action: 'Kaydet veya Kaydet + Sonraki ile lat/lon bilgisini sabitle.', doneWhen: 'Satırdaki kayıt güncellenir ve gerekiyorsa sıradaki kişi seçilir.', ifBlocked: 'Kaydet + Sonraki seçimi değiştirmiyorsa selected id akışını kontrol et.' },
      { key: 'GEO_CLEAN', title: 'KVKK temizliğini tamamla', action: 'Gerekirse adres ve telefon temizleme akışını uygula.', doneWhen: 'Kalıcıda yalnız gerekli lat/lon kalır.', ifBlocked: 'Toplu temizleme çağrısı yetki veya backend route problemi veriyorsa loga bak.' },
    ],
    nextScreens: [
      { label: 'Planlama Merkezi', path: '/company', reason: 'Konumlar düzeldikten sonra plan akışına dönmek için.' },
      { label: 'Vardiyalar', path: '/company/shifts', reason: 'Plan çıktıysa takip tarafına geçmek için.' },
      { label: 'Hub', path: '/company/hub', reason: 'Toplanma veya bırakma noktasını ayrıca kontrol etmek için.' },
    ],
    chatQuestions: ['Bu ekranda önce neyi kontrol edeyim?', 'Kaydet + Sonraki ne yapmalı?', 'Büyük harita ile nasıl işaretlerim?', 'Adres temizleme ne zaman yapılır?', 'Bu satırı nasıl okurum?', 'Bu rozet ne demek?'],
    fieldGuides: [
      { label: 'Ad Soyad', meaning: 'Düzenlediğin kişi kaydıdır.' },
      { label: 'Adres', meaning: 'Geçici olarak konum üretmek için kullanılan metin adresidir.', risk: 'KVKK nedeniyle kalıcı tutmama kararı varsa temizlenebilir.' },
      { label: 'Durum', meaning: 'Konum kaydının hazır mı incelemede mi olduğunu gösterir.' },
      { label: 'Koordinat', meaning: 'Kalıcı olarak esas ihtiyaç duyulan lat/lon bilgisidir.', howToRead: 'Lat ve lng birlikte geçerli sayıysa kayıt harita için kullanılabilir.' },
      { label: 'Neden', meaning: 'Neden inceleme gerektiğini anlatan nottur.' },
    ],
    badgeGuides: [
      { label: 'OK', meaning: 'Konum kullanıma hazır görünüyor.' },
      { label: 'NEEDS_REVIEW', meaning: 'Konum veya adres tarafında inceleme gerekiyor.', actionHint: 'Adresten bul, büyük haritada işaretle veya elle düzelt.' },
      { label: 'FAILED', meaning: 'Otomatik üretim başarısız olmuş olabilir.', actionHint: 'Elle kontrol et ve kaydet.' },
      { label: 'MANUAL_OVERRIDE', meaning: 'Kayıt elle doğrulanmış veya düzeltilmiştir.' },
    ],
    rowReadHint: 'Önce kişi adını ve durum rozetini oku. Sonra koordinat var mı bak. En son neden alanına göre kaydet, adresten bul veya büyük harita kararını ver.',
  }),
  screen(2112, "/company/map", "Canlı Harita", {
    menuPurpose: "Canlı araç, rota ve sıradaki durak bilgisini tek ekranda okumak için kullanılır.",
    forWhom: "Şirket, okul ve organizasyon tarafında canlı takibi izleyen kullanıcı içindir.",
    firstStep: "Önce doğru aracı veya vardiyayı seç.",
    nextStep: "Sorun varsa Vardiyalar veya Copilot tarafına geç.",
    doNotDo: "Eski GPS bilgisini canlı sanma veya yanlış aracı okuyup karar verme.",
    stepByStep: ["Doğru aracı seç.", "Son GPS, sıradaki durak ve ETA bilgisini birlikte oku.", "Gerekirse Vardiyalar ekranına geç."],
    commonMistakes: ["Haritadaki tek rozetle karar vermek.", "Mavi, yeşil ve tam rota çizgilerini aynı şey sanmak."],
    doneChecklist: ["Doğru araç seçildi.", "Canlı özet ve ETA birlikte okundu."],
    buttonGuides: [
      button("Durakları göster", "Durak pinlerini açıp kapatır.", "Haritada durak yoğunluğunu görmek istediğinde kullan.", "Durak markerları görünür veya gizlenir."),
      button("Sonraki Durağa Navigasyon", "Sıradaki durak için dış navigasyonu açar.", "Sürücüye sıradaki hedefi net göstermek istediğinde kullan.", "Harici navigasyon sıradaki durağa göre açılır."),
      button("Tam Rotayı Dış Navigasyonda Aç", "Tüm rotayı harici navigasyonda açar.", "Tam yol tarifine ihtiyaç olduğunda kullan.", "Harici navigasyon tüm durak sırasını açar."),
      button("Tümünü Göster", "Araç ve durakların tamamını görünür alana sığdırır.", "Harita fazla yakınlaştıysa kullan.", "Kamera tüm aktif rota alanına oturur."),
    ],
    screenMenus: [
      { label: "Vardiyalar", path: "/company/shifts", purpose: "Haritadaki kaydın bağlı olduğu işi okumak için açılır." },
      { label: "Copilot", path: "/company/copilot", purpose: "Takıldığında harita ve canlılık rehberi almak için açılır." },
    ],
    simpleTerms: pickTerms(["telefonGps", "cihazGps", "konumKaynagi"]),
    dataRules: ["Son GPS çok eskiyse bu ekran tek başına canlı karar için yetmez.", "Sıradaki durak, ETA ve kalan durak sayısı birlikte okunmalıdır.", "Mavi aktif parça sıradaki hedefi, yeşil parça geçilen kısmı gösterir; tam rota tabanı ayrı görülebilir.", "Araç seçili değilse üst kart ve Copilot bağlamı doğru değişmez; önce doğru satırı seç."],
    firstControls: ["Önce doğru aracı seç.", "Son GPS zamanı yeni mi kontrol et.", "Sıradaki durak ve ETA mantıklı mı bak."],
    stuckChecks: ["Araç seçili değilse üst kart değişmez.", "GPS eskiyse canlı karar verme.", "Harita var ama ETA sabitse rota yenileme zincirini kontrol et."],
    workflowStages: [
      { key: 'COMPANY_MAP_PICK', title: 'Doğru kaydı seç', action: 'Listeden veya haritadan doğru aracı seç.', doneWhen: 'Üst kartta plaka ve özet görünür.', ifBlocked: 'Seçim değişmiyorsa filtre ve yenileme akışını kontrol et.' },
      { key: 'COMPANY_MAP_READ', title: 'Canlı özeti oku', action: 'Son GPS, sıradaki durak, ETA ve kalan durak bilgisini birlikte değerlendir.', doneWhen: 'Canlı durumu tek cümlede özetleyebilirsin.', ifBlocked: 'GPS çok eskiyse vardiya ekranına in.' },
      { key: 'COMPANY_MAP_DECIDE', title: 'Doğru ekrana geç', action: 'Operasyon ayrıntısı için Vardiyalar, yardım için Copilot aç.', doneWhen: 'Bir sonraki ekran netleşir.', ifBlocked: 'Sorun tipi belirsizse seçili vardiya bağını netleştir.' },
    ],
    nextScreens: [
      { label: 'Vardiyalar', path: '/company/shifts', reason: 'Haritadaki kaydın teklif, atama ve operasyon durumunu okumak için.' },
      { label: 'Copilot', path: '/company/copilot', reason: 'Canlılık, ETA ve seçili kayıt sorularını adım adım sormak için.' },
    ],
    chatQuestions: ['Bu satırı nasıl okurum?', 'Bu sütun ne demek?', 'Bu rozet ne demek?', 'Bu seçili kayıtta eksik ne var?', 'Önce neyi kontrol edeyim?'],
    fieldGuides: [
      { label: 'Araç', meaning: 'Seçili aracın plakasını veya kayıt numarasını gösterir.' },
      { label: 'Son GPS', meaning: 'Canlı konum bilgisinin ne kadar önce geldiğini gösterir.', risk: 'Çok eskiyse canlı karar vermek yanıltıcı olabilir.' },
      { label: 'Sıradaki Durak', meaning: 'Aracın bir sonraki hedef noktasıdır.' },
      { label: 'ETA', meaning: 'Sıradaki durağa tahmini kalan süredir.', risk: 'Sabit kalıyorsa rota güncellenmiyor olabilir.' },
      { label: 'Toplam Durak', meaning: 'Seçili vardiyadaki toplam durak sayısıdır.' },
      { label: 'Kalan', meaning: 'Henüz tamamlanmamış durak adedidir.' },
    ],
    badgeGuides: [
      { label: 'GPS', meaning: 'Araç GPS sinyalinin canlı mı eski mi olduğunu gösterir.' },
      { label: 'Vardiya Durumu', meaning: 'Seçili vardiyanın operasyon durumunu kısa gösterir.' },
      { label: 'ONLINE', meaning: 'Canlı GPS akışı var.' },
      { label: 'OFFLINE', meaning: 'Canlı GPS akışı görünmüyor veya düşmüş olabilir.', actionHint: 'Son GPS zamanını ve cihaz/telefon tarafını kontrol et.' },
    ],
    rowReadHint: 'Önce araç alanını doğrula. Sonra Son GPS, Sıradaki Durak ve ETA alanlarını birlikte oku. En son toplam ve kalan durak ile işin rotadaki konumunu anla.',
  }),

  screen(2114, "/company/service-evaluation", "Hizmet Değerlendirme", {
    menuPurpose: "Tamamlanan veya aktif hizmetlerin kalite ve memnuniyet tarafını görmek için kullanılır.",
    forWhom: "Şirket tarafında hizmet kalitesini takip eden kullanıcı içindir.",
    firstStep: "Önce hangi hizmet veya sağlayıcıya baktığını netleştir.",
    nextStep: "Gerekirse ilgili vardiyayı veya sözleşmeyi aç.",
    doNotDo: "Bu ekranı plan kurma ekranı sanma; burada kalite takibi yapılır.",
    stepByStep: ["Hizmet satırlarını oku.", "Durum ve değerlendirme alanını kontrol et.", "Gerekirse ilgili vardiyayı aç.", "Hizmet tamamlandıysa puan veya not ver."],
    commonMistakes: ["Hizmet Değerlendirme ile Planlama Merkezi'ni karıştırmak.", "Hizmet bitmeden puan beklemek."],
    doneChecklist: ["Doğru hizmet satırı okundu.", "Durum ve sonraki adım anlaşıldı.", "Gerekirse ilgili vardiyaya geçildi."],
    buttonGuides: [
      button("Hizmetleri aç", "İlgili vardiya veya hizmet listesini açar.", "Bağlı işi görmek istediğinde kullan.", "Vardiya veya hizmet tarafı açılır."),
      button("Sözleşmeleri aç", "Bağlı sözleşmeleri açar.", "Sözleşme etkisini görmek istediğinde kullan.", "Sözleşme ekranı açılır."),
    ],
    screenMenus: [
      { label: "Vardiyalar", path: "/company/shifts", purpose: "Değerlendirilen hizmetin bağlı olduğu işi görmek için açılır." },
      { label: "Sözleşmeler", path: "/company/agreements", purpose: "Hizmete bağlı sözleşme varsa görmek için açılır." },
      { label: "Ticari Akışım", path: "/company/commercial-flow", purpose: "İşin ticari geçmişini görmek için açılır." },
    ],
    simpleTerms: pickTerms(["sozlesme", "atama", "teklif"]),
    dataRules: ["Bu ekran kalite ve sonuç takibidir; yeni plan kurma veya pazarlık başlatma yeri değildir.", "Hizmet tamamlanmadan değerlendirme rozeti tam anlamlı olmayabilir.", "Sağlayıcı puanı geçmiş performansı gösterir; tek satırlık hizmet sonucuyla birlikte okunmalıdır."],
    firstControls: ["Önce doğru hizmet satırını seç.", "Durum, değerlendirme rozeti ve sonraki adım alanını birlikte oku.", "Gerekirse bağlı vardiyayı aç."],
    stuckChecks: ["Hizmet bitmeden puan bekleme.", "Kalite ekranını planlama ekranı sanma.", "Sonraki adım boşsa satır seçimi veya veri yenileme gerekebilir."],
    chatQuestions: ['Bu satırı nasıl okurum?', 'Bu rozet ne demek?', 'Bu seçili kayıtta eksik ne var?', 'Hangi ekrana geçeyim?'],
    fieldGuides: [
      { label: 'Sağlayıcı', meaning: 'Hizmeti veren oda veya sağlayıcı bilgisidir.' },
      { label: 'Puan', meaning: 'Sağlayıcının geçmiş hizmet puanı ve değerlendirme sayısıdır.', risk: 'Henüz puan yoksa kalite yargısı için tek başına yeterli veri olmayabilir.' },
      { label: 'Hizmet', meaning: 'Değerlendirilen işin kısa etiketidir.' },
      { label: 'Tarih', meaning: 'Hizmetin tamamlandığı veya değerlendirmeye düştüğü zamanı gösterir.' },
      { label: 'Sonraki Adım', meaning: 'Bu kayıtta şimdi hangi işleme gitmen gerektiğini söyler.' },
    ],
    badgeGuides: [
      { label: 'Durum', meaning: 'Hizmetin operasyon durumunu gösterir.' },
      { label: 'Değerlendirme', meaning: 'Puan verilebilir mi, bekliyor mu, tamamlandı mı bilgisini özetler.' },
      { label: 'DONE', meaning: 'Hizmet tamamlanmıştır.' },
      { label: 'ACTIVE', meaning: 'Hizmet halen aktif akışta olabilir.' },
      { label: 'BEKLİYOR', meaning: 'Değerlendirme veya sonuç henüz tamamlanmamış olabilir.' },
    ],
    rowReadHint: 'Önce hizmet ve sağlayıcıyı oku. Sonra durum ve değerlendirme rozetini değerlendir. En son sonraki adım alanına göre vardiya mı sözleşme mi açacağına karar ver.',
  }),
  screen(2115, "/company/commercial-flow", "Ticari Akışım", {
    menuPurpose: "Market, kabul ve operasyona inen ticari kayıtları tek yerde görmek için kullanılır.",
    forWhom: "Şirket tarafında ticari durumu ve sonraki adımı izleyen kullanıcı içindir.",
    firstStep: "Önce listedeki kaydın market, kabul veya operasyon tarafında mı olduğuna bak.",
    nextStep: "Gerekirse ilgili vardiyayı, marketi veya hizmet değerlendirme ekranını aç.",
    doNotDo: "Ticari Akışım ekranını Planlama Merkezi sanma; burada yeni plan kurulmaz.",
    stepByStep: ["Kayıtların akış türünü oku.", "Durum ve sonraki adım sütununu kontrol et.", "Gerekirse ilgili vardiyaya git.", "Operasyon başladıysa hizmet değerlendirme tarafını izle."],
    commonMistakes: ["Planlama Merkezi ile Ticari Akışım'ı karıştırmak.", "Kabul edilen kayıtla aktif operasyonu aynı sanmak."],
    doneChecklist: ["Kayıdın hangi aşamada olduğu anlaşıldı.", "Sonraki adım görüldü.", "Gerekirse ilgili ekrana geçildi."],
    buttonGuides: [
      button("Listeyi aç", "Seçili kaydı normal liste/takip tarafında açar.", "Kayıt artık market veya pending dışında ilerlemişse kullan.", "İlgili vardiya liste tarafında açılır."),
      button("Bekleyeni aç", "Seçili kaydı bekleyen karar tarafında açar.", "Kayıt pending veya onay bekliyorsa kullan.", "İlgili kayıt bekleyen görünümde açılır."),
      button("Marketi aç", "Ticari teklif veya pazarlık tarafına gider.", "Kayıt market aşamasındaysa kullan.", "Market görünümü veya bağlı vardiya açılır."),
      button("Planlama Merkezi'ni aç", "Yeni iş kurma ekranını açar.", "Yeni iş kurulacaksa kullan.", "Planlama Merkezi açılır."),
      button("Hizmet Değerlendirme", "Operasyon sonrası kalite ekranını açar.", "Tamamlanan hizmetin kalitesine bakacaksan kullan.", "Hizmet Değerlendirme ekranı açılır."),
    ],
    screenMenus: [
      { label: "Planlama Merkezi", path: "/company", purpose: "Yeni iş kurmak için açılır." },
      { label: "Vardiyalar", path: "/company/shifts", purpose: "Kayıdın bağlı olduğu işi görmek için açılır." },
      { label: "Hizmet Değerlendirme", path: "/company/service-evaluation", purpose: "Aktif veya biten hizmetin kalite tarafını görmek için açılır." },
    ],
    simpleTerms: pickTerms(["teklif", "sozlesme", "atama"]),
    fieldGuides: [
      { label: 'Karşı Taraf', meaning: 'Ticari kaydın karşısındaki oda veya sağlayıcıdır.' },
      { label: 'Akış', meaning: 'Kayıdın market, kabul veya operasyon tarafında mı olduğunu gösterir.' },
      { label: 'Tutar', meaning: 'Ticari pazarlıkta görünen fiyat bilgisidir.' },
      { label: 'Durum', meaning: 'Kayıdın ticari veya operasyonel aşama etiketidir.' },
      { label: 'Son Güncelleme', meaning: 'Bu kayıtta en son hareketin ne zaman olduğunu gösterir.' },
      { label: 'Sonraki Adım', meaning: 'Buradan sonra hangi ekrana veya işleme gitmen gerektiğini özetler.' },
    ],
    badgeGuides: [
      { label: 'OPEN', meaning: 'Teklif açık durumda.' },
      { label: 'COUNTERED', meaning: 'Karşı teklif aşamasında.' },
      { label: 'ACCEPTED', meaning: 'Pazarlık kabul edilmiş, operasyon hazırlığına inmiş.' },
      { label: 'APPROVED', meaning: 'İş onaylı operasyon tarafına geçmiş.' },
      { label: 'ACTIVE', meaning: 'İş aktif operasyonda.' },
      { label: 'DONE', meaning: 'İş tamamlanmış.' },
    ],
    rowReadHint: 'Önce akış ve durum alanını oku. Sonra karşı taraf ve tutarla ticari bağlamı anla. En son sonraki adım metnine göre Listeyi aç, Bekleyeni aç veya Marketi aç kararını ver.',
  }),
  screen(2116, "/company/reports", "Raporlar", {
    menuPurpose: "Sürücü, araç ve durak raporlarını görmek için kullanılır.",
    forWhom: "Şirket tarafında özet tablo ve performans takibi yapan kullanıcı içindir.",
    firstStep: "Önce hangi rapor türüne baktığını seç.",
    nextStep: "Gerekirse bağlı vardiya veya harita ekranına geç.",
    doNotDo: "Rapor ekranını canlı operasyon ekranı sanma.",
    stepByStep: ["Rapor türünü seç.", "Sütunları ve sayıları oku.", "Sorun veya eksik gördüysen ilgili ekrana geç."],
    commonMistakes: ["Canlı veriyi rapor tablosu ile karıştırmak."],
    doneChecklist: ["Doğru rapor türü açıldı.", "Temel tablo okundu."],
    buttonGuides: [button("Raporu aç", "İlgili rapor görünümünü açar.", "Sürücü, araç veya durak raporuna bakarken kullan.", "Rapor görünümü açılır.")],
    screenMenus: [
      { label: "Harita", path: "/company/map", purpose: "Canlı aracı veya rota tarafını görmek için açılır." },
      { label: "Vardiyalar", path: "/company/shifts", purpose: "Rapordaki kaydın bağlı olduğu işi görmek için açılır." },
    ],
    simpleTerms: pickTerms(["rapor", "atama"]),
  }),
  screen(2110, "/shared/notifications", "Bildirimler", {
    menuPurpose: "Kullanıcılara giden uyarı ve haberleri görmek için kullanılır.",
    forWhom: "Şirket kullanıcısı içindir.",
    firstStep: "Önce bildirimin ne anlattığını oku.",
    nextStep: "Gerekirse ilgili iş veya kayıt ekranına git.",
    doNotDo: "Bildirimi işlem kaydı ile aynı sanma.",
    stepByStep: ["Bildirimi seç.", "İçeriğini oku.", "Gerekirse ilgili yere git."],
    commonMistakes: ["Bildirim ile logu karıştırmak."],
    doneChecklist: ["Bildirim anlamı netleşti."],
    buttonGuides: [button("İlgili yere git", "Bildirimin bağlı olduğu ekrana götürür.", "Sorunun kaynağına gitmek istediğinde kullan.", "İlgili ekran açılır.")],
    screenMenus: [{ label: "Loglar", path: "/shared/logs", purpose: "Sistem kaydını karşılaştırmak için açılır." }],
    simpleTerms: pickTerms(["bildirim", "islemKaydi"]),
  }),
  screen(2111, "/shared/logs", "Loglar", {
    menuPurpose: "Sistemde ne olduğunun kayıt altına alınmış halini görmek için kullanılır.",
    forWhom: "Şirket kullanıcısı içindir.",
    firstStep: "Önce aradığın olayı seç veya filtrele.",
    nextStep: "Gerekirse ilgili bildirim veya iş ekranına dön.",
    doNotDo: "Log kaydını kullanıcı bildirimi sanma.",
    stepByStep: ["Kayıdı filtrele.", "Olayı oku.", "Gerekirse bağlı ekrana git."],
    commonMistakes: ["Log ile bildirimi aynı sanmak."],
    doneChecklist: ["İşlem kaydı anlamı netleşti."],
    buttonGuides: [button("Filtre uygula", "Kayıtları daraltır.", "Belirli olayı aradığında kullan.", "Liste daralır.")],
    screenMenus: [{ label: "Bildirimler", path: "/shared/notifications", purpose: "Kullanıcıya giden uyarıyı görmek için açılır." }],
    simpleTerms: pickTerms(["islemKaydi", "bildirim"]),
  }),
];

const SCHOOL = COMPANY.map((x) => ({
  ...x,
  path: x.path.replace('/company', '/school'),
  label: x.path === '/company/georeview' ? 'Öğrenci Konum İncele' : x.label,
})).concat([
  screen(2201, '/school/parents', 'Veli Erişimi', {
    menuPurpose: 'Veli tarafı için süreli link, erişim kodu ve PIN üretmek için kullanılır.',
    forWhom: 'Okul yönetimi içindir.',
    firstStep: 'Önce öğrenci seçimini yap.',
    nextStep: 'Süreyi seç ve paylaşım bilgisini kontrol et.',
    doNotDo: 'Yanlış öğrenci için erişim üretme.',
    stepByStep: ['Öğrenciyi seç.', 'Süreyi belirle.', 'Link, kod ve PIN üretip paylaşmadan önce kontrol et.'],
    commonMistakes: ['Yanlış öğrenci için erişim üretmek.'],
    doneChecklist: ['Doğru öğrenci için erişim üretildi.'],
    buttonGuides: [button('Erişim üret', 'Yeni veli erişimi üretir.', 'Yeni paylaşım gerektiğinde kullan.', 'Yeni erişim oluşur.')],
    screenMenus: [{ label: 'Öğrenci Link', path: '/school/access-links', purpose: 'Benzer paylaşım yüzeyini görmek için açılır.' }],
    simpleTerms: pickTerms(["veliErisimi", "erisimLinki"]),
  }),
]);

const ORGANIZATION = COMPANY.map((x) => {
  const mapped = { ...x, path: x.path.replace('/company', '/organization'), label: x.path === '/company/georeview' ? 'Lokasyon İncele' : x.label === 'Planlama Merkezi' ? 'Organizasyon Merkezi' : x.label };

  if (x.path === '/company') {
    return screen(2101, '/organization', 'Gezi / Planlama Merkezi', {
      menuPurpose: 'Yeni gezi veya organizasyon işini burada kurarsın. Toplanma noktasını, plan paketini, tahmini kişi sayısını, gidilecek yerleri ve dönüş tipini burada tamamlarsın.',
      forWhom: 'Organizasyon tarafında gezi, tur veya toplu etkinlik işi kuran kullanıcı içindir.',
      firstStep: 'Önce toplanma noktasını ve gidilecek yerlerin koordinat durumunu kontrol et. Eksik koordinat varsa önce tamamla.',
      nextStep: 'Taslak plan tamam olduktan sonra ön izleme ve teklif adımına geç; takip için sonra Vardiyalar ekranını kullan.',
      doNotDo: 'Company/School planı gibi kişi-durak çözümünü zorunlu sanma veya eksik planı markete düşürmeye çalışma.',
      stepByStep: ['Toplanma noktasını kaydet.', 'Rehberi Başlat ile plan akışını aç.', 'Plan paketi, tarih ve günleri seç.', 'Tahmini kişi sayısını, gidilecek yerleri ve dönüş tipini gir.', 'Eksik koordinat varsa tamamla, sonra ön izleme ve rota sıralamayı kontrol et.', 'Plan tamamsa teklifi gönder; takip için Vardiyalar ekranına geç.'],
      commonMistakes: ['Toplanma noktasını kaydetmeden devam etmek.', 'Gidilecek yerleri eksik koordinatla bırakmak.', 'Takip ekranını yeni plan kurma ekranı sanmak.'],
      doneChecklist: ['Toplanma noktası kaydedildi.', 'Tahmini kişi sayısı girildi.', 'Gidilecek yerler ve dönüş tipi tamamlandı.', 'Teklif veya plan çıktısı üretildi.'],
      buttonGuides: [
        button('Rehberi Başlat', 'Gezi planlama akışını adım adım açar.', 'Yeni gezi veya organizasyon işi kuracaksan kullan.', 'Toplanma noktası → plan paketi → kişi sayısı / yerler → ön izleme akışı açılır.'),
        button('Konum kontrol et', 'Toplanma noktası ve gidilecek yerlerin konum sorunlarını düzeltmeye yardım eder.', 'Koordinat eksik veya hatalıysa kullan.', 'Eksik konumları tamamlayıp plana geri dönersin.'),
        button('Vardiyalar', 'Kurulan işin teklif ve operasyon takibine götürür.', 'Plan çıktıktan sonra kullan.', 'Vardiyalar ekranı açılır.'),
      ],
      screenMenus: [
        { label: 'Vardiyalar', path: '/organization/shifts', purpose: 'Kurulan gezi/organizasyon işinin teklif ve operasyon takibini yapmak için açılır.' },
        { label: 'Lokasyon İncele', path: '/organization/georeview', purpose: 'Konum sorunu olan kayıtları düzeltmek için açılır.' },
        { label: 'Copilot', path: '/organization/copilot', purpose: 'Takıldığında organization rehberi almak için açılır.' },
      ],
      simpleTerms: pickTerms(['teklif', 'atama']),
    });
  }

  if (x.path === '/company/shifts') {
    return screen(2102, '/organization/shifts', 'Vardiyalar', {
      menuPurpose: 'Bu ekranın ana işi takip etmektir. Burada açılmış gezi/organizasyon işlerini, teklifleri ve operasyon durumunu izlersin.',
      forWhom: 'Organizasyon tarafında oluşturulmuş işi takip eden kullanıcı içindir.',
      firstStep: 'Önce doğru planı veya takip sekmesini seç.',
      nextStep: "Yeni gezi kuracaksan Gezi / Planlama Merkezi'ne dön; mevcut işin takibini burada sürdür.",
      doNotDo: 'Vardiyalar ekranını yeni gezi planı kurmanın ana yeri sanma veya plan eksikse burada düzeltmeye çalışma.',
      stepByStep: ["Takip edeceğin işi seç.", "Market, Bekleyen veya Liste bölümünde durumu oku.", "Gerekirse önizleme, teklif detayı veya rota ekranını aç.", "Plan eksikse Gezi / Planlama Merkezi'ne dön."],
      commonMistakes: ['Yeni geziyi bu ekrandan kurmaya çalışmak.', 'Eksik koordinatı takip ekranında çözmeye çalışmak.', 'Takip ekranını plan kurma ekranı sanmak.'],
      doneChecklist: ['Doğru iş seçildi.', 'Teklif ve takip durumu okundu.', 'Gerekli takip adımı açıldı.'],
      buttonGuides: [
        button('Takip', 'Gezi/organizasyon işlerini takip görünümünde açar.', 'Mevcut işlerin durumunu izlemek istediğinde kullan.', 'Market, Bekleyen ve Liste alanları görünür.'),
        button('Önizle', 'Seçili işin rota ve özet bilgisini gösterir.', 'Karar öncesi kısa kontrol gerektiğinde kullan.', 'Vardiya özeti açılır.'),
        button('Süre uzat', 'Mevcut işin süresini uzatma akışını açar.', 'Aynı iş devam edecekse kullan.', 'Uzatma alanı açılır.'),
      ],
      screenMenus: [
        { label: 'Gezi / Planlama Merkezi', path: '/organization', purpose: 'Yeni gezi veya organizasyon işi kurmak için açılır.' },
        { label: 'Lokasyon İncele', path: '/organization/georeview', purpose: 'Konum sorunu olan kayıtları düzeltmek için açılır.' },
      ],
      simpleTerms: pickTerms(['atama']),
    });
  }

  if (x.path === '/company/copilot') {
    return screen(2105, '/organization/copilot', 'Copilot', {
      menuPurpose: 'Organizasyon ekranlarında ne yapacağını anlamadığında sade ve adım adım yardım almak için kullanılır.',
      forWhom: 'Organizasyon kullanıcısı içindir.',
      firstStep: 'Önce hangi ekran veya hangi iş hakkında konuşacağını seç.',
      nextStep: 'Gerekirse hızlı geçişle Gezi / Planlama Merkezi, Vardiyalar veya Lokasyon İncele ekranına git.',
      doNotDo: 'Company ekranı gibi kişi-durak çözümü bekleme veya organization işini company metniyle yorumlamaya çalışma.',
      stepByStep: ["Ekranı veya kaydı seç.", "Toplanma noktası, tahmini kişi sayısı, gidilecek yerler ve dönüş tipi adımlarına göre cevabı oku.", "Plan eksikse önce Gezi / Planlama Merkezi'ne dön; plan tamamsa takip için Vardiyalar'a geç."],
      commonMistakes: ['Planlama ve takip ekranlarını karıştırmak.', 'Eksik koordinatı tamamlamadan teklif göndermeye çalışmak.', 'Copilot seçili ekranı company sanmak.'],
      doneChecklist: ['Doğru rehber seçildi.', 'Gerekli ekran açıldı.', 'Sıradaki adım netleşti.'],
      buttonGuides: [
        button('Rehberi aç', 'Seçilen organization rehberini çalıştırır.', 'Yol gösterecek sade yardım istediğinde kullan.', 'Rehber sonucu görünür.'),
        button('Analiz et', 'Gelişmiş analizi çalıştırır.', 'Detaylı yorum gerektiğinde kullan.', 'Gelişmiş sonuç görünür.'),
      ],
      screenMenus: [
        { label: 'Gezi / Planlama Merkezi', path: '/organization', purpose: 'Yeni gezi veya organizasyon işi kurmak için açılır.' },
        { label: 'Vardiyalar', path: '/organization/shifts', purpose: 'İş detaylarını ve takibi görmek için açılır.' },
        { label: 'Lokasyon İncele', path: '/organization/georeview', purpose: 'Konum sorunlarını düzeltmek için açılır.' },
      ],
    });
  }

  return mapped;
}).concat([
  screen(2301, '/organization/plans', 'Yer Planları', {
    menuPurpose: 'Organizasyon yer ve plan kayıtlarını yönetmek için kullanılır.',
    forWhom: 'Organizasyon yönetimi içindir.',
    firstStep: 'Önce doğru planı seç.',
    nextStep: 'Gerekirse iş akışına dön.',
    doNotDo: 'Yanlış plan üzerinde değişiklik yapma.',
    stepByStep: ['Planı seç.', 'Detayı incele.', 'Gerekli değişikliği yap.'],
    commonMistakes: ['Yanlış planı açmak.'],
    doneChecklist: ['Doğru plan açıldı.'],
    buttonGuides: [button('Planı aç', 'Seçili planın detayını açar.', 'Detay görmek için kullan.', 'Plan detayı açılır.')],
    screenMenus: [{ label: 'Organizasyon Merkezi', path: '/organization', purpose: 'Genel özet için açılır.' }],
  }),
]);

const DRIVER = [
  screen(3101, '/driver/today', 'Bugün', {
    menuPurpose: 'Sürücünün bugün ne yapacağını sade şekilde görmek için kullanılır.',
    forWhom: 'Sürücü içindir.',
    firstStep: 'Önce bugün için atanmış işi kontrol et.',
    nextStep: 'Gerekirse rota veya harita ekranına geç.',
    doNotDo: 'Bugün ekranını görmeden yola çıkma.',
    stepByStep: ['Bugünkü işi oku.', 'Saat ve görev durumunu kontrol et.', 'Gerekirse rota ekranına geç.'],
    commonMistakes: ['Göreve bakmadan doğrudan haritaya gitmek.'],
    doneChecklist: ['Bugünkü görev okundu.', 'Sonraki adım netleşti.'],
    buttonGuides: [
      button('Rota aç', 'Bugünkü işin rota ekranını açar.', 'Nereye gideceğini görmek için kullan.', 'Rota ekranı açılır.'),
      button('Harita aç', 'Canlı konum ve harita ekranını açar.', 'Canlı konum görmek için kullan.', 'Harita ekranı açılır.'),
    ],
    screenMenus: [
      { label: 'Rota', path: '/driver/route', purpose: 'Durak sırasını görmek için açılır.' },
      { label: 'Harita', path: '/driver/map', purpose: 'Canlı konumu görmek için açılır.' },
      { label: 'Copilot', path: '/driver/copilot', purpose: 'Takıldığında yardım almak için açılır.' },
    ],
    firstControls: ['Önce bugün için atanmış görev var mı bak.', 'Araç, saat ve durum alanı dolu mu kontrol et.', 'Görev yoksa boş ekranı canlı görev sanma.'],
    stuckChecks: ['Görev görünmüyorsa bugün atanmış vardiya olmayabilir.', 'Bugün ekranını rota ekranı sanma.', 'Canlı takibe geçmeden önce görev özeti okunmalı.'],
    workflowStages: [
      { key: 'DRIVER_TODAY_READ', title: 'Bugünkü görevi oku', action: 'Görev kartındaki iş, saat ve araç bilgisini kontrol et.', doneWhen: 'Nereye ve hangi araçla çıkacağını biliyorsun.', ifBlocked: 'Atama yoksa room/company tarafında sürücü bağı kontrol edilmeli.' },
      { key: 'DRIVER_TODAY_MOVE', title: 'Doğru ekrana geç', action: 'Durak sırası için Rota, canlı konum için Harita ekranına geç.', doneWhen: 'İhtiyacın olan sürücü ekranı açık.', ifBlocked: 'Yanlış ekrana geçersen eksik bilgi ararsın.' },
    ],
    nextScreens: [
      { label: 'Rota', path: '/driver/route', reason: 'Durak sırası ve bir sonraki durak için.' },
      { label: 'Harita', path: '/driver/map', reason: 'Canlı konum, ETA ve sesli destek için.' },
    ],
    dataRules: ['Bugün ekranı görev özetidir; canlı haritanın yerine geçmez.', 'Bugün boşsa sürücüye atanmış aktif vardiya olmayabilir.', 'Araç veya saat bilgisi eksikse room/company tarafında atama bağı kontrol edilmelidir.'],
    chatQuestions: ['Bugün önce neyi kontrol edeyim?', 'Bu seçili kayıtta eksik ne var?', 'Hangi ekrana geçeyim?', 'Bu buton ne yapar?'],
    fieldGuides: [
      { label: 'Görev', meaning: 'Bugün yapacağın işin özet başlığıdır.' },
      { label: 'Araç', meaning: 'Göreve bağlı araç bilgisidir.', risk: 'Boşsa atama eksik olabilir.' },
      { label: 'Saat', meaning: 'İşe çıkış veya başlangıç zamanını gösterir.', risk: 'Eksikse sürücü hazırlığı net değildir.' },
      { label: 'Durum', meaning: 'Bugünkü görevin hangi aşamada olduğunu gösterir.' },
    ],
    badgeGuides: [
      { label: 'ACTIVE', meaning: 'Görev bugün aktif ilerliyor olabilir.' },
      { label: 'APPROVED', meaning: 'Görev onaylıdır fakat sürücü açısından detay yine okunmalıdır.' },
      { label: 'YOK', meaning: 'Bugün atanmış görev görünmüyor olabilir.', actionHint: 'Room/company tarafında sürücü atamasını kontrol et.' },
    ],
    rowReadHint: 'Önce görev ve araç bilgisini oku. Sonra saat ve durum alanıyla bugün ne yapacağını netleştir. Eksik alan varsa rota veya haritaya geçmeden önce atama tarafını kontrol et.',
  }),
  screen(3102, '/driver/route', 'Rota', {
    menuPurpose: 'Durak sırasını ve rota akışını görmek için kullanılır.',
    forWhom: 'Sürücü içindir.',
    firstStep: 'Önce sıradaki durağı kontrol et.',
    nextStep: 'Gerekirse harita ekranına geç.',
    doNotDo: 'Sıradaki durağı okumadan yola devam etme.',
    stepByStep: ['Durakları sırayla oku.', 'Sıradaki durağı netleştir.', 'Gerekirse haritaya geç.'],
    commonMistakes: ['Yanlış durağı sıradaki sanmak.'],
    doneChecklist: ['Sıradaki durak netleşti.'],
    buttonGuides: [button('Harita aç', 'Rota için haritayı açar.', 'Yol ve konum görmek için kullan.', 'Harita ekranı açılır.')],
    screenMenus: [{ label: 'Bugün', path: '/driver/today', purpose: 'Görev özetine dönmek için açılır.' }],
  }),
  screen(3103, '/driver/map', 'Harita', {
    menuPurpose: 'Sürücünün canlı konumunu ve işi harita üzerinde görmek için kullanılır.',
    forWhom: 'Sürücü içindir.',
    firstStep: 'Önce konumun güncel görünüp görünmediğine bak.',
    nextStep: 'Sorun varsa Copilot rehberine geç.',
    doNotDo: 'Eski konumu canlı sanma.',
    stepByStep: ['Harita açıldı mı kontrol et.', 'Konum güncelliğine bak.', 'Sorun varsa yardım aç.'],
    commonMistakes: ['Eski konumu yeni sanmak.'],
    doneChecklist: ['Konum kontrol edildi.'],
    buttonGuides: [
      button('Yenile', 'Harita ve görev verisini yeniden yükler.', 'Bilgi eski kaldıysa kullan.', 'Araç, durak ve rota özeti tekrar çekilir.'),
      button('Sonraki Durağa Navigasyon', 'Sıradaki durak için dış navigasyonu açar.', 'Sıradaki durağa gitmek istediğinde kullan.', 'Telefon navigasyonu sıradaki durağa göre açılır.'),
      button('Tam Rotayı Dış Navigasyonda Aç', 'Tüm durakları dış navigasyonda açar.', 'Mini önizleme yerine tam yol tarifi istediğinde kullan.', 'Harici navigasyon tam rota ile açılır.'),
      button('Yardım aç', 'Konum görünmüyorsa rehber ekranını açar.', 'Takıldığında kullan.', 'Copilot ekranı açılır.'),
    ],
    screenMenus: [{ label: 'Copilot', path: '/driver/copilot', purpose: 'Konum sorularında rehber almak için açılır.' }],
    simpleTerms: pickTerms(['telefonGps', 'cihazGps', 'konumKaynagi']),
    dataRules: ['Sıradaki durak, mesafe ve ETA hareket ettikçe değişmelidir; sabit kalıyorsa rota yenilenmiyor olabilir.', 'Ekran kapanınca canlılık düşüyorsa background location zinciri kontrol edilmelidir.', 'Auto reached durak yakınlığına ve aktif görev bağlamına göre çalışır; yalnız haritaya bakarak anlaşılmaz.', 'Sesli destek operasyonu yönlendirmek içindir; yalnız konuşması değil doğru anda konuşması önemlidir.'],
    fieldGuides: [
      { label: 'Son GPS', meaning: 'Konum bilgisinin en son ne zaman geldiğini gösterir.', risk: 'Eskiyse canlılık yanıltıcı olabilir.' },
      { label: 'Sıradaki Durak', meaning: 'Sıradaki hedef durağı gösterir.' },
      { label: 'Mesafe', meaning: 'Sıradaki durağa kalan yaklaşık yolu gösterir.' },
      { label: 'ETA', meaning: 'Sıradaki durağa tahmini kalan süredir.', risk: 'Sabit kalıyorsa rota yenilenmiyor olabilir.' },
      { label: 'Alınacak Yolcu', meaning: 'Sıradaki durakta alınması beklenen yolcu sayısıdır.' },
    ],
    badgeGuides: [
      { label: 'ONLINE', meaning: 'Canlı GPS akışı geliyor.' },
      { label: 'OFFLINE', meaning: 'Canlı GPS akışı görünmüyor olabilir.', actionHint: 'İzin, bağlantı ve background GPS zincirini kontrol et.' },
      { label: 'ACTIVE', meaning: 'Görev aktif ilerliyor.' },
      { label: 'REACHED', meaning: 'Durak ulaşıldı olarak işaretlenmiş olabilir.' },
    ],
    firstControls: ['Önce konum güncel mi bak.', 'Sıradaki durak, mesafe ve ETA değişiyor mu kontrol et.', 'Ekran kapanınca canlılık sürüyor mu test et.'],
    stuckChecks: ['Harita var ama konum akmıyorsa background GPS izni veya yayın zinciri düşmüş olabilir.', 'ETA sabit kalıyorsa rota tekrar çekilmiyor olabilir.', 'Auto reached çalışmıyorsa mesafe eşiği veya aktif görev bağını kontrol et.'],
    workflowStages: [
      { key: 'DRIVER_MAP_SIGNAL', title: 'Canlılığı doğrula', action: 'Harita açıldıktan sonra araç pininin ve son GPS zamanının hareket ettikçe değiştiğini kontrol et.', doneWhen: 'Konum akışı canlı görünüyor.', ifBlocked: 'Ekran kapanınca akış düşüyorsa background location akışını kontrol et.' },
      { key: 'DRIVER_MAP_STOP', title: 'Durak otomasyonunu izle', action: 'Sıradaki durak, mesafe ve auto reached davranışını takip et.', doneWhen: 'Durak gelince reached olur ve sonraki durak bilgisi güncellenir.', ifBlocked: 'ETA veya mesafe değişmiyorsa rota refresh zincirini kontrol et.' },
      { key: 'DRIVER_MAP_VOICE', title: 'Sesli desteği doğrula', action: 'Durak yaklaşınca alınacak yolcu sayısı ve sonraki durak ETA bilgisinin okunup okunmadığını dinle.', doneWhen: 'Sesli destek operasyonu gerçekten yönlendirir.', ifBlocked: 'Sesli destek yalnız ön planda çalışıyorsa cihaz güç yönetimini ve speech akışını kontrol et.' },
    ],
    nextScreens: [
      { label: 'Bugün', path: '/driver/today', reason: 'Görev özetine dönmek için.' },
      { label: 'Copilot', path: '/driver/copilot', reason: 'Canlılık veya ETA sorununu adım adım teşhis etmek için.' },
    ],
    chatQuestions: ['Konum neden güncellenmiyor?', 'Önce neyi kontrol edeyim?', 'Auto reached neden olmuyor?', 'Sesli destek ne zaman konuşur?'],
  }),
  screen(3104, '/driver/checkin', 'Check-in', {
    menuPurpose: 'Sürücünün check-in veya doğrulama tarafını görmek için kullanılır.',
    forWhom: 'Sürücü içindir.',
    firstStep: 'Önce hangi doğrulama adımında olduğunu kontrol et.',
    nextStep: 'Gerekirse Bugün ekranına dön.',
    doNotDo: 'Check-in yapılınca tüm görevin bittiğini sanma.',
    stepByStep: ['Kayıdı aç.', 'Check-in durumunu oku.', 'Gerekirse görev ekranına dön.'],
    commonMistakes: ['Check-in ile görevin tamamını karıştırmak.'],
    doneChecklist: ['Check-in anlamı netleşti.'],
    buttonGuides: [button('Yardım aç', 'Check-in ne demek sorusuna sade yardım açar.', 'Takıldığında kullan.', 'Copilot ekranı açılır.')],
    screenMenus: [{ label: 'Bugün', path: '/driver/today', purpose: 'Görev özetine dönmek için açılır.' }],
    simpleTerms: pickTerms(['checkin']),
  }),
  screen(3105, '/driver/copilot', 'Copilot', {
    menuPurpose: 'Sürücünün ekranda ne yapacağını anlaması için sade yardım verir.',
    forWhom: 'Sürücü içindir.',
    firstStep: 'Önce hangi ekranı anlamak istediğini seç.',
    nextStep: 'Gerekirse ilgili ekrana hızlı geçiş kullan.',
    doNotDo: 'Görev ekranını görmeden genel yorumla yetinme.',
    stepByStep: ['Ekranı seç.', 'Rehberi aç.', 'Sonucu uygula.'],
    commonMistakes: ['Yanlış ekranı seçmek.'],
    doneChecklist: ['İlgili ekran rehberi açıldı.'],
    buttonGuides: [button('Rehberi aç', 'Ekran rehberini çalıştırır.', 'Ne yapacağını bilmiyorsan kullan.', 'Sade yardım görünür.')],
    firstControls: ['Önce hangi ekran veya kayıt hakkında konuşacağını seç.', 'Seçili vardiya/araç bağlamı varsa doğru geldi mi kontrol et.', 'Kısa soru yerine bağlamı söyleyen soru sor.'],
    stuckChecks: ['Yanlış ekran seçiliyse cevap genel kalır.', 'Seçili kayıt yoksa copilot yalnız ekran seviyesinde yanıt verir.', 'Kısa takip sorularında önceki bağlamı korumak için aynı sohbeti sürdür.'],
    workflowStages: [
      { key: 'COPILOT_SCOPE', title: 'Bağlamı netleştir', action: 'Önce ekranı ve varsa seçili kaydı doğrula.', doneWhen: 'Copilot üstünde doğru ekran ve seçili kayıt görünür.', ifBlocked: 'Yanlış scope varsa ilgili ekrana dönüp kaydı yeniden seç.' },
      { key: 'COPILOT_ASK', title: 'Doğru soru tipini sor', action: 'Önce neyi kontrol edeyim, kontrol listesi ver, sık hata ne, hangi ekrana geçeyim gibi sorular kullan.', doneWhen: 'Cevap operasyonel ve adım adım gelir.', ifBlocked: 'Soru çok genelse daha spesifik ekran veya kayıt belirt.' },
      { key: 'COPILOT_APPLY', title: 'Cevabı ekrana uygula', action: 'Quick action veya önerilen ekran geçişini aç.', doneWhen: 'Konuşma ekranda bir sonraki adıma dönüşür.', ifBlocked: 'Yalnız sohbet edip ekrana dönmüyorsan değer üretemez.' },
    ],
    nextScreens: [
      { label: 'Bugün', path: '/driver/today', reason: 'Görev özetine dönmek için.' },
      { label: 'Harita', path: '/driver/map', reason: 'Canlılık, ETA ve rota takibi için.' },
      { label: 'Rota', path: '/driver/route', reason: 'Durak sırasını görmek için.' },
    ],
    chatQuestions: ['Bu ekranda önce neyi kontrol edeyim?', 'Kontrol listesi ver', 'Sık hata ne?', 'Hangi ekrana geçeyim?'],
  }),
];

const PERSONEL = [
  screen(4101, '/personel/live', 'Canlı', {
    menuPurpose: 'Servisin canlı durumunu görmek için kullanılır.',
    forWhom: 'Personel içindir.',
    firstStep: 'Önce konum ve durum bilgisini oku.',
    nextStep: 'Gerekirse Servisim ekranına geç.',
    doNotDo: 'Eski bilgiyi canlı sanma.',
    stepByStep: ['Canlı bilgiyi oku.', 'Konum güncel mi bak.', 'Gerekirse diğer ekrana geç.'],
    commonMistakes: ['Eski bilgiye göre hareket etmek.'],
    doneChecklist: ['Canlı durum okundu.'],
    buttonGuides: [button('Servisimi aç', 'Kendi servis detayını açar.', 'Daha fazla bilgi gerektiğinde kullan.', 'Servisim ekranı açılır.')],
    screenMenus: [{ label: 'Servisim', path: '/personel/my', purpose: 'Kendi servis detayın için açılır.' }, { label: 'Copilot', path: '/personel/copilot', purpose: 'Takıldığında yardım için açılır.' }],
  }),
  screen(4102, '/personel/my', 'Servisim', {
    menuPurpose: 'Kendi servis bilgini görmek için kullanılır.',
    forWhom: 'Personel içindir.',
    firstStep: 'Önce hangi servise bağlı olduğunu kontrol et.',
    nextStep: 'Gerekirse canlı ekrana dön.',
    doNotDo: 'Başka kişiye ait bilgi bekleme.',
    stepByStep: ['Kayıt bilgisini oku.', 'Araç ve durum bilgisini kontrol et.', 'Gerekirse canlı ekrana dön.'],
    commonMistakes: ['Bu ekranı canlı takip ekranı sanmak.'],
    doneChecklist: ['Kendi servis bilgisi okundu.'],
    buttonGuides: [button('Canlı aç', 'Canlı takip ekranına döner.', 'Konum görmek istediğinde kullan.', 'Canlı ekran açılır.')],
    screenMenus: [{ label: 'Canlı', path: '/personel/live', purpose: 'Canlı duruma dönmek için açılır.' }, { label: 'Copilot', path: '/personel/copilot', purpose: 'Rehber almak için açılır.' }],
  }),
  screen(4103, '/personel/copilot', 'Copilot', {
    menuPurpose: 'Personel kullanıcısına çok sade ekran yardımı verir.',
    forWhom: 'Personel içindir.',
    firstStep: 'Önce anlamak istediğin ekranı seç.',
    nextStep: 'Gerekirse ilgili ekrana git.',
    doNotDo: 'Yanlış ekrana göre yardım alma.',
    stepByStep: ['Ekranı seç.', 'Rehberi aç.', 'Yönlendirmeyi uygula.'],
    commonMistakes: ['Canlı ile Servisim ekranını karıştırmak.'],
    doneChecklist: ['Doğru yardım açıldı.'],
    buttonGuides: [button('Rehberi aç', 'Sade ekran yardımını çalıştırır.', 'Takıldığında kullan.', 'Yardım sonucu görünür.')],
  }),
];

const PARENT = [
  screen(5101, '/parent/live', 'Canlı', {
    menuPurpose: 'Çocuğun canlı durumunu ve yol bilgisini görmek için kullanılır.',
    forWhom: 'Veli içindir.',
    firstStep: 'Önce canlı bilgi ve zaman bilgisini oku.',
    nextStep: 'Sorun varsa yardım ekranına geç.',
    doNotDo: 'Eski bilgiyi canlı sanma.',
    stepByStep: ['Canlı bilgiyi aç.', 'Zaman ve durum bilgisini oku.', 'Gerekirse yardım aç.'],
    commonMistakes: ['Eski canlı veriyi güncel sanmak.'],
    doneChecklist: ['Canlı bilgi okundu.'],
    buttonGuides: [button('Yardım aç', 'Bu ekranın ne anlattığını açıklar.', 'Bilginin ne olduğunu anlamıyorsan kullan.', 'Copilot ekranı açılır.')],
    screenMenus: [{ label: 'Copilot', path: '/parent/copilot', purpose: 'Sade yardım almak için açılır.' }],
  }),
  screen(5102, '/parent/copilot', 'Copilot', {
    menuPurpose: 'Veliye canlı ekranı sade dille açıklar ve doğru yere yönlendirir.',
    forWhom: 'Veli içindir.',
    firstStep: 'Önce hangi ekranı anlamak istediğini seç.',
    nextStep: 'Sonra gerekirse canlı ekrana dön.',
    doNotDo: 'Canlı veri ile tahmini zamanı aynı şey sanma.',
    stepByStep: ['Ekranı seç.', 'Rehberi aç.', 'Gerekirse canlı ekrana dön.'],
    commonMistakes: ['Canlı ile tahmini zamanı karıştırmak.'],
    doneChecklist: ['Ekran daha anlaşılır hale geldi.'],
    buttonGuides: [button('Rehberi aç', 'Seçili ekran için sade yardım üretir.', 'Ne gördüğünü anlamıyorsan kullan.', 'Sade yardım görünür.')],
  }),
];

const SUPER_ADMIN = [
  screen(6101, '/superadmin', 'Overview', {
    menuPurpose: 'Sistem genelini üst seviyede görmek için kullanılır.',
    forWhom: 'Super admin içindir.',
    firstStep: 'Önce hangi alana ineceğine karar ver.',
    nextStep: 'Gerekirse şirket, oda veya kullanıcı ekranına geç.',
    doNotDo: 'Özet ekranı detay ekranı sanma.',
    stepByStep: ['Özet kartları oku.', 'İlgili yönetim ekranına geç.', 'Detayı orada incele.'],
    commonMistakes: ['Özet bilgiyi detay sanmak.'],
    doneChecklist: ['Doğru yönetim alanı seçildi.'],
    buttonGuides: [button('Alanı aç', 'Özetten ilgili yönetim alanına geçer.', 'Detaya inmek istediğinde kullan.', 'İlgili ekran açılır.')],
    screenMenus: [{ label: 'Companies', path: '/superadmin/companies', purpose: 'Şirket yönetimi için açılır.' }, { label: 'Rooms', path: '/superadmin/rooms', purpose: 'Oda yönetimi için açılır.' }, { label: 'Copilot', path: '/superadmin/copilot', purpose: 'Yardım için açılır.' }],
  }),
  screen(6102, '/superadmin/companies', 'Companies', {
    menuPurpose: 'Şirket kayıtlarını yönetmek için kullanılır.',
    forWhom: 'Super admin içindir.',
    firstStep: 'Önce doğru şirketi seç.',
    nextStep: 'Gerekirse kullanıcı veya oda tarafına geç.',
    doNotDo: 'Yanlış şirket üzerinde değişiklik yapma.',
    stepByStep: ['Şirketi seç.', 'Detayı incele.', 'Gerekirse diğer yönetime geç.'],
    commonMistakes: ['Yanlış şirketi açmak.'],
    doneChecklist: ['Doğru şirket seçildi.'],
    buttonGuides: [button('Şirketi aç', 'Şirket detayını açar.', 'Detay görmek için kullan.', 'Detay alanı açılır.')],
    screenMenus: [{ label: 'Rooms', path: '/superadmin/rooms', purpose: 'Oda bağlantısını görmek için açılır.' }, { label: 'Users', path: '/superadmin/users', purpose: 'Kullanıcı bağlantısını görmek için açılır.' }],
  }),
  screen(6105, '/superadmin/rooms', 'Rooms', {
    menuPurpose: 'Oda kayıtlarını, bağlantılarını ve kapsama alanını yönetmek için kullanılır.',
    forWhom: 'Super admin içindir.',
    firstStep: 'Önce doğru odayı seç.',
    nextStep: 'Gerekirse şirkete, kullanıcıya veya kalite ekranına geç.',
    doNotDo: 'Oda bağlantısını hangi şirkete ait olduğunu okumadan değiştirme.',
    stepByStep: ['Odayı seç.', 'Bağlı şirket ve kapsamı kontrol et.', 'Gerekirse ilişkili yönetim ekranına geç.'],
    commonMistakes: ['Yanlış odayı açmak.', 'Kapsamı görmeden karar vermek.'],
    doneChecklist: ['Doğru oda seçildi.', 'Bağlantı bilgisi okundu.'],
    buttonGuides: [button('Odayı aç', 'Seçili odayı detaylı incelemeye götürür.', 'Bağlantı ve kapsamı görmek istediğinde kullan.', 'Oda detay akışı açılır.')],
    screenMenus: [{ label: 'Companies', path: '/superadmin/companies', purpose: 'Bağlı şirketi kontrol etmek için açılır.' }, { label: 'Users', path: '/superadmin/users', purpose: 'Yetkili kullanıcıları görmek için açılır.' }, { label: 'Operasyon Doğrulama', path: '/superadmin/operation-verification', purpose: 'Rol ve operasyon yüzeyini doğrulamak için açılır.' }],
  }),
  screen(6106, '/superadmin/users', 'Users', {
    menuPurpose: 'Kullanıcı kayıtlarını, rollerini ve erişim durumunu yönetmek için kullanılır.',
    forWhom: 'Super admin içindir.',
    firstStep: 'Önce doğru kullanıcıyı veya rol filtresini seç.',
    nextStep: 'Gerekirse oda, şirket veya güven ekranına geç.',
    doNotDo: 'Rol ve erişim kapsamını okumadan kullanıcı üzerinde karar verme.',
    stepByStep: ['Kullanıcıyı veya rolü seç.', 'Erişim ve rol bilgisini oku.', 'Gerekirse ilişkili yönetim ekranına geç.'],
    commonMistakes: ['Yanlış kullanıcı üzerinde işlem yapmak.', 'Rol ile şirket/oda kapsamını karıştırmak.'],
    doneChecklist: ['Doğru kullanıcı veya rol filtresi seçildi.', 'Erişim durumu okundu.'],
    buttonGuides: [button('Kullanıcıyı aç', 'Seçili kullanıcıyı detaylı incelemeye götürür.', 'Rol veya erişim durumunu netleştirmek istediğinde kullan.', 'Kullanıcı detay akışı açılır.')],
    screenMenus: [{ label: 'Rooms', path: '/superadmin/rooms', purpose: 'Kullanıcının bağlı olduğu oda tarafını görmek için açılır.' }, { label: 'Companies', path: '/superadmin/companies', purpose: 'Kullanıcının bağlı olduğu şirketi görmek için açılır.' }, { label: 'Güven ve Kalite', path: '/superadmin/trust-quality', purpose: 'Kritik rol ve kalite sinyalini birlikte okumak için açılır.' }],
  }),
  screen(6103, '/superadmin/audit', 'Audit', {
    menuPurpose: 'İşlem kayıtlarını ve izleri görmek için kullanılır.',
    forWhom: 'Super admin içindir.',
    firstStep: 'Önce neyi aradığını netleştir.',
    nextStep: 'Gerekirse log export veya Copilot ekranına geç.',
    doNotDo: 'Log ile audit kaydını aynı şey sanma.',
    stepByStep: ['Filtreyi seç.', 'Kayıtları incele.', 'Gerekirse dışa aktar.'],
    commonMistakes: ['Yanlış zaman aralığı ile arama yapmak.'],
    doneChecklist: ['İlgili kayıt bulundu.'],
    buttonGuides: [button('Filtrele', 'İşlem kayıtlarını daraltır.', 'Belirli işlem ararken kullan.', 'Liste daha anlamlı hale gelir.')],
    screenMenus: [{ label: 'Log Export', path: '/superadmin/logexport', purpose: 'Dışa aktarım için açılır.' }, { label: 'Copilot', path: '/superadmin/copilot', purpose: 'Kayıtları açıklatmak için açılır.' }],
    simpleTerms: pickTerms(['islemKaydi']),
  }),
  screen(6107, '/superadmin/observability', 'Canlı İzleme', {
    menuPurpose: 'Canlı sağlık, GPS güveni ve son olayları tek ekranda okumak için kullanılır.',
    forWhom: 'Super admin içindir.',
    firstStep: 'Önce canlı durum ve GPS güven skorunu oku.',
    nextStep: 'Sonra son canlı olaylara ve cihaz riskine in.',
    doNotDo: 'GPS skoru ile canlı durumu aynı şey sanma.',
    stepByStep: ['Canlı durum kartını oku.', 'GPS güven notlarını kontrol et.', 'Son olay ve cihaz riskini birlikte değerlendir.'],
    commonMistakes: ['Tek bir event ile genel sağlık kararı vermek.', 'Son sync ve son GPS zamanını atlamak.'],
    doneChecklist: ['Canlı durum okundu.', 'Risk alanı belirlendi.'],
    buttonGuides: [button('Yenile', 'Canlı sağlık özetini tekrar yükler.', 'Verinin eski kaldığını düşünüyorsan kullan.', 'Özet, event type ve son olay listesi güncellenir.')],
    screenMenus: [{ label: 'Operasyon Doğrulama', path: '/superadmin/operation-verification', purpose: 'Kanıt ve kayıt tarafına geçmek için açılır.' }, { label: 'Kabul Merkezi', path: '/superadmin/acceptance', purpose: 'Saha kabul kararına etkisini görmek için açılır.' }],
  }),
  screen(6108, '/superadmin/acceptance', 'Kabul Merkezi', {
    menuPurpose: 'Saha kabul kararı, checklist ve test oturumu özetini birlikte okumak için kullanılır.',
    forWhom: 'Super admin içindir.',
    firstStep: 'Önce PASS olmayan checklist maddelerini belirle.',
    nextStep: 'Sonra kabul kararını tekrar değerlendir.',
    doNotDo: 'Checklist kapanmadan ACCEPT kararını kesin sanma.',
    stepByStep: ['Checklist maddelerini oku.', 'Bekleyenleri kapat.', 'En son karar alanını gözden geçir.'],
    commonMistakes: ['Checklist ile kabul kararını birbirinin yerine koymak.'],
    doneChecklist: ['Açık maddeler belirlendi.', 'Karar yeniden gözden geçirildi.'],
    buttonGuides: [button('Yenile', 'Manifest ve test oturumu özetini tekrar çeker.', 'Checklist veya karar yeni değiştiyse kullan.', 'Kabul merkezi güncel veriyle tekrar yüklenir.')],
    screenMenus: [{ label: 'Canlı İzleme', path: '/superadmin/observability', purpose: 'Saha sağlığını acceptance öncesi görmek için açılır.' }, { label: 'Pilot Launch Gate', path: '/superadmin/pilot-launch-gate', purpose: 'Sahaya çıkış kararını görmek için açılır.' }],
  }),
  screen(6109, '/superadmin/operation-verification', 'Operasyon Doğrulama', {
    menuPurpose: 'Rol bazlı operasyon kontrollerini kanıt tipi ve kısa notla kayıt altına almak için kullanılır.',
    forWhom: 'Super admin içindir.',
    firstStep: 'Önce kontrol edilecek rolü seç.',
    nextStep: 'Sonra her kontrol maddesinde durum, kanıt ve notu tamamla.',
    doNotDo: 'Sadece varsayılan karara bakıp manuel kayıt ihtiyacını atlama.',
    stepByStep: ['Rolü seç.', 'Kontrol maddelerini sırayla oku.', 'Kanıt tipini ve notu kaydet.'],
    commonMistakes: ["Rol değişince eski draftı doğru sanmak.", "Kanıt tipini boş bırakmak."],
    doneChecklist: ['Doğru rol seçildi.', 'Kontroller kaydedildi.'],
    buttonGuides: [button('Kaydet', 'Seçili kontrol maddesi için durum, kanıt ve notu kayıt altına alır.', 'Kontrol maddesini netleştirdiğinde kullan.', 'Kayıt, role surface üzerinde görünür hale gelir.')],
    screenMenus: [{ label: 'Canlı İzleme', path: '/superadmin/observability', purpose: 'Canlı kanıt ve saha sinyalini desteklemek için açılır.' }, { label: 'Kabul Merkezi', path: '/superadmin/acceptance', purpose: 'Saha kabul checklisti ile birlikte okumak için açılır.' }],
  }),
  screen(6113, '/superadmin/trust-quality', 'Güven ve Kalite', {
    menuPurpose: 'Hizmet değerlendirmesi ve sağlayıcı kalite sinyalini birlikte görmek için kullanılır.',
    forWhom: 'Super admin içindir.',
    firstStep: 'Önce kalite özeti ile sağlayıcı sinyalini birlikte oku.',
    nextStep: 'Gerekirse hizmet değerlendirme veya ticari akış tarafına in.',
    doNotDo: 'Tek bir puan ile tüm güven kararını verme.',
    stepByStep: ['Kalite özetini oku.', 'Sinyal setini gözden geçir.', 'Gerekirse bağlı hizmet ekranına geç.'],
    commonMistakes: ['Hizmet puanı ile sağlayıcı sinyalini karıştırmak.'],
    doneChecklist: ['Kalite sinyali okundu.'],
    screenMenus: [{ label: 'Operasyon Doğrulama', path: '/superadmin/operation-verification', purpose: 'Kalite ve güven kontrolünü role surface tarafında desteklemek için açılır.' }],
  }),
  screen(6104, '/superadmin/copilot', 'Copilot', {
    menuPurpose: 'Sistem genelinde rehber ve açıklama almak için kullanılır.',
    forWhom: 'Super admin içindir.',
    firstStep: 'Önce iş veya ekran rehberini seç.',
    nextStep: 'Gerekirse ilgili yönetim ekranına geç.',
    doNotDo: 'Detayı seçmeden genel yorumla yetinme.',
    stepByStep: ['Rehberi seç.', 'Sonucu oku.', 'Gerekirse yönetim ekranına geç.'],
    commonMistakes: ['Yanlış kapsam için rehber açmak.'],
    doneChecklist: ['Doğru rehber seçildi.'],
    buttonGuides: [button('Rehberi aç', 'Seçili yardım akışını çalıştırır.', 'Ekran veya iş açıklaması gerektiğinde kullan.', 'Sonuç görünür.')],
  }),
];

const SCREEN_CATALOG = { ROOM, COMPANY, SCHOOL, ORGANIZATION, DRIVER, PERSONEL, PARENT, SUPER_ADMIN };

export function resolveRoleGuideKey(user, screenContext = {}) {
  const hinted = inferGuideKeyFromScreen(screenContext);
  if (hinted) return hinted;
  const role = String(user?.role || '');
  if (role === 'COMPANY') {
    const kind = String(user?.companyKind || '').toUpperCase();
    if (kind === 'SCHOOL') return 'SCHOOL';
    if (kind === 'ORGANIZATION') return 'ORGANIZATION';
    return 'COMPANY';
  }
  return role || 'ROOM';
}

export function listScreensForUser(user, screenContext = {}) {
  const key = resolveRoleGuideKey(user, screenContext);
  return (SCREEN_CATALOG[key] || []).map((x) => ({ id: x.id, path: x.path, label: x.label }));
}

export function getScreenDefinitionForUser(user, screenContext = {}, entityId = null) {
  const key = resolveRoleGuideKey(user, screenContext);
  const list = SCREEN_CATALOG[key] || [];
  const rawPath = String(screenContext?.path || '').split('?')[0] || '';
  let found = null;
  if (rawPath) found = list.find((x) => x.path === rawPath) || null;
  if (!found && entityId != null) found = list.find((x) => Number(x.id) === Number(entityId)) || null;
  if (!found) found = list[0] || null;
  if (!found) return null;
  return {
    type: 'screen',
    id: Number(entityId || found.id || 0),
    roleKey: key,
    roleLabel: key === 'SCHOOL' ? 'OKUL' : key === 'ORGANIZATION' ? 'ORGANİZASYON' : key,
    label: found.label,
    ...found,
  };
}

export function buildRoleHelpSummary(user, screenContext = {}) {
  const key = resolveRoleGuideKey(user, screenContext);
  const list = SCREEN_CATALOG[key] || [];
  const first = list[0] || null;
  return {
    roleKey: key,
    roleLabel: key === 'SCHOOL' ? 'OKUL' : key === 'ORGANIZATION' ? 'ORGANİZASYON' : key,
    screens: list.map((x) => ({ label: x.label, path: x.path, purpose: x.menuPurpose })),
    firstPath: first?.path || '',
  };
}
