import { RoomFinalListSection, RoomPendingSection } from "./roomShiftsPanelSections";
import { RoomShiftsDispatchPoolSection } from "./roomShiftsOverviewSection";

export function RoomShiftsMainSections({
  pendingStatus,
  setPendingStatus,
  pendingQ,
  setPendingQ,
  onlyAgreement,
  setOnlyAgreement,
  pendingFiltered,
  offersByShiftId,
  effectiveShiftRoomId,
  vehiclesForRoom,
  assignSel,
  vehiclesById,
  showAvailableOnly,
  isVehicleAvailableForShift,
  driversById,
  driverSel,
  avail,
  busy,
  openRoutePreview,
  setAssignSel,
  setDriverSel,
  drivers,
  uiCopyVehicleToPkg,
  uiCopyDriverToPkg,
  toggleAvailable,
  roomsById,
  approveShift,
  rejectShift,
  setFocusedTrackShiftId,
  copilotShiftId,
  poolSummary,
  dispatchPreview,
  getDispatchSelectionStates,
  driversForRoom,
  selectedDispatchVehicleId,
  selectedDispatchDriverId,
  buildDispatchVirtualShift,
  setDispatchSelection,
  openDispatchSuggestionPreview,
  loadPoolSummary,
  loadDispatchPreview,
  autoSplitApprove,
  listStatus,
  setListStatus,
  listQ,
  setListQ,
  copilotShift,
  listFiltered,
  items,
  extendNoteSel,
  setExtendNote,
  decideExtend,
  openOpsEvents,
  openReassignModal,
}) {
  function renderPoolSummary(shift, capacityMeta, effectiveRoomId = null) {
    return (
      <RoomShiftsDispatchPoolSection
        shift={shift}
        capacityMeta={capacityMeta}
        effectiveRoomId={effectiveRoomId}
        poolSummary={poolSummary}
        dispatchPreview={dispatchPreview}
        getDispatchSelectionStates={getDispatchSelectionStates}
        vehiclesForRoom={vehiclesForRoom}
        driversForRoom={driversForRoom}
        selectedDispatchVehicleId={selectedDispatchVehicleId}
        selectedDispatchDriverId={selectedDispatchDriverId}
        vehiclesById={vehiclesById}
        driversById={driversById}
        buildDispatchVirtualShift={buildDispatchVirtualShift}
        setDispatchSelection={setDispatchSelection}
        openDispatchSuggestionPreview={openDispatchSuggestionPreview}
        loadPoolSummary={loadPoolSummary}
        loadDispatchPreview={loadDispatchPreview}
        autoSplitApprove={autoSplitApprove}
        busy={busy}
      />
    );
  }

  return (
    <>
      <RoomPendingSection
        pendingStatus={pendingStatus}
        setPendingStatus={setPendingStatus}
        pendingQ={pendingQ}
        setPendingQ={setPendingQ}
        onlyAgreement={onlyAgreement}
        setOnlyAgreement={setOnlyAgreement}
        pendingFiltered={pendingFiltered}
        offersByShiftId={offersByShiftId}
        effectiveShiftRoomId={effectiveShiftRoomId}
        vehiclesForRoom={vehiclesForRoom}
        assignSel={assignSel}
        vehiclesById={vehiclesById}
        showAvailableOnly={showAvailableOnly}
        isVehicleAvailableForShift={isVehicleAvailableForShift}
        driversById={driversById}
        driverSel={driverSel}
        avail={avail}
        busy={busy}
        openRoutePreview={openRoutePreview}
        renderPoolSummary={renderPoolSummary}
        setAssignSel={setAssignSel}
        setDriverSel={setDriverSel}
        drivers={drivers}
        uiCopyVehicleToPkg={uiCopyVehicleToPkg}
        uiCopyDriverToPkg={uiCopyDriverToPkg}
        toggleAvailable={toggleAvailable}
        roomsById={roomsById}
        approveShift={approveShift}
        rejectShift={rejectShift}
        setFocusedTrackShiftId={setFocusedTrackShiftId}
        copilotShiftId={copilotShiftId}
      />

      <RoomFinalListSection
        listStatus={listStatus}
        setListStatus={setListStatus}
        listQ={listQ}
        setListQ={setListQ}
        onlyAgreement={onlyAgreement}
        setOnlyAgreement={setOnlyAgreement}
        copilotShift={copilotShift}
        listFiltered={listFiltered}
        items={items}
        offersByShiftId={offersByShiftId}
        vehiclesById={vehiclesById}
        extendNoteSel={extendNoteSel}
        setExtendNote={setExtendNote}
        busy={busy}
        decideExtend={decideExtend}
        openOpsEvents={openOpsEvents}
        openReassignModal={openReassignModal}
        openRoutePreview={openRoutePreview}
        setFocusedTrackShiftId={setFocusedTrackShiftId}
        copilotShiftId={copilotShiftId}
      />
    </>
  );
}
